# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import billing_pb2 as evs_dot_v1_dot_billing__pb2


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsage = channel.unary_unary(
                '/evs.v1.BillingService/GetUsage',
                request_serializer=evs_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_billing__pb2.GetUsageResponse.FromString,
                _registered_method=True)
        self.ListInvoices = channel.unary_unary(
                '/evs.v1.BillingService/ListInvoices',
                request_serializer=evs_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_billing__pb2.ListInvoicesResponse.FromString,
                _registered_method=True)
        self.RecordUsage = channel.unary_unary(
                '/evs.v1.BillingService/RecordUsage',
                request_serializer=evs_dot_v1_dot_billing__pb2.RecordUsageRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_billing__pb2.RecordUsageResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=evs_dot_v1_dot_billing__pb2.GetUsageRequest.FromString,
                    response_serializer=evs_dot_v1_dot_billing__pb2.GetUsageResponse.SerializeToString,
            ),
            'ListInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInvoices,
                    request_deserializer=evs_dot_v1_dot_billing__pb2.ListInvoicesRequest.FromString,
                    response_serializer=evs_dot_v1_dot_billing__pb2.ListInvoicesResponse.SerializeToString,
            ),
            'RecordUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsage,
                    request_deserializer=evs_dot_v1_dot_billing__pb2.RecordUsageRequest.FromString,
                    response_serializer=evs_dot_v1_dot_billing__pb2.RecordUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.BillingService/GetUsage',
            evs_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
            evs_dot_v1_dot_billing__pb2.GetUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.BillingService/ListInvoices',
            evs_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
            evs_dot_v1_dot_billing__pb2.ListInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.BillingService/RecordUsage',
            evs_dot_v1_dot_billing__pb2.RecordUsageRequest.SerializeToString,
            evs_dot_v1_dot_billing__pb2.RecordUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
