# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import scheduler_pb2 as evs_dot_v1_dot_scheduler__pb2


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleJob = channel.unary_unary(
                '/evs.v1.SchedulerService/ScheduleJob',
                request_serializer=evs_dot_v1_dot_scheduler__pb2.ScheduleJobRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scheduler__pb2.ScheduleJobResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/evs.v1.SchedulerService/CancelJob',
                request_serializer=evs_dot_v1_dot_scheduler__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scheduler__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/evs.v1.SchedulerService/ListJobs',
                request_serializer=evs_dot_v1_dot_scheduler__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scheduler__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScheduleJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScheduleJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleJob,
                    request_deserializer=evs_dot_v1_dot_scheduler__pb2.ScheduleJobRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scheduler__pb2.ScheduleJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=evs_dot_v1_dot_scheduler__pb2.CancelJobRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scheduler__pb2.CancelJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=evs_dot_v1_dot_scheduler__pb2.ListJobsRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scheduler__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScheduleJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SchedulerService/ScheduleJob',
            evs_dot_v1_dot_scheduler__pb2.ScheduleJobRequest.SerializeToString,
            evs_dot_v1_dot_scheduler__pb2.ScheduleJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SchedulerService/CancelJob',
            evs_dot_v1_dot_scheduler__pb2.CancelJobRequest.SerializeToString,
            evs_dot_v1_dot_scheduler__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SchedulerService/ListJobs',
            evs_dot_v1_dot_scheduler__pb2.ListJobsRequest.SerializeToString,
            evs_dot_v1_dot_scheduler__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
