# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import scoring_pb2 as evs_dot_v1_dot_scoring__pb2


class ScoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreLead = channel.unary_unary(
                '/evs.v1.ScoringService/ScoreLead',
                request_serializer=evs_dot_v1_dot_scoring__pb2.ScoreLeadRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scoring__pb2.ScoreLeadResponse.FromString,
                _registered_method=True)
        self.GetScore = channel.unary_unary(
                '/evs.v1.ScoringService/GetScore',
                request_serializer=evs_dot_v1_dot_scoring__pb2.GetScoreRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scoring__pb2.GetScoreResponse.FromString,
                _registered_method=True)
        self.BatchScore = channel.unary_unary(
                '/evs.v1.ScoringService/BatchScore',
                request_serializer=evs_dot_v1_dot_scoring__pb2.BatchScoreRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_scoring__pb2.BatchScoreResponse.FromString,
                _registered_method=True)


class ScoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScoreLead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreLead': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreLead,
                    request_deserializer=evs_dot_v1_dot_scoring__pb2.ScoreLeadRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scoring__pb2.ScoreLeadResponse.SerializeToString,
            ),
            'GetScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScore,
                    request_deserializer=evs_dot_v1_dot_scoring__pb2.GetScoreRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scoring__pb2.GetScoreResponse.SerializeToString,
            ),
            'BatchScore': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchScore,
                    request_deserializer=evs_dot_v1_dot_scoring__pb2.BatchScoreRequest.FromString,
                    response_serializer=evs_dot_v1_dot_scoring__pb2.BatchScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.ScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.ScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScoreLead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.ScoringService/ScoreLead',
            evs_dot_v1_dot_scoring__pb2.ScoreLeadRequest.SerializeToString,
            evs_dot_v1_dot_scoring__pb2.ScoreLeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.ScoringService/GetScore',
            evs_dot_v1_dot_scoring__pb2.GetScoreRequest.SerializeToString,
            evs_dot_v1_dot_scoring__pb2.GetScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.ScoringService/BatchScore',
            evs_dot_v1_dot_scoring__pb2.BatchScoreRequest.SerializeToString,
            evs_dot_v1_dot_scoring__pb2.BatchScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
