# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import site_visit_pb2 as evs_dot_v1_dot_site__visit__pb2


class SiteVisitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleVisit = channel.unary_unary(
                '/evs.v1.SiteVisitService/ScheduleVisit',
                request_serializer=evs_dot_v1_dot_site__visit__pb2.ScheduleVisitRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_site__visit__pb2.ScheduleVisitResponse.FromString,
                _registered_method=True)
        self.RescheduleVisit = channel.unary_unary(
                '/evs.v1.SiteVisitService/RescheduleVisit',
                request_serializer=evs_dot_v1_dot_site__visit__pb2.RescheduleVisitRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_site__visit__pb2.RescheduleVisitResponse.FromString,
                _registered_method=True)
        self.CancelVisit = channel.unary_unary(
                '/evs.v1.SiteVisitService/CancelVisit',
                request_serializer=evs_dot_v1_dot_site__visit__pb2.CancelVisitRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_site__visit__pb2.CancelVisitResponse.FromString,
                _registered_method=True)
        self.CompleteVisit = channel.unary_unary(
                '/evs.v1.SiteVisitService/CompleteVisit',
                request_serializer=evs_dot_v1_dot_site__visit__pb2.CompleteVisitRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_site__visit__pb2.CompleteVisitResponse.FromString,
                _registered_method=True)
        self.ListVisits = channel.unary_unary(
                '/evs.v1.SiteVisitService/ListVisits',
                request_serializer=evs_dot_v1_dot_site__visit__pb2.ListVisitsRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_site__visit__pb2.ListVisitsResponse.FromString,
                _registered_method=True)


class SiteVisitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScheduleVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RescheduleVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteVisit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVisits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiteVisitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScheduleVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleVisit,
                    request_deserializer=evs_dot_v1_dot_site__visit__pb2.ScheduleVisitRequest.FromString,
                    response_serializer=evs_dot_v1_dot_site__visit__pb2.ScheduleVisitResponse.SerializeToString,
            ),
            'RescheduleVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.RescheduleVisit,
                    request_deserializer=evs_dot_v1_dot_site__visit__pb2.RescheduleVisitRequest.FromString,
                    response_serializer=evs_dot_v1_dot_site__visit__pb2.RescheduleVisitResponse.SerializeToString,
            ),
            'CancelVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelVisit,
                    request_deserializer=evs_dot_v1_dot_site__visit__pb2.CancelVisitRequest.FromString,
                    response_serializer=evs_dot_v1_dot_site__visit__pb2.CancelVisitResponse.SerializeToString,
            ),
            'CompleteVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteVisit,
                    request_deserializer=evs_dot_v1_dot_site__visit__pb2.CompleteVisitRequest.FromString,
                    response_serializer=evs_dot_v1_dot_site__visit__pb2.CompleteVisitResponse.SerializeToString,
            ),
            'ListVisits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVisits,
                    request_deserializer=evs_dot_v1_dot_site__visit__pb2.ListVisitsRequest.FromString,
                    response_serializer=evs_dot_v1_dot_site__visit__pb2.ListVisitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.SiteVisitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.SiteVisitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SiteVisitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScheduleVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SiteVisitService/ScheduleVisit',
            evs_dot_v1_dot_site__visit__pb2.ScheduleVisitRequest.SerializeToString,
            evs_dot_v1_dot_site__visit__pb2.ScheduleVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RescheduleVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SiteVisitService/RescheduleVisit',
            evs_dot_v1_dot_site__visit__pb2.RescheduleVisitRequest.SerializeToString,
            evs_dot_v1_dot_site__visit__pb2.RescheduleVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SiteVisitService/CancelVisit',
            evs_dot_v1_dot_site__visit__pb2.CancelVisitRequest.SerializeToString,
            evs_dot_v1_dot_site__visit__pb2.CancelVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SiteVisitService/CompleteVisit',
            evs_dot_v1_dot_site__visit__pb2.CompleteVisitRequest.SerializeToString,
            evs_dot_v1_dot_site__visit__pb2.CompleteVisitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVisits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SiteVisitService/ListVisits',
            evs_dot_v1_dot_site__visit__pb2.ListVisitsRequest.SerializeToString,
            evs_dot_v1_dot_site__visit__pb2.ListVisitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
