# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import stt_router_pb2 as evs_dot_v1_dot_stt__router__pb2


class SttRouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/evs.v1.SttRouterService/Transcribe',
                request_serializer=evs_dot_v1_dot_stt__router__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_stt__router__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.StreamTranscribe = channel.unary_stream(
                '/evs.v1.SttRouterService/StreamTranscribe',
                request_serializer=evs_dot_v1_dot_stt__router__pb2.StreamTranscribeRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_stt__router__pb2.StreamTranscribeResponse.FromString,
                _registered_method=True)


class SttRouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTranscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=evs_dot_v1_dot_stt__router__pb2.TranscribeRequest.FromString,
                    response_serializer=evs_dot_v1_dot_stt__router__pb2.TranscribeResponse.SerializeToString,
            ),
            'StreamTranscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=evs_dot_v1_dot_stt__router__pb2.StreamTranscribeRequest.FromString,
                    response_serializer=evs_dot_v1_dot_stt__router__pb2.StreamTranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.SttRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.SttRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SttRouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.SttRouterService/Transcribe',
            evs_dot_v1_dot_stt__router__pb2.TranscribeRequest.SerializeToString,
            evs_dot_v1_dot_stt__router__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTranscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/evs.v1.SttRouterService/StreamTranscribe',
            evs_dot_v1_dot_stt__router__pb2.StreamTranscribeRequest.SerializeToString,
            evs_dot_v1_dot_stt__router__pb2.StreamTranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
