# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import tts_router_pb2 as evs_dot_v1_dot_tts__router__pb2


class TtsRouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/evs.v1.TtsRouterService/Synthesize',
                request_serializer=evs_dot_v1_dot_tts__router__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_tts__router__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.StreamSynthesize = channel.unary_stream(
                '/evs.v1.TtsRouterService/StreamSynthesize',
                request_serializer=evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeResponse.FromString,
                _registered_method=True)


class TtsRouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSynthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=evs_dot_v1_dot_tts__router__pb2.SynthesizeRequest.FromString,
                    response_serializer=evs_dot_v1_dot_tts__router__pb2.SynthesizeResponse.SerializeToString,
            ),
            'StreamSynthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSynthesize,
                    request_deserializer=evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeRequest.FromString,
                    response_serializer=evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.TtsRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.TtsRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TtsRouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.TtsRouterService/Synthesize',
            evs_dot_v1_dot_tts__router__pb2.SynthesizeRequest.SerializeToString,
            evs_dot_v1_dot_tts__router__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSynthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/evs.v1.TtsRouterService/StreamSynthesize',
            evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeRequest.SerializeToString,
            evs_dot_v1_dot_tts__router__pb2.StreamSynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
