# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evs.v1 import whatsapp_pb2 as evs_dot_v1_dot_whatsapp__pb2


class WhatsAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/evs.v1.WhatsAppService/SendMessage',
                request_serializer=evs_dot_v1_dot_whatsapp__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_whatsapp__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendTemplate = channel.unary_unary(
                '/evs.v1.WhatsAppService/SendTemplate',
                request_serializer=evs_dot_v1_dot_whatsapp__pb2.SendTemplateRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_whatsapp__pb2.SendTemplateResponse.FromString,
                _registered_method=True)
        self.HandleInbound = channel.unary_unary(
                '/evs.v1.WhatsAppService/HandleInbound',
                request_serializer=evs_dot_v1_dot_whatsapp__pb2.HandleInboundRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_whatsapp__pb2.HandleInboundResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/evs.v1.WhatsAppService/ListMessages',
                request_serializer=evs_dot_v1_dot_whatsapp__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=evs_dot_v1_dot_whatsapp__pb2.ListMessagesResponse.FromString,
                _registered_method=True)


class WhatsAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleInbound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhatsAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=evs_dot_v1_dot_whatsapp__pb2.SendMessageRequest.FromString,
                    response_serializer=evs_dot_v1_dot_whatsapp__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTemplate,
                    request_deserializer=evs_dot_v1_dot_whatsapp__pb2.SendTemplateRequest.FromString,
                    response_serializer=evs_dot_v1_dot_whatsapp__pb2.SendTemplateResponse.SerializeToString,
            ),
            'HandleInbound': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleInbound,
                    request_deserializer=evs_dot_v1_dot_whatsapp__pb2.HandleInboundRequest.FromString,
                    response_serializer=evs_dot_v1_dot_whatsapp__pb2.HandleInboundResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=evs_dot_v1_dot_whatsapp__pb2.ListMessagesRequest.FromString,
                    response_serializer=evs_dot_v1_dot_whatsapp__pb2.ListMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evs.v1.WhatsAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evs.v1.WhatsAppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WhatsAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.WhatsAppService/SendMessage',
            evs_dot_v1_dot_whatsapp__pb2.SendMessageRequest.SerializeToString,
            evs_dot_v1_dot_whatsapp__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.WhatsAppService/SendTemplate',
            evs_dot_v1_dot_whatsapp__pb2.SendTemplateRequest.SerializeToString,
            evs_dot_v1_dot_whatsapp__pb2.SendTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleInbound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.WhatsAppService/HandleInbound',
            evs_dot_v1_dot_whatsapp__pb2.HandleInboundRequest.SerializeToString,
            evs_dot_v1_dot_whatsapp__pb2.HandleInboundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evs.v1.WhatsAppService/ListMessages',
            evs_dot_v1_dot_whatsapp__pb2.ListMessagesRequest.SerializeToString,
            evs_dot_v1_dot_whatsapp__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
