// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/lead_identity.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LeadIdentityServiceName is the fully-qualified name of the LeadIdentityService service.
	LeadIdentityServiceName = "evs.v1.LeadIdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LeadIdentityServiceUpsertContactProcedure is the fully-qualified name of the
	// LeadIdentityService's UpsertContact RPC.
	LeadIdentityServiceUpsertContactProcedure = "/evs.v1.LeadIdentityService/UpsertContact"
	// LeadIdentityServiceGetContactProcedure is the fully-qualified name of the LeadIdentityService's
	// GetContact RPC.
	LeadIdentityServiceGetContactProcedure = "/evs.v1.LeadIdentityService/GetContact"
	// LeadIdentityServiceUpsertLeadProcedure is the fully-qualified name of the LeadIdentityService's
	// UpsertLead RPC.
	LeadIdentityServiceUpsertLeadProcedure = "/evs.v1.LeadIdentityService/UpsertLead"
	// LeadIdentityServiceGetLeadProcedure is the fully-qualified name of the LeadIdentityService's
	// GetLead RPC.
	LeadIdentityServiceGetLeadProcedure = "/evs.v1.LeadIdentityService/GetLead"
	// LeadIdentityServiceListLeadsProcedure is the fully-qualified name of the LeadIdentityService's
	// ListLeads RPC.
	LeadIdentityServiceListLeadsProcedure = "/evs.v1.LeadIdentityService/ListLeads"
	// LeadIdentityServiceDedupeContactProcedure is the fully-qualified name of the
	// LeadIdentityService's DedupeContact RPC.
	LeadIdentityServiceDedupeContactProcedure = "/evs.v1.LeadIdentityService/DedupeContact"
)

// LeadIdentityServiceClient is a client for the evs.v1.LeadIdentityService service.
type LeadIdentityServiceClient interface {
	UpsertContact(context.Context, *connect.Request[v1.UpsertContactRequest]) (*connect.Response[v1.UpsertContactResponse], error)
	GetContact(context.Context, *connect.Request[v1.GetContactRequest]) (*connect.Response[v1.GetContactResponse], error)
	UpsertLead(context.Context, *connect.Request[v1.UpsertLeadRequest]) (*connect.Response[v1.UpsertLeadResponse], error)
	GetLead(context.Context, *connect.Request[v1.GetLeadRequest]) (*connect.Response[v1.GetLeadResponse], error)
	ListLeads(context.Context, *connect.Request[v1.ListLeadsRequest]) (*connect.Response[v1.ListLeadsResponse], error)
	DedupeContact(context.Context, *connect.Request[v1.DedupeContactRequest]) (*connect.Response[v1.DedupeContactResponse], error)
}

// NewLeadIdentityServiceClient constructs a client for the evs.v1.LeadIdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLeadIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LeadIdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	leadIdentityServiceMethods := v1.File_evs_v1_lead_identity_proto.Services().ByName("LeadIdentityService").Methods()
	return &leadIdentityServiceClient{
		upsertContact: connect.NewClient[v1.UpsertContactRequest, v1.UpsertContactResponse](
			httpClient,
			baseURL+LeadIdentityServiceUpsertContactProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("UpsertContact")),
			connect.WithClientOptions(opts...),
		),
		getContact: connect.NewClient[v1.GetContactRequest, v1.GetContactResponse](
			httpClient,
			baseURL+LeadIdentityServiceGetContactProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("GetContact")),
			connect.WithClientOptions(opts...),
		),
		upsertLead: connect.NewClient[v1.UpsertLeadRequest, v1.UpsertLeadResponse](
			httpClient,
			baseURL+LeadIdentityServiceUpsertLeadProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("UpsertLead")),
			connect.WithClientOptions(opts...),
		),
		getLead: connect.NewClient[v1.GetLeadRequest, v1.GetLeadResponse](
			httpClient,
			baseURL+LeadIdentityServiceGetLeadProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("GetLead")),
			connect.WithClientOptions(opts...),
		),
		listLeads: connect.NewClient[v1.ListLeadsRequest, v1.ListLeadsResponse](
			httpClient,
			baseURL+LeadIdentityServiceListLeadsProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("ListLeads")),
			connect.WithClientOptions(opts...),
		),
		dedupeContact: connect.NewClient[v1.DedupeContactRequest, v1.DedupeContactResponse](
			httpClient,
			baseURL+LeadIdentityServiceDedupeContactProcedure,
			connect.WithSchema(leadIdentityServiceMethods.ByName("DedupeContact")),
			connect.WithClientOptions(opts...),
		),
	}
}

// leadIdentityServiceClient implements LeadIdentityServiceClient.
type leadIdentityServiceClient struct {
	upsertContact *connect.Client[v1.UpsertContactRequest, v1.UpsertContactResponse]
	getContact    *connect.Client[v1.GetContactRequest, v1.GetContactResponse]
	upsertLead    *connect.Client[v1.UpsertLeadRequest, v1.UpsertLeadResponse]
	getLead       *connect.Client[v1.GetLeadRequest, v1.GetLeadResponse]
	listLeads     *connect.Client[v1.ListLeadsRequest, v1.ListLeadsResponse]
	dedupeContact *connect.Client[v1.DedupeContactRequest, v1.DedupeContactResponse]
}

// UpsertContact calls evs.v1.LeadIdentityService.UpsertContact.
func (c *leadIdentityServiceClient) UpsertContact(ctx context.Context, req *connect.Request[v1.UpsertContactRequest]) (*connect.Response[v1.UpsertContactResponse], error) {
	return c.upsertContact.CallUnary(ctx, req)
}

// GetContact calls evs.v1.LeadIdentityService.GetContact.
func (c *leadIdentityServiceClient) GetContact(ctx context.Context, req *connect.Request[v1.GetContactRequest]) (*connect.Response[v1.GetContactResponse], error) {
	return c.getContact.CallUnary(ctx, req)
}

// UpsertLead calls evs.v1.LeadIdentityService.UpsertLead.
func (c *leadIdentityServiceClient) UpsertLead(ctx context.Context, req *connect.Request[v1.UpsertLeadRequest]) (*connect.Response[v1.UpsertLeadResponse], error) {
	return c.upsertLead.CallUnary(ctx, req)
}

// GetLead calls evs.v1.LeadIdentityService.GetLead.
func (c *leadIdentityServiceClient) GetLead(ctx context.Context, req *connect.Request[v1.GetLeadRequest]) (*connect.Response[v1.GetLeadResponse], error) {
	return c.getLead.CallUnary(ctx, req)
}

// ListLeads calls evs.v1.LeadIdentityService.ListLeads.
func (c *leadIdentityServiceClient) ListLeads(ctx context.Context, req *connect.Request[v1.ListLeadsRequest]) (*connect.Response[v1.ListLeadsResponse], error) {
	return c.listLeads.CallUnary(ctx, req)
}

// DedupeContact calls evs.v1.LeadIdentityService.DedupeContact.
func (c *leadIdentityServiceClient) DedupeContact(ctx context.Context, req *connect.Request[v1.DedupeContactRequest]) (*connect.Response[v1.DedupeContactResponse], error) {
	return c.dedupeContact.CallUnary(ctx, req)
}

// LeadIdentityServiceHandler is an implementation of the evs.v1.LeadIdentityService service.
type LeadIdentityServiceHandler interface {
	UpsertContact(context.Context, *connect.Request[v1.UpsertContactRequest]) (*connect.Response[v1.UpsertContactResponse], error)
	GetContact(context.Context, *connect.Request[v1.GetContactRequest]) (*connect.Response[v1.GetContactResponse], error)
	UpsertLead(context.Context, *connect.Request[v1.UpsertLeadRequest]) (*connect.Response[v1.UpsertLeadResponse], error)
	GetLead(context.Context, *connect.Request[v1.GetLeadRequest]) (*connect.Response[v1.GetLeadResponse], error)
	ListLeads(context.Context, *connect.Request[v1.ListLeadsRequest]) (*connect.Response[v1.ListLeadsResponse], error)
	DedupeContact(context.Context, *connect.Request[v1.DedupeContactRequest]) (*connect.Response[v1.DedupeContactResponse], error)
}

// NewLeadIdentityServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLeadIdentityServiceHandler(svc LeadIdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	leadIdentityServiceMethods := v1.File_evs_v1_lead_identity_proto.Services().ByName("LeadIdentityService").Methods()
	leadIdentityServiceUpsertContactHandler := connect.NewUnaryHandler(
		LeadIdentityServiceUpsertContactProcedure,
		svc.UpsertContact,
		connect.WithSchema(leadIdentityServiceMethods.ByName("UpsertContact")),
		connect.WithHandlerOptions(opts...),
	)
	leadIdentityServiceGetContactHandler := connect.NewUnaryHandler(
		LeadIdentityServiceGetContactProcedure,
		svc.GetContact,
		connect.WithSchema(leadIdentityServiceMethods.ByName("GetContact")),
		connect.WithHandlerOptions(opts...),
	)
	leadIdentityServiceUpsertLeadHandler := connect.NewUnaryHandler(
		LeadIdentityServiceUpsertLeadProcedure,
		svc.UpsertLead,
		connect.WithSchema(leadIdentityServiceMethods.ByName("UpsertLead")),
		connect.WithHandlerOptions(opts...),
	)
	leadIdentityServiceGetLeadHandler := connect.NewUnaryHandler(
		LeadIdentityServiceGetLeadProcedure,
		svc.GetLead,
		connect.WithSchema(leadIdentityServiceMethods.ByName("GetLead")),
		connect.WithHandlerOptions(opts...),
	)
	leadIdentityServiceListLeadsHandler := connect.NewUnaryHandler(
		LeadIdentityServiceListLeadsProcedure,
		svc.ListLeads,
		connect.WithSchema(leadIdentityServiceMethods.ByName("ListLeads")),
		connect.WithHandlerOptions(opts...),
	)
	leadIdentityServiceDedupeContactHandler := connect.NewUnaryHandler(
		LeadIdentityServiceDedupeContactProcedure,
		svc.DedupeContact,
		connect.WithSchema(leadIdentityServiceMethods.ByName("DedupeContact")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.LeadIdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LeadIdentityServiceUpsertContactProcedure:
			leadIdentityServiceUpsertContactHandler.ServeHTTP(w, r)
		case LeadIdentityServiceGetContactProcedure:
			leadIdentityServiceGetContactHandler.ServeHTTP(w, r)
		case LeadIdentityServiceUpsertLeadProcedure:
			leadIdentityServiceUpsertLeadHandler.ServeHTTP(w, r)
		case LeadIdentityServiceGetLeadProcedure:
			leadIdentityServiceGetLeadHandler.ServeHTTP(w, r)
		case LeadIdentityServiceListLeadsProcedure:
			leadIdentityServiceListLeadsHandler.ServeHTTP(w, r)
		case LeadIdentityServiceDedupeContactProcedure:
			leadIdentityServiceDedupeContactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLeadIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLeadIdentityServiceHandler struct{}

func (UnimplementedLeadIdentityServiceHandler) UpsertContact(context.Context, *connect.Request[v1.UpsertContactRequest]) (*connect.Response[v1.UpsertContactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.UpsertContact is not implemented"))
}

func (UnimplementedLeadIdentityServiceHandler) GetContact(context.Context, *connect.Request[v1.GetContactRequest]) (*connect.Response[v1.GetContactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.GetContact is not implemented"))
}

func (UnimplementedLeadIdentityServiceHandler) UpsertLead(context.Context, *connect.Request[v1.UpsertLeadRequest]) (*connect.Response[v1.UpsertLeadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.UpsertLead is not implemented"))
}

func (UnimplementedLeadIdentityServiceHandler) GetLead(context.Context, *connect.Request[v1.GetLeadRequest]) (*connect.Response[v1.GetLeadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.GetLead is not implemented"))
}

func (UnimplementedLeadIdentityServiceHandler) ListLeads(context.Context, *connect.Request[v1.ListLeadsRequest]) (*connect.Response[v1.ListLeadsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.ListLeads is not implemented"))
}

func (UnimplementedLeadIdentityServiceHandler) DedupeContact(context.Context, *connect.Request[v1.DedupeContactRequest]) (*connect.Response[v1.DedupeContactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.LeadIdentityService.DedupeContact is not implemented"))
}
