// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/notification.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "evs.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceSendProcedure is the fully-qualified name of the NotificationService's Send
	// RPC.
	NotificationServiceSendProcedure = "/evs.v1.NotificationService/Send"
	// NotificationServiceGetStatusProcedure is the fully-qualified name of the NotificationService's
	// GetStatus RPC.
	NotificationServiceGetStatusProcedure = "/evs.v1.NotificationService/GetStatus"
	// NotificationServiceListNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListNotifications RPC.
	NotificationServiceListNotificationsProcedure = "/evs.v1.NotificationService/ListNotifications"
)

// NotificationServiceClient is a client for the evs.v1.NotificationService service.
type NotificationServiceClient interface {
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
}

// NewNotificationServiceClient constructs a client for the evs.v1.NotificationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_evs_v1_notification_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		send: connect.NewClient[v1.SendRequest, v1.SendResponse](
			httpClient,
			baseURL+NotificationServiceSendProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[v1.GetStatusRequest, v1.GetStatusResponse](
			httpClient,
			baseURL+NotificationServiceGetStatusProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		listNotifications: connect.NewClient[v1.ListNotificationsRequest, v1.ListNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	send              *connect.Client[v1.SendRequest, v1.SendResponse]
	getStatus         *connect.Client[v1.GetStatusRequest, v1.GetStatusResponse]
	listNotifications *connect.Client[v1.ListNotificationsRequest, v1.ListNotificationsResponse]
}

// Send calls evs.v1.NotificationService.Send.
func (c *notificationServiceClient) Send(ctx context.Context, req *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// GetStatus calls evs.v1.NotificationService.GetStatus.
func (c *notificationServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// ListNotifications calls evs.v1.NotificationService.ListNotifications.
func (c *notificationServiceClient) ListNotifications(ctx context.Context, req *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return c.listNotifications.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the evs.v1.NotificationService service.
type NotificationServiceHandler interface {
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_evs_v1_notification_proto.Services().ByName("NotificationService").Methods()
	notificationServiceSendHandler := connect.NewUnaryHandler(
		NotificationServiceSendProcedure,
		svc.Send,
		connect.WithSchema(notificationServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceGetStatusHandler := connect.NewUnaryHandler(
		NotificationServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(notificationServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListNotificationsProcedure,
		svc.ListNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceSendProcedure:
			notificationServiceSendHandler.ServeHTTP(w, r)
		case NotificationServiceGetStatusProcedure:
			notificationServiceGetStatusHandler.ServeHTTP(w, r)
		case NotificationServiceListNotificationsProcedure:
			notificationServiceListNotificationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.NotificationService.Send is not implemented"))
}

func (UnimplementedNotificationServiceHandler) GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.NotificationService.GetStatus is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.NotificationService.ListNotifications is not implemented"))
}
