// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/scheduler.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SchedulerServiceName is the fully-qualified name of the SchedulerService service.
	SchedulerServiceName = "evs.v1.SchedulerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SchedulerServiceScheduleJobProcedure is the fully-qualified name of the SchedulerService's
	// ScheduleJob RPC.
	SchedulerServiceScheduleJobProcedure = "/evs.v1.SchedulerService/ScheduleJob"
	// SchedulerServiceCancelJobProcedure is the fully-qualified name of the SchedulerService's
	// CancelJob RPC.
	SchedulerServiceCancelJobProcedure = "/evs.v1.SchedulerService/CancelJob"
	// SchedulerServiceListJobsProcedure is the fully-qualified name of the SchedulerService's ListJobs
	// RPC.
	SchedulerServiceListJobsProcedure = "/evs.v1.SchedulerService/ListJobs"
)

// SchedulerServiceClient is a client for the evs.v1.SchedulerService service.
type SchedulerServiceClient interface {
	ScheduleJob(context.Context, *connect.Request[v1.ScheduleJobRequest]) (*connect.Response[v1.ScheduleJobResponse], error)
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
}

// NewSchedulerServiceClient constructs a client for the evs.v1.SchedulerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSchedulerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SchedulerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	schedulerServiceMethods := v1.File_evs_v1_scheduler_proto.Services().ByName("SchedulerService").Methods()
	return &schedulerServiceClient{
		scheduleJob: connect.NewClient[v1.ScheduleJobRequest, v1.ScheduleJobResponse](
			httpClient,
			baseURL+SchedulerServiceScheduleJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ScheduleJob")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[v1.CancelJobRequest, v1.CancelJobResponse](
			httpClient,
			baseURL+SchedulerServiceCancelJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+SchedulerServiceListJobsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// schedulerServiceClient implements SchedulerServiceClient.
type schedulerServiceClient struct {
	scheduleJob *connect.Client[v1.ScheduleJobRequest, v1.ScheduleJobResponse]
	cancelJob   *connect.Client[v1.CancelJobRequest, v1.CancelJobResponse]
	listJobs    *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
}

// ScheduleJob calls evs.v1.SchedulerService.ScheduleJob.
func (c *schedulerServiceClient) ScheduleJob(ctx context.Context, req *connect.Request[v1.ScheduleJobRequest]) (*connect.Response[v1.ScheduleJobResponse], error) {
	return c.scheduleJob.CallUnary(ctx, req)
}

// CancelJob calls evs.v1.SchedulerService.CancelJob.
func (c *schedulerServiceClient) CancelJob(ctx context.Context, req *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// ListJobs calls evs.v1.SchedulerService.ListJobs.
func (c *schedulerServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// SchedulerServiceHandler is an implementation of the evs.v1.SchedulerService service.
type SchedulerServiceHandler interface {
	ScheduleJob(context.Context, *connect.Request[v1.ScheduleJobRequest]) (*connect.Response[v1.ScheduleJobResponse], error)
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
}

// NewSchedulerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSchedulerServiceHandler(svc SchedulerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	schedulerServiceMethods := v1.File_evs_v1_scheduler_proto.Services().ByName("SchedulerService").Methods()
	schedulerServiceScheduleJobHandler := connect.NewUnaryHandler(
		SchedulerServiceScheduleJobProcedure,
		svc.ScheduleJob,
		connect.WithSchema(schedulerServiceMethods.ByName("ScheduleJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceCancelJobHandler := connect.NewUnaryHandler(
		SchedulerServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(schedulerServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceListJobsHandler := connect.NewUnaryHandler(
		SchedulerServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.SchedulerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SchedulerServiceScheduleJobProcedure:
			schedulerServiceScheduleJobHandler.ServeHTTP(w, r)
		case SchedulerServiceCancelJobProcedure:
			schedulerServiceCancelJobHandler.ServeHTTP(w, r)
		case SchedulerServiceListJobsProcedure:
			schedulerServiceListJobsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSchedulerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSchedulerServiceHandler struct{}

func (UnimplementedSchedulerServiceHandler) ScheduleJob(context.Context, *connect.Request[v1.ScheduleJobRequest]) (*connect.Response[v1.ScheduleJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SchedulerService.ScheduleJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SchedulerService.CancelJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SchedulerService.ListJobs is not implemented"))
}
