// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/site_visit.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SiteVisitServiceName is the fully-qualified name of the SiteVisitService service.
	SiteVisitServiceName = "evs.v1.SiteVisitService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SiteVisitServiceScheduleVisitProcedure is the fully-qualified name of the SiteVisitService's
	// ScheduleVisit RPC.
	SiteVisitServiceScheduleVisitProcedure = "/evs.v1.SiteVisitService/ScheduleVisit"
	// SiteVisitServiceRescheduleVisitProcedure is the fully-qualified name of the SiteVisitService's
	// RescheduleVisit RPC.
	SiteVisitServiceRescheduleVisitProcedure = "/evs.v1.SiteVisitService/RescheduleVisit"
	// SiteVisitServiceCancelVisitProcedure is the fully-qualified name of the SiteVisitService's
	// CancelVisit RPC.
	SiteVisitServiceCancelVisitProcedure = "/evs.v1.SiteVisitService/CancelVisit"
	// SiteVisitServiceCompleteVisitProcedure is the fully-qualified name of the SiteVisitService's
	// CompleteVisit RPC.
	SiteVisitServiceCompleteVisitProcedure = "/evs.v1.SiteVisitService/CompleteVisit"
	// SiteVisitServiceListVisitsProcedure is the fully-qualified name of the SiteVisitService's
	// ListVisits RPC.
	SiteVisitServiceListVisitsProcedure = "/evs.v1.SiteVisitService/ListVisits"
)

// SiteVisitServiceClient is a client for the evs.v1.SiteVisitService service.
type SiteVisitServiceClient interface {
	ScheduleVisit(context.Context, *connect.Request[v1.ScheduleVisitRequest]) (*connect.Response[v1.ScheduleVisitResponse], error)
	RescheduleVisit(context.Context, *connect.Request[v1.RescheduleVisitRequest]) (*connect.Response[v1.RescheduleVisitResponse], error)
	CancelVisit(context.Context, *connect.Request[v1.CancelVisitRequest]) (*connect.Response[v1.CancelVisitResponse], error)
	CompleteVisit(context.Context, *connect.Request[v1.CompleteVisitRequest]) (*connect.Response[v1.CompleteVisitResponse], error)
	ListVisits(context.Context, *connect.Request[v1.ListVisitsRequest]) (*connect.Response[v1.ListVisitsResponse], error)
}

// NewSiteVisitServiceClient constructs a client for the evs.v1.SiteVisitService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSiteVisitServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SiteVisitServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	siteVisitServiceMethods := v1.File_evs_v1_site_visit_proto.Services().ByName("SiteVisitService").Methods()
	return &siteVisitServiceClient{
		scheduleVisit: connect.NewClient[v1.ScheduleVisitRequest, v1.ScheduleVisitResponse](
			httpClient,
			baseURL+SiteVisitServiceScheduleVisitProcedure,
			connect.WithSchema(siteVisitServiceMethods.ByName("ScheduleVisit")),
			connect.WithClientOptions(opts...),
		),
		rescheduleVisit: connect.NewClient[v1.RescheduleVisitRequest, v1.RescheduleVisitResponse](
			httpClient,
			baseURL+SiteVisitServiceRescheduleVisitProcedure,
			connect.WithSchema(siteVisitServiceMethods.ByName("RescheduleVisit")),
			connect.WithClientOptions(opts...),
		),
		cancelVisit: connect.NewClient[v1.CancelVisitRequest, v1.CancelVisitResponse](
			httpClient,
			baseURL+SiteVisitServiceCancelVisitProcedure,
			connect.WithSchema(siteVisitServiceMethods.ByName("CancelVisit")),
			connect.WithClientOptions(opts...),
		),
		completeVisit: connect.NewClient[v1.CompleteVisitRequest, v1.CompleteVisitResponse](
			httpClient,
			baseURL+SiteVisitServiceCompleteVisitProcedure,
			connect.WithSchema(siteVisitServiceMethods.ByName("CompleteVisit")),
			connect.WithClientOptions(opts...),
		),
		listVisits: connect.NewClient[v1.ListVisitsRequest, v1.ListVisitsResponse](
			httpClient,
			baseURL+SiteVisitServiceListVisitsProcedure,
			connect.WithSchema(siteVisitServiceMethods.ByName("ListVisits")),
			connect.WithClientOptions(opts...),
		),
	}
}

// siteVisitServiceClient implements SiteVisitServiceClient.
type siteVisitServiceClient struct {
	scheduleVisit   *connect.Client[v1.ScheduleVisitRequest, v1.ScheduleVisitResponse]
	rescheduleVisit *connect.Client[v1.RescheduleVisitRequest, v1.RescheduleVisitResponse]
	cancelVisit     *connect.Client[v1.CancelVisitRequest, v1.CancelVisitResponse]
	completeVisit   *connect.Client[v1.CompleteVisitRequest, v1.CompleteVisitResponse]
	listVisits      *connect.Client[v1.ListVisitsRequest, v1.ListVisitsResponse]
}

// ScheduleVisit calls evs.v1.SiteVisitService.ScheduleVisit.
func (c *siteVisitServiceClient) ScheduleVisit(ctx context.Context, req *connect.Request[v1.ScheduleVisitRequest]) (*connect.Response[v1.ScheduleVisitResponse], error) {
	return c.scheduleVisit.CallUnary(ctx, req)
}

// RescheduleVisit calls evs.v1.SiteVisitService.RescheduleVisit.
func (c *siteVisitServiceClient) RescheduleVisit(ctx context.Context, req *connect.Request[v1.RescheduleVisitRequest]) (*connect.Response[v1.RescheduleVisitResponse], error) {
	return c.rescheduleVisit.CallUnary(ctx, req)
}

// CancelVisit calls evs.v1.SiteVisitService.CancelVisit.
func (c *siteVisitServiceClient) CancelVisit(ctx context.Context, req *connect.Request[v1.CancelVisitRequest]) (*connect.Response[v1.CancelVisitResponse], error) {
	return c.cancelVisit.CallUnary(ctx, req)
}

// CompleteVisit calls evs.v1.SiteVisitService.CompleteVisit.
func (c *siteVisitServiceClient) CompleteVisit(ctx context.Context, req *connect.Request[v1.CompleteVisitRequest]) (*connect.Response[v1.CompleteVisitResponse], error) {
	return c.completeVisit.CallUnary(ctx, req)
}

// ListVisits calls evs.v1.SiteVisitService.ListVisits.
func (c *siteVisitServiceClient) ListVisits(ctx context.Context, req *connect.Request[v1.ListVisitsRequest]) (*connect.Response[v1.ListVisitsResponse], error) {
	return c.listVisits.CallUnary(ctx, req)
}

// SiteVisitServiceHandler is an implementation of the evs.v1.SiteVisitService service.
type SiteVisitServiceHandler interface {
	ScheduleVisit(context.Context, *connect.Request[v1.ScheduleVisitRequest]) (*connect.Response[v1.ScheduleVisitResponse], error)
	RescheduleVisit(context.Context, *connect.Request[v1.RescheduleVisitRequest]) (*connect.Response[v1.RescheduleVisitResponse], error)
	CancelVisit(context.Context, *connect.Request[v1.CancelVisitRequest]) (*connect.Response[v1.CancelVisitResponse], error)
	CompleteVisit(context.Context, *connect.Request[v1.CompleteVisitRequest]) (*connect.Response[v1.CompleteVisitResponse], error)
	ListVisits(context.Context, *connect.Request[v1.ListVisitsRequest]) (*connect.Response[v1.ListVisitsResponse], error)
}

// NewSiteVisitServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSiteVisitServiceHandler(svc SiteVisitServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	siteVisitServiceMethods := v1.File_evs_v1_site_visit_proto.Services().ByName("SiteVisitService").Methods()
	siteVisitServiceScheduleVisitHandler := connect.NewUnaryHandler(
		SiteVisitServiceScheduleVisitProcedure,
		svc.ScheduleVisit,
		connect.WithSchema(siteVisitServiceMethods.ByName("ScheduleVisit")),
		connect.WithHandlerOptions(opts...),
	)
	siteVisitServiceRescheduleVisitHandler := connect.NewUnaryHandler(
		SiteVisitServiceRescheduleVisitProcedure,
		svc.RescheduleVisit,
		connect.WithSchema(siteVisitServiceMethods.ByName("RescheduleVisit")),
		connect.WithHandlerOptions(opts...),
	)
	siteVisitServiceCancelVisitHandler := connect.NewUnaryHandler(
		SiteVisitServiceCancelVisitProcedure,
		svc.CancelVisit,
		connect.WithSchema(siteVisitServiceMethods.ByName("CancelVisit")),
		connect.WithHandlerOptions(opts...),
	)
	siteVisitServiceCompleteVisitHandler := connect.NewUnaryHandler(
		SiteVisitServiceCompleteVisitProcedure,
		svc.CompleteVisit,
		connect.WithSchema(siteVisitServiceMethods.ByName("CompleteVisit")),
		connect.WithHandlerOptions(opts...),
	)
	siteVisitServiceListVisitsHandler := connect.NewUnaryHandler(
		SiteVisitServiceListVisitsProcedure,
		svc.ListVisits,
		connect.WithSchema(siteVisitServiceMethods.ByName("ListVisits")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.SiteVisitService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SiteVisitServiceScheduleVisitProcedure:
			siteVisitServiceScheduleVisitHandler.ServeHTTP(w, r)
		case SiteVisitServiceRescheduleVisitProcedure:
			siteVisitServiceRescheduleVisitHandler.ServeHTTP(w, r)
		case SiteVisitServiceCancelVisitProcedure:
			siteVisitServiceCancelVisitHandler.ServeHTTP(w, r)
		case SiteVisitServiceCompleteVisitProcedure:
			siteVisitServiceCompleteVisitHandler.ServeHTTP(w, r)
		case SiteVisitServiceListVisitsProcedure:
			siteVisitServiceListVisitsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSiteVisitServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSiteVisitServiceHandler struct{}

func (UnimplementedSiteVisitServiceHandler) ScheduleVisit(context.Context, *connect.Request[v1.ScheduleVisitRequest]) (*connect.Response[v1.ScheduleVisitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SiteVisitService.ScheduleVisit is not implemented"))
}

func (UnimplementedSiteVisitServiceHandler) RescheduleVisit(context.Context, *connect.Request[v1.RescheduleVisitRequest]) (*connect.Response[v1.RescheduleVisitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SiteVisitService.RescheduleVisit is not implemented"))
}

func (UnimplementedSiteVisitServiceHandler) CancelVisit(context.Context, *connect.Request[v1.CancelVisitRequest]) (*connect.Response[v1.CancelVisitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SiteVisitService.CancelVisit is not implemented"))
}

func (UnimplementedSiteVisitServiceHandler) CompleteVisit(context.Context, *connect.Request[v1.CompleteVisitRequest]) (*connect.Response[v1.CompleteVisitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SiteVisitService.CompleteVisit is not implemented"))
}

func (UnimplementedSiteVisitServiceHandler) ListVisits(context.Context, *connect.Request[v1.ListVisitsRequest]) (*connect.Response[v1.ListVisitsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SiteVisitService.ListVisits is not implemented"))
}
