// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/stt_router.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SttRouterServiceName is the fully-qualified name of the SttRouterService service.
	SttRouterServiceName = "evs.v1.SttRouterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SttRouterServiceTranscribeProcedure is the fully-qualified name of the SttRouterService's
	// Transcribe RPC.
	SttRouterServiceTranscribeProcedure = "/evs.v1.SttRouterService/Transcribe"
	// SttRouterServiceStreamTranscribeProcedure is the fully-qualified name of the SttRouterService's
	// StreamTranscribe RPC.
	SttRouterServiceStreamTranscribeProcedure = "/evs.v1.SttRouterService/StreamTranscribe"
)

// SttRouterServiceClient is a client for the evs.v1.SttRouterService service.
type SttRouterServiceClient interface {
	Transcribe(context.Context, *connect.Request[v1.TranscribeRequest]) (*connect.Response[v1.TranscribeResponse], error)
	StreamTranscribe(context.Context, *connect.Request[v1.StreamTranscribeRequest]) (*connect.ServerStreamForClient[v1.StreamTranscribeResponse], error)
}

// NewSttRouterServiceClient constructs a client for the evs.v1.SttRouterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSttRouterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SttRouterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sttRouterServiceMethods := v1.File_evs_v1_stt_router_proto.Services().ByName("SttRouterService").Methods()
	return &sttRouterServiceClient{
		transcribe: connect.NewClient[v1.TranscribeRequest, v1.TranscribeResponse](
			httpClient,
			baseURL+SttRouterServiceTranscribeProcedure,
			connect.WithSchema(sttRouterServiceMethods.ByName("Transcribe")),
			connect.WithClientOptions(opts...),
		),
		streamTranscribe: connect.NewClient[v1.StreamTranscribeRequest, v1.StreamTranscribeResponse](
			httpClient,
			baseURL+SttRouterServiceStreamTranscribeProcedure,
			connect.WithSchema(sttRouterServiceMethods.ByName("StreamTranscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sttRouterServiceClient implements SttRouterServiceClient.
type sttRouterServiceClient struct {
	transcribe       *connect.Client[v1.TranscribeRequest, v1.TranscribeResponse]
	streamTranscribe *connect.Client[v1.StreamTranscribeRequest, v1.StreamTranscribeResponse]
}

// Transcribe calls evs.v1.SttRouterService.Transcribe.
func (c *sttRouterServiceClient) Transcribe(ctx context.Context, req *connect.Request[v1.TranscribeRequest]) (*connect.Response[v1.TranscribeResponse], error) {
	return c.transcribe.CallUnary(ctx, req)
}

// StreamTranscribe calls evs.v1.SttRouterService.StreamTranscribe.
func (c *sttRouterServiceClient) StreamTranscribe(ctx context.Context, req *connect.Request[v1.StreamTranscribeRequest]) (*connect.ServerStreamForClient[v1.StreamTranscribeResponse], error) {
	return c.streamTranscribe.CallServerStream(ctx, req)
}

// SttRouterServiceHandler is an implementation of the evs.v1.SttRouterService service.
type SttRouterServiceHandler interface {
	Transcribe(context.Context, *connect.Request[v1.TranscribeRequest]) (*connect.Response[v1.TranscribeResponse], error)
	StreamTranscribe(context.Context, *connect.Request[v1.StreamTranscribeRequest], *connect.ServerStream[v1.StreamTranscribeResponse]) error
}

// NewSttRouterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSttRouterServiceHandler(svc SttRouterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sttRouterServiceMethods := v1.File_evs_v1_stt_router_proto.Services().ByName("SttRouterService").Methods()
	sttRouterServiceTranscribeHandler := connect.NewUnaryHandler(
		SttRouterServiceTranscribeProcedure,
		svc.Transcribe,
		connect.WithSchema(sttRouterServiceMethods.ByName("Transcribe")),
		connect.WithHandlerOptions(opts...),
	)
	sttRouterServiceStreamTranscribeHandler := connect.NewServerStreamHandler(
		SttRouterServiceStreamTranscribeProcedure,
		svc.StreamTranscribe,
		connect.WithSchema(sttRouterServiceMethods.ByName("StreamTranscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.SttRouterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SttRouterServiceTranscribeProcedure:
			sttRouterServiceTranscribeHandler.ServeHTTP(w, r)
		case SttRouterServiceStreamTranscribeProcedure:
			sttRouterServiceStreamTranscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSttRouterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSttRouterServiceHandler struct{}

func (UnimplementedSttRouterServiceHandler) Transcribe(context.Context, *connect.Request[v1.TranscribeRequest]) (*connect.Response[v1.TranscribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SttRouterService.Transcribe is not implemented"))
}

func (UnimplementedSttRouterServiceHandler) StreamTranscribe(context.Context, *connect.Request[v1.StreamTranscribeRequest], *connect.ServerStream[v1.StreamTranscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.SttRouterService.StreamTranscribe is not implemented"))
}
