// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/telephony.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelephonyServiceName is the fully-qualified name of the TelephonyService service.
	TelephonyServiceName = "evs.v1.TelephonyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelephonyServicePlaceCallProcedure is the fully-qualified name of the TelephonyService's
	// PlaceCall RPC.
	TelephonyServicePlaceCallProcedure = "/evs.v1.TelephonyService/PlaceCall"
	// TelephonyServiceHangupCallProcedure is the fully-qualified name of the TelephonyService's
	// HangupCall RPC.
	TelephonyServiceHangupCallProcedure = "/evs.v1.TelephonyService/HangupCall"
	// TelephonyServiceGetCallProcedure is the fully-qualified name of the TelephonyService's GetCall
	// RPC.
	TelephonyServiceGetCallProcedure = "/evs.v1.TelephonyService/GetCall"
	// TelephonyServiceListCallsProcedure is the fully-qualified name of the TelephonyService's
	// ListCalls RPC.
	TelephonyServiceListCallsProcedure = "/evs.v1.TelephonyService/ListCalls"
	// TelephonyServiceHandleProviderWebhookProcedure is the fully-qualified name of the
	// TelephonyService's HandleProviderWebhook RPC.
	TelephonyServiceHandleProviderWebhookProcedure = "/evs.v1.TelephonyService/HandleProviderWebhook"
)

// TelephonyServiceClient is a client for the evs.v1.TelephonyService service.
type TelephonyServiceClient interface {
	PlaceCall(context.Context, *connect.Request[v1.PlaceCallRequest]) (*connect.Response[v1.PlaceCallResponse], error)
	HangupCall(context.Context, *connect.Request[v1.HangupCallRequest]) (*connect.Response[v1.HangupCallResponse], error)
	GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error)
	ListCalls(context.Context, *connect.Request[v1.ListCallsRequest]) (*connect.Response[v1.ListCallsResponse], error)
	HandleProviderWebhook(context.Context, *connect.Request[v1.HandleProviderWebhookRequest]) (*connect.Response[v1.HandleProviderWebhookResponse], error)
}

// NewTelephonyServiceClient constructs a client for the evs.v1.TelephonyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelephonyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelephonyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telephonyServiceMethods := v1.File_evs_v1_telephony_proto.Services().ByName("TelephonyService").Methods()
	return &telephonyServiceClient{
		placeCall: connect.NewClient[v1.PlaceCallRequest, v1.PlaceCallResponse](
			httpClient,
			baseURL+TelephonyServicePlaceCallProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("PlaceCall")),
			connect.WithClientOptions(opts...),
		),
		hangupCall: connect.NewClient[v1.HangupCallRequest, v1.HangupCallResponse](
			httpClient,
			baseURL+TelephonyServiceHangupCallProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("HangupCall")),
			connect.WithClientOptions(opts...),
		),
		getCall: connect.NewClient[v1.GetCallRequest, v1.GetCallResponse](
			httpClient,
			baseURL+TelephonyServiceGetCallProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("GetCall")),
			connect.WithClientOptions(opts...),
		),
		listCalls: connect.NewClient[v1.ListCallsRequest, v1.ListCallsResponse](
			httpClient,
			baseURL+TelephonyServiceListCallsProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("ListCalls")),
			connect.WithClientOptions(opts...),
		),
		handleProviderWebhook: connect.NewClient[v1.HandleProviderWebhookRequest, v1.HandleProviderWebhookResponse](
			httpClient,
			baseURL+TelephonyServiceHandleProviderWebhookProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("HandleProviderWebhook")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telephonyServiceClient implements TelephonyServiceClient.
type telephonyServiceClient struct {
	placeCall             *connect.Client[v1.PlaceCallRequest, v1.PlaceCallResponse]
	hangupCall            *connect.Client[v1.HangupCallRequest, v1.HangupCallResponse]
	getCall               *connect.Client[v1.GetCallRequest, v1.GetCallResponse]
	listCalls             *connect.Client[v1.ListCallsRequest, v1.ListCallsResponse]
	handleProviderWebhook *connect.Client[v1.HandleProviderWebhookRequest, v1.HandleProviderWebhookResponse]
}

// PlaceCall calls evs.v1.TelephonyService.PlaceCall.
func (c *telephonyServiceClient) PlaceCall(ctx context.Context, req *connect.Request[v1.PlaceCallRequest]) (*connect.Response[v1.PlaceCallResponse], error) {
	return c.placeCall.CallUnary(ctx, req)
}

// HangupCall calls evs.v1.TelephonyService.HangupCall.
func (c *telephonyServiceClient) HangupCall(ctx context.Context, req *connect.Request[v1.HangupCallRequest]) (*connect.Response[v1.HangupCallResponse], error) {
	return c.hangupCall.CallUnary(ctx, req)
}

// GetCall calls evs.v1.TelephonyService.GetCall.
func (c *telephonyServiceClient) GetCall(ctx context.Context, req *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error) {
	return c.getCall.CallUnary(ctx, req)
}

// ListCalls calls evs.v1.TelephonyService.ListCalls.
func (c *telephonyServiceClient) ListCalls(ctx context.Context, req *connect.Request[v1.ListCallsRequest]) (*connect.Response[v1.ListCallsResponse], error) {
	return c.listCalls.CallUnary(ctx, req)
}

// HandleProviderWebhook calls evs.v1.TelephonyService.HandleProviderWebhook.
func (c *telephonyServiceClient) HandleProviderWebhook(ctx context.Context, req *connect.Request[v1.HandleProviderWebhookRequest]) (*connect.Response[v1.HandleProviderWebhookResponse], error) {
	return c.handleProviderWebhook.CallUnary(ctx, req)
}

// TelephonyServiceHandler is an implementation of the evs.v1.TelephonyService service.
type TelephonyServiceHandler interface {
	PlaceCall(context.Context, *connect.Request[v1.PlaceCallRequest]) (*connect.Response[v1.PlaceCallResponse], error)
	HangupCall(context.Context, *connect.Request[v1.HangupCallRequest]) (*connect.Response[v1.HangupCallResponse], error)
	GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error)
	ListCalls(context.Context, *connect.Request[v1.ListCallsRequest]) (*connect.Response[v1.ListCallsResponse], error)
	HandleProviderWebhook(context.Context, *connect.Request[v1.HandleProviderWebhookRequest]) (*connect.Response[v1.HandleProviderWebhookResponse], error)
}

// NewTelephonyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelephonyServiceHandler(svc TelephonyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telephonyServiceMethods := v1.File_evs_v1_telephony_proto.Services().ByName("TelephonyService").Methods()
	telephonyServicePlaceCallHandler := connect.NewUnaryHandler(
		TelephonyServicePlaceCallProcedure,
		svc.PlaceCall,
		connect.WithSchema(telephonyServiceMethods.ByName("PlaceCall")),
		connect.WithHandlerOptions(opts...),
	)
	telephonyServiceHangupCallHandler := connect.NewUnaryHandler(
		TelephonyServiceHangupCallProcedure,
		svc.HangupCall,
		connect.WithSchema(telephonyServiceMethods.ByName("HangupCall")),
		connect.WithHandlerOptions(opts...),
	)
	telephonyServiceGetCallHandler := connect.NewUnaryHandler(
		TelephonyServiceGetCallProcedure,
		svc.GetCall,
		connect.WithSchema(telephonyServiceMethods.ByName("GetCall")),
		connect.WithHandlerOptions(opts...),
	)
	telephonyServiceListCallsHandler := connect.NewUnaryHandler(
		TelephonyServiceListCallsProcedure,
		svc.ListCalls,
		connect.WithSchema(telephonyServiceMethods.ByName("ListCalls")),
		connect.WithHandlerOptions(opts...),
	)
	telephonyServiceHandleProviderWebhookHandler := connect.NewUnaryHandler(
		TelephonyServiceHandleProviderWebhookProcedure,
		svc.HandleProviderWebhook,
		connect.WithSchema(telephonyServiceMethods.ByName("HandleProviderWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.TelephonyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelephonyServicePlaceCallProcedure:
			telephonyServicePlaceCallHandler.ServeHTTP(w, r)
		case TelephonyServiceHangupCallProcedure:
			telephonyServiceHangupCallHandler.ServeHTTP(w, r)
		case TelephonyServiceGetCallProcedure:
			telephonyServiceGetCallHandler.ServeHTTP(w, r)
		case TelephonyServiceListCallsProcedure:
			telephonyServiceListCallsHandler.ServeHTTP(w, r)
		case TelephonyServiceHandleProviderWebhookProcedure:
			telephonyServiceHandleProviderWebhookHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelephonyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelephonyServiceHandler struct{}

func (UnimplementedTelephonyServiceHandler) PlaceCall(context.Context, *connect.Request[v1.PlaceCallRequest]) (*connect.Response[v1.PlaceCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TelephonyService.PlaceCall is not implemented"))
}

func (UnimplementedTelephonyServiceHandler) HangupCall(context.Context, *connect.Request[v1.HangupCallRequest]) (*connect.Response[v1.HangupCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TelephonyService.HangupCall is not implemented"))
}

func (UnimplementedTelephonyServiceHandler) GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TelephonyService.GetCall is not implemented"))
}

func (UnimplementedTelephonyServiceHandler) ListCalls(context.Context, *connect.Request[v1.ListCallsRequest]) (*connect.Response[v1.ListCallsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TelephonyService.ListCalls is not implemented"))
}

func (UnimplementedTelephonyServiceHandler) HandleProviderWebhook(context.Context, *connect.Request[v1.HandleProviderWebhookRequest]) (*connect.Response[v1.HandleProviderWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TelephonyService.HandleProviderWebhook is not implemented"))
}
