// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/tts_router.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TtsRouterServiceName is the fully-qualified name of the TtsRouterService service.
	TtsRouterServiceName = "evs.v1.TtsRouterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TtsRouterServiceSynthesizeProcedure is the fully-qualified name of the TtsRouterService's
	// Synthesize RPC.
	TtsRouterServiceSynthesizeProcedure = "/evs.v1.TtsRouterService/Synthesize"
	// TtsRouterServiceStreamSynthesizeProcedure is the fully-qualified name of the TtsRouterService's
	// StreamSynthesize RPC.
	TtsRouterServiceStreamSynthesizeProcedure = "/evs.v1.TtsRouterService/StreamSynthesize"
)

// TtsRouterServiceClient is a client for the evs.v1.TtsRouterService service.
type TtsRouterServiceClient interface {
	Synthesize(context.Context, *connect.Request[v1.SynthesizeRequest]) (*connect.Response[v1.SynthesizeResponse], error)
	StreamSynthesize(context.Context, *connect.Request[v1.StreamSynthesizeRequest]) (*connect.ServerStreamForClient[v1.StreamSynthesizeResponse], error)
}

// NewTtsRouterServiceClient constructs a client for the evs.v1.TtsRouterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTtsRouterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TtsRouterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ttsRouterServiceMethods := v1.File_evs_v1_tts_router_proto.Services().ByName("TtsRouterService").Methods()
	return &ttsRouterServiceClient{
		synthesize: connect.NewClient[v1.SynthesizeRequest, v1.SynthesizeResponse](
			httpClient,
			baseURL+TtsRouterServiceSynthesizeProcedure,
			connect.WithSchema(ttsRouterServiceMethods.ByName("Synthesize")),
			connect.WithClientOptions(opts...),
		),
		streamSynthesize: connect.NewClient[v1.StreamSynthesizeRequest, v1.StreamSynthesizeResponse](
			httpClient,
			baseURL+TtsRouterServiceStreamSynthesizeProcedure,
			connect.WithSchema(ttsRouterServiceMethods.ByName("StreamSynthesize")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ttsRouterServiceClient implements TtsRouterServiceClient.
type ttsRouterServiceClient struct {
	synthesize       *connect.Client[v1.SynthesizeRequest, v1.SynthesizeResponse]
	streamSynthesize *connect.Client[v1.StreamSynthesizeRequest, v1.StreamSynthesizeResponse]
}

// Synthesize calls evs.v1.TtsRouterService.Synthesize.
func (c *ttsRouterServiceClient) Synthesize(ctx context.Context, req *connect.Request[v1.SynthesizeRequest]) (*connect.Response[v1.SynthesizeResponse], error) {
	return c.synthesize.CallUnary(ctx, req)
}

// StreamSynthesize calls evs.v1.TtsRouterService.StreamSynthesize.
func (c *ttsRouterServiceClient) StreamSynthesize(ctx context.Context, req *connect.Request[v1.StreamSynthesizeRequest]) (*connect.ServerStreamForClient[v1.StreamSynthesizeResponse], error) {
	return c.streamSynthesize.CallServerStream(ctx, req)
}

// TtsRouterServiceHandler is an implementation of the evs.v1.TtsRouterService service.
type TtsRouterServiceHandler interface {
	Synthesize(context.Context, *connect.Request[v1.SynthesizeRequest]) (*connect.Response[v1.SynthesizeResponse], error)
	StreamSynthesize(context.Context, *connect.Request[v1.StreamSynthesizeRequest], *connect.ServerStream[v1.StreamSynthesizeResponse]) error
}

// NewTtsRouterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTtsRouterServiceHandler(svc TtsRouterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ttsRouterServiceMethods := v1.File_evs_v1_tts_router_proto.Services().ByName("TtsRouterService").Methods()
	ttsRouterServiceSynthesizeHandler := connect.NewUnaryHandler(
		TtsRouterServiceSynthesizeProcedure,
		svc.Synthesize,
		connect.WithSchema(ttsRouterServiceMethods.ByName("Synthesize")),
		connect.WithHandlerOptions(opts...),
	)
	ttsRouterServiceStreamSynthesizeHandler := connect.NewServerStreamHandler(
		TtsRouterServiceStreamSynthesizeProcedure,
		svc.StreamSynthesize,
		connect.WithSchema(ttsRouterServiceMethods.ByName("StreamSynthesize")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.TtsRouterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TtsRouterServiceSynthesizeProcedure:
			ttsRouterServiceSynthesizeHandler.ServeHTTP(w, r)
		case TtsRouterServiceStreamSynthesizeProcedure:
			ttsRouterServiceStreamSynthesizeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTtsRouterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTtsRouterServiceHandler struct{}

func (UnimplementedTtsRouterServiceHandler) Synthesize(context.Context, *connect.Request[v1.SynthesizeRequest]) (*connect.Response[v1.SynthesizeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TtsRouterService.Synthesize is not implemented"))
}

func (UnimplementedTtsRouterServiceHandler) StreamSynthesize(context.Context, *connect.Request[v1.StreamSynthesizeRequest], *connect.ServerStream[v1.StreamSynthesizeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.TtsRouterService.StreamSynthesize is not implemented"))
}
