// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: evs/v1/whatsapp.proto

package evsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lead/libs/go/pb/evs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WhatsAppServiceName is the fully-qualified name of the WhatsAppService service.
	WhatsAppServiceName = "evs.v1.WhatsAppService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WhatsAppServiceSendMessageProcedure is the fully-qualified name of the WhatsAppService's
	// SendMessage RPC.
	WhatsAppServiceSendMessageProcedure = "/evs.v1.WhatsAppService/SendMessage"
	// WhatsAppServiceSendTemplateProcedure is the fully-qualified name of the WhatsAppService's
	// SendTemplate RPC.
	WhatsAppServiceSendTemplateProcedure = "/evs.v1.WhatsAppService/SendTemplate"
	// WhatsAppServiceHandleInboundProcedure is the fully-qualified name of the WhatsAppService's
	// HandleInbound RPC.
	WhatsAppServiceHandleInboundProcedure = "/evs.v1.WhatsAppService/HandleInbound"
	// WhatsAppServiceListMessagesProcedure is the fully-qualified name of the WhatsAppService's
	// ListMessages RPC.
	WhatsAppServiceListMessagesProcedure = "/evs.v1.WhatsAppService/ListMessages"
)

// WhatsAppServiceClient is a client for the evs.v1.WhatsAppService service.
type WhatsAppServiceClient interface {
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	SendTemplate(context.Context, *connect.Request[v1.SendTemplateRequest]) (*connect.Response[v1.SendTemplateResponse], error)
	HandleInbound(context.Context, *connect.Request[v1.HandleInboundRequest]) (*connect.Response[v1.HandleInboundResponse], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
}

// NewWhatsAppServiceClient constructs a client for the evs.v1.WhatsAppService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWhatsAppServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WhatsAppServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	whatsAppServiceMethods := v1.File_evs_v1_whatsapp_proto.Services().ByName("WhatsAppService").Methods()
	return &whatsAppServiceClient{
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.SendMessageResponse](
			httpClient,
			baseURL+WhatsAppServiceSendMessageProcedure,
			connect.WithSchema(whatsAppServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
		sendTemplate: connect.NewClient[v1.SendTemplateRequest, v1.SendTemplateResponse](
			httpClient,
			baseURL+WhatsAppServiceSendTemplateProcedure,
			connect.WithSchema(whatsAppServiceMethods.ByName("SendTemplate")),
			connect.WithClientOptions(opts...),
		),
		handleInbound: connect.NewClient[v1.HandleInboundRequest, v1.HandleInboundResponse](
			httpClient,
			baseURL+WhatsAppServiceHandleInboundProcedure,
			connect.WithSchema(whatsAppServiceMethods.ByName("HandleInbound")),
			connect.WithClientOptions(opts...),
		),
		listMessages: connect.NewClient[v1.ListMessagesRequest, v1.ListMessagesResponse](
			httpClient,
			baseURL+WhatsAppServiceListMessagesProcedure,
			connect.WithSchema(whatsAppServiceMethods.ByName("ListMessages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// whatsAppServiceClient implements WhatsAppServiceClient.
type whatsAppServiceClient struct {
	sendMessage   *connect.Client[v1.SendMessageRequest, v1.SendMessageResponse]
	sendTemplate  *connect.Client[v1.SendTemplateRequest, v1.SendTemplateResponse]
	handleInbound *connect.Client[v1.HandleInboundRequest, v1.HandleInboundResponse]
	listMessages  *connect.Client[v1.ListMessagesRequest, v1.ListMessagesResponse]
}

// SendMessage calls evs.v1.WhatsAppService.SendMessage.
func (c *whatsAppServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// SendTemplate calls evs.v1.WhatsAppService.SendTemplate.
func (c *whatsAppServiceClient) SendTemplate(ctx context.Context, req *connect.Request[v1.SendTemplateRequest]) (*connect.Response[v1.SendTemplateResponse], error) {
	return c.sendTemplate.CallUnary(ctx, req)
}

// HandleInbound calls evs.v1.WhatsAppService.HandleInbound.
func (c *whatsAppServiceClient) HandleInbound(ctx context.Context, req *connect.Request[v1.HandleInboundRequest]) (*connect.Response[v1.HandleInboundResponse], error) {
	return c.handleInbound.CallUnary(ctx, req)
}

// ListMessages calls evs.v1.WhatsAppService.ListMessages.
func (c *whatsAppServiceClient) ListMessages(ctx context.Context, req *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return c.listMessages.CallUnary(ctx, req)
}

// WhatsAppServiceHandler is an implementation of the evs.v1.WhatsAppService service.
type WhatsAppServiceHandler interface {
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	SendTemplate(context.Context, *connect.Request[v1.SendTemplateRequest]) (*connect.Response[v1.SendTemplateResponse], error)
	HandleInbound(context.Context, *connect.Request[v1.HandleInboundRequest]) (*connect.Response[v1.HandleInboundResponse], error)
	ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error)
}

// NewWhatsAppServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWhatsAppServiceHandler(svc WhatsAppServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	whatsAppServiceMethods := v1.File_evs_v1_whatsapp_proto.Services().ByName("WhatsAppService").Methods()
	whatsAppServiceSendMessageHandler := connect.NewUnaryHandler(
		WhatsAppServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(whatsAppServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	whatsAppServiceSendTemplateHandler := connect.NewUnaryHandler(
		WhatsAppServiceSendTemplateProcedure,
		svc.SendTemplate,
		connect.WithSchema(whatsAppServiceMethods.ByName("SendTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	whatsAppServiceHandleInboundHandler := connect.NewUnaryHandler(
		WhatsAppServiceHandleInboundProcedure,
		svc.HandleInbound,
		connect.WithSchema(whatsAppServiceMethods.ByName("HandleInbound")),
		connect.WithHandlerOptions(opts...),
	)
	whatsAppServiceListMessagesHandler := connect.NewUnaryHandler(
		WhatsAppServiceListMessagesProcedure,
		svc.ListMessages,
		connect.WithSchema(whatsAppServiceMethods.ByName("ListMessages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/evs.v1.WhatsAppService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WhatsAppServiceSendMessageProcedure:
			whatsAppServiceSendMessageHandler.ServeHTTP(w, r)
		case WhatsAppServiceSendTemplateProcedure:
			whatsAppServiceSendTemplateHandler.ServeHTTP(w, r)
		case WhatsAppServiceHandleInboundProcedure:
			whatsAppServiceHandleInboundHandler.ServeHTTP(w, r)
		case WhatsAppServiceListMessagesProcedure:
			whatsAppServiceListMessagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWhatsAppServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWhatsAppServiceHandler struct{}

func (UnimplementedWhatsAppServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.WhatsAppService.SendMessage is not implemented"))
}

func (UnimplementedWhatsAppServiceHandler) SendTemplate(context.Context, *connect.Request[v1.SendTemplateRequest]) (*connect.Response[v1.SendTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.WhatsAppService.SendTemplate is not implemented"))
}

func (UnimplementedWhatsAppServiceHandler) HandleInbound(context.Context, *connect.Request[v1.HandleInboundRequest]) (*connect.Response[v1.HandleInboundResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.WhatsAppService.HandleInbound is not implemented"))
}

func (UnimplementedWhatsAppServiceHandler) ListMessages(context.Context, *connect.Request[v1.ListMessagesRequest]) (*connect.Response[v1.ListMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("evs.v1.WhatsAppService.ListMessages is not implemented"))
}
