// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/billing.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUsageRequest, GetUsageResponse, ListInvoicesRequest, ListInvoicesResponse, RecordUsageRequest, RecordUsageResponse } from "./billing_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.BillingService
 */
export const BillingService = {
  typeName: "evs.v1.BillingService",
  methods: {
    /**
     * @generated from rpc evs.v1.BillingService.GetUsage
     */
    getUsage: {
      name: "GetUsage",
      I: GetUsageRequest,
      O: GetUsageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.BillingService.ListInvoices
     */
    listInvoices: {
      name: "ListInvoices",
      I: ListInvoicesRequest,
      O: ListInvoicesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.BillingService.RecordUsage
     */
    recordUsage: {
      name: "RecordUsage",
      I: RecordUsageRequest,
      O: RecordUsageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

