// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/campaign.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateCampaignRequest, CreateCampaignResponse, GetCampaignRequest, GetCampaignResponse, ListCampaignsRequest, ListCampaignsResponse, PauseCampaignRequest, PauseCampaignResponse, StartCampaignRequest, StartCampaignResponse } from "./campaign_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.CampaignService
 */
export const CampaignService = {
  typeName: "evs.v1.CampaignService",
  methods: {
    /**
     * @generated from rpc evs.v1.CampaignService.CreateCampaign
     */
    createCampaign: {
      name: "CreateCampaign",
      I: CreateCampaignRequest,
      O: CreateCampaignResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.CampaignService.GetCampaign
     */
    getCampaign: {
      name: "GetCampaign",
      I: GetCampaignRequest,
      O: GetCampaignResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.CampaignService.ListCampaigns
     */
    listCampaigns: {
      name: "ListCampaigns",
      I: ListCampaignsRequest,
      O: ListCampaignsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.CampaignService.StartCampaign
     */
    startCampaign: {
      name: "StartCampaign",
      I: StartCampaignRequest,
      O: StartCampaignResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.CampaignService.PauseCampaign
     */
    pauseCampaign: {
      name: "PauseCampaign",
      I: PauseCampaignRequest,
      O: PauseCampaignResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

