// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/consent.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AuditActor, ConsentRecord, PageRequest, PageResponse } from "./common_pb";
import { file_evs_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/consent.proto.
 */
export const file_evs_v1_consent: GenFile = /*@__PURE__*/
  fileDesc("ChRldnMvdjEvY29uc2VudC5wcm90bxIGZXZzLnYxInMKFFJlY29yZENvbnNlbnRSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIlCgZyZWNvcmQYAiABKAsyFS5ldnMudjEuQ29uc2VudFJlY29yZBIhCgVhY3RvchgDIAEoCzISLmV2cy52MS5BdWRpdEFjdG9yIj4KFVJlY29yZENvbnNlbnRSZXNwb25zZRIlCgZyZWNvcmQYASABKAsyFS5ldnMudjEuQ29uc2VudFJlY29yZCJxChRSZXZva2VDb25zZW50UmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSEgoKY29udGFjdF9pZBgCIAEoCRIPCgdjaGFubmVsGAMgASgJEiEKBWFjdG9yGAQgASgLMhIuZXZzLnYxLkF1ZGl0QWN0b3IiPgoVUmV2b2tlQ29uc2VudFJlc3BvbnNlEiUKBnJlY29yZBgBIAEoCzIVLmV2cy52MS5Db25zZW50UmVjb3JkIk0KE0NoZWNrQ29uc2VudFJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEhIKCmNvbnRhY3RfaWQYAiABKAkSDwoHY2hhbm5lbBgDIAEoCSJOChRDaGVja0NvbnNlbnRSZXNwb25zZRIPCgdncmFudGVkGAEgASgIEiUKBnJlY29yZBgCIAEoCzIVLmV2cy52MS5Db25zZW50UmVjb3JkIl4KEkxpc3RDb25zZW50UmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSEgoKY29udGFjdF9pZBgCIAEoCRIhCgRwYWdlGAMgASgLMhMuZXZzLnYxLlBhZ2VSZXF1ZXN0ImEKE0xpc3RDb25zZW50UmVzcG9uc2USJgoHcmVjb3JkcxgBIAMoCzIVLmV2cy52MS5Db25zZW50UmVjb3JkEiIKBHBhZ2UYAiABKAsyFC5ldnMudjEuUGFnZVJlc3BvbnNlMr8CCg5Db25zZW50U2VydmljZRJMCg1SZWNvcmRDb25zZW50EhwuZXZzLnYxLlJlY29yZENvbnNlbnRSZXF1ZXN0Gh0uZXZzLnYxLlJlY29yZENvbnNlbnRSZXNwb25zZRJMCg1SZXZva2VDb25zZW50EhwuZXZzLnYxLlJldm9rZUNvbnNlbnRSZXF1ZXN0Gh0uZXZzLnYxLlJldm9rZUNvbnNlbnRSZXNwb25zZRJJCgxDaGVja0NvbnNlbnQSGy5ldnMudjEuQ2hlY2tDb25zZW50UmVxdWVzdBocLmV2cy52MS5DaGVja0NvbnNlbnRSZXNwb25zZRJGCgtMaXN0Q29uc2VudBIaLmV2cy52MS5MaXN0Q29uc2VudFJlcXVlc3QaGy5ldnMudjEuTGlzdENvbnNlbnRSZXNwb25zZUJ8Cgpjb20uZXZzLnYxQgxDb25zZW50UHJvdG9QAVonZ2l0aHViLmNvbS9sZWFkL2xpYnMvZ28vcGIvZXZzL3YxO2V2c3YxogIDRVhYqgIGRXZzLlYxygIGRXZzXFYx4gISRXZzXFYxXEdQQk1ldGFkYXRh6gIHRXZzOjpWMWIGcHJvdG8z", [file_evs_v1_common]);

/**
 * @generated from message evs.v1.RecordConsentRequest
 */
export type RecordConsentRequest = Message<"evs.v1.RecordConsentRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: evs.v1.ConsentRecord record = 2;
   */
  record?: ConsentRecord | undefined;

  /**
   * @generated from field: evs.v1.AuditActor actor = 3;
   */
  actor?: AuditActor | undefined;
};

/**
 * Describes the message evs.v1.RecordConsentRequest.
 * Use `create(RecordConsentRequestSchema)` to create a new message.
 */
export const RecordConsentRequestSchema: GenMessage<RecordConsentRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 0);

/**
 * @generated from message evs.v1.RecordConsentResponse
 */
export type RecordConsentResponse = Message<"evs.v1.RecordConsentResponse"> & {
  /**
   * @generated from field: evs.v1.ConsentRecord record = 1;
   */
  record?: ConsentRecord | undefined;
};

/**
 * Describes the message evs.v1.RecordConsentResponse.
 * Use `create(RecordConsentResponseSchema)` to create a new message.
 */
export const RecordConsentResponseSchema: GenMessage<RecordConsentResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 1);

/**
 * @generated from message evs.v1.RevokeConsentRequest
 */
export type RevokeConsentRequest = Message<"evs.v1.RevokeConsentRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string channel = 3;
   */
  channel: string;

  /**
   * @generated from field: evs.v1.AuditActor actor = 4;
   */
  actor?: AuditActor | undefined;
};

/**
 * Describes the message evs.v1.RevokeConsentRequest.
 * Use `create(RevokeConsentRequestSchema)` to create a new message.
 */
export const RevokeConsentRequestSchema: GenMessage<RevokeConsentRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 2);

/**
 * @generated from message evs.v1.RevokeConsentResponse
 */
export type RevokeConsentResponse = Message<"evs.v1.RevokeConsentResponse"> & {
  /**
   * @generated from field: evs.v1.ConsentRecord record = 1;
   */
  record?: ConsentRecord | undefined;
};

/**
 * Describes the message evs.v1.RevokeConsentResponse.
 * Use `create(RevokeConsentResponseSchema)` to create a new message.
 */
export const RevokeConsentResponseSchema: GenMessage<RevokeConsentResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 3);

/**
 * @generated from message evs.v1.CheckConsentRequest
 */
export type CheckConsentRequest = Message<"evs.v1.CheckConsentRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string channel = 3;
   */
  channel: string;
};

/**
 * Describes the message evs.v1.CheckConsentRequest.
 * Use `create(CheckConsentRequestSchema)` to create a new message.
 */
export const CheckConsentRequestSchema: GenMessage<CheckConsentRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 4);

/**
 * @generated from message evs.v1.CheckConsentResponse
 */
export type CheckConsentResponse = Message<"evs.v1.CheckConsentResponse"> & {
  /**
   * @generated from field: bool granted = 1;
   */
  granted: boolean;

  /**
   * @generated from field: evs.v1.ConsentRecord record = 2;
   */
  record?: ConsentRecord | undefined;
};

/**
 * Describes the message evs.v1.CheckConsentResponse.
 * Use `create(CheckConsentResponseSchema)` to create a new message.
 */
export const CheckConsentResponseSchema: GenMessage<CheckConsentResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 5);

/**
 * @generated from message evs.v1.ListConsentRequest
 */
export type ListConsentRequest = Message<"evs.v1.ListConsentRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: evs.v1.PageRequest page = 3;
   */
  page?: PageRequest | undefined;
};

/**
 * Describes the message evs.v1.ListConsentRequest.
 * Use `create(ListConsentRequestSchema)` to create a new message.
 */
export const ListConsentRequestSchema: GenMessage<ListConsentRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 6);

/**
 * @generated from message evs.v1.ListConsentResponse
 */
export type ListConsentResponse = Message<"evs.v1.ListConsentResponse"> & {
  /**
   * @generated from field: repeated evs.v1.ConsentRecord records = 1;
   */
  records: ConsentRecord[];

  /**
   * @generated from field: evs.v1.PageResponse page = 2;
   */
  page?: PageResponse | undefined;
};

/**
 * Describes the message evs.v1.ListConsentResponse.
 * Use `create(ListConsentResponseSchema)` to create a new message.
 */
export const ListConsentResponseSchema: GenMessage<ListConsentResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_consent, 7);

/**
 * @generated from service evs.v1.ConsentService
 */
export const ConsentService: GenService<{
  /**
   * @generated from rpc evs.v1.ConsentService.RecordConsent
   */
  recordConsent: {
    methodKind: "unary";
    input: typeof RecordConsentRequestSchema;
    output: typeof RecordConsentResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.ConsentService.RevokeConsent
   */
  revokeConsent: {
    methodKind: "unary";
    input: typeof RevokeConsentRequestSchema;
    output: typeof RevokeConsentResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.ConsentService.CheckConsent
   */
  checkConsent: {
    methodKind: "unary";
    input: typeof CheckConsentRequestSchema;
    output: typeof CheckConsentResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.ConsentService.ListConsent
   */
  listConsent: {
    methodKind: "unary";
    input: typeof ListConsentRequestSchema;
    output: typeof ListConsentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_consent, 0);

