// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/guardrail.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/guardrail.proto.
 */
export const file_evs_v1_guardrail: GenFile = /*@__PURE__*/
  fileDesc("ChZldnMvdjEvZ3VhcmRyYWlsLnByb3RvEgZldnMudjEiVQoMQ2hlY2tSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIPCgdjb250ZW50GAIgASgJEg8KB2NvbnRleHQYAyABKAkSEAoIcG9saWNpZXMYBCADKAkiawoNQ2hlY2tSZXNwb25zZRIPCgdhbGxvd2VkGAEgASgIEi4KCnZpb2xhdGlvbnMYAiADKAsyGi5ldnMudjEuR3VhcmRyYWlsVmlvbGF0aW9uEhkKEXNhbml0aXplZF9jb250ZW50GAMgASgJIkYKEkd1YXJkcmFpbFZpb2xhdGlvbhIOCgZwb2xpY3kYASABKAkSDgoGcmVhc29uGAIgASgJEhAKCHNldmVyaXR5GAMgASgBMkgKEEd1YXJkcmFpbFNlcnZpY2USNAoFQ2hlY2sSFC5ldnMudjEuQ2hlY2tSZXF1ZXN0GhUuZXZzLnYxLkNoZWNrUmVzcG9uc2VCfgoKY29tLmV2cy52MUIOR3VhcmRyYWlsUHJvdG9QAVonZ2l0aHViLmNvbS9sZWFkL2xpYnMvZ28vcGIvZXZzL3YxO2V2c3YxogIDRVhYqgIGRXZzLlYxygIGRXZzXFYx4gISRXZzXFYxXEdQQk1ldGFkYXRh6gIHRXZzOjpWMWIGcHJvdG8z");

/**
 * @generated from message evs.v1.CheckRequest
 */
export type CheckRequest = Message<"evs.v1.CheckRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: string context = 3;
   */
  context: string;

  /**
   * @generated from field: repeated string policies = 4;
   */
  policies: string[];
};

/**
 * Describes the message evs.v1.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema: GenMessage<CheckRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_guardrail, 0);

/**
 * @generated from message evs.v1.CheckResponse
 */
export type CheckResponse = Message<"evs.v1.CheckResponse"> & {
  /**
   * @generated from field: bool allowed = 1;
   */
  allowed: boolean;

  /**
   * @generated from field: repeated evs.v1.GuardrailViolation violations = 2;
   */
  violations: GuardrailViolation[];

  /**
   * @generated from field: string sanitized_content = 3;
   */
  sanitizedContent: string;
};

/**
 * Describes the message evs.v1.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema: GenMessage<CheckResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_guardrail, 1);

/**
 * @generated from message evs.v1.GuardrailViolation
 */
export type GuardrailViolation = Message<"evs.v1.GuardrailViolation"> & {
  /**
   * @generated from field: string policy = 1;
   */
  policy: string;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: double severity = 3;
   */
  severity: number;
};

/**
 * Describes the message evs.v1.GuardrailViolation.
 * Use `create(GuardrailViolationSchema)` to create a new message.
 */
export const GuardrailViolationSchema: GenMessage<GuardrailViolation> = /*@__PURE__*/
  messageDesc(file_evs_v1_guardrail, 2);

/**
 * @generated from service evs.v1.GuardrailService
 */
export const GuardrailService: GenService<{
  /**
   * @generated from rpc evs.v1.GuardrailService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_guardrail, 0);

