// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/knowledge.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteDocumentRequest, DeleteDocumentResponse, IngestDocumentRequest, IngestDocumentResponse, ListDocumentsRequest, ListDocumentsResponse, QueryRequest, QueryResponse } from "./knowledge_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.KnowledgeService
 */
export const KnowledgeService = {
  typeName: "evs.v1.KnowledgeService",
  methods: {
    /**
     * @generated from rpc evs.v1.KnowledgeService.IngestDocument
     */
    ingestDocument: {
      name: "IngestDocument",
      I: IngestDocumentRequest,
      O: IngestDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.KnowledgeService.DeleteDocument
     */
    deleteDocument: {
      name: "DeleteDocument",
      I: DeleteDocumentRequest,
      O: DeleteDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.KnowledgeService.Query
     */
    query: {
      name: "Query",
      I: QueryRequest,
      O: QueryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.KnowledgeService.ListDocuments
     */
    listDocuments: {
      name: "ListDocuments",
      I: ListDocumentsRequest,
      O: ListDocumentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

