// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/lead_import.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetImportJobRequest, GetImportJobResponse, ImportLeadsRequest, ImportLeadsResponse, ListImportJobsRequest, ListImportJobsResponse } from "./lead_import_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.LeadImportService
 */
export const LeadImportService = {
  typeName: "evs.v1.LeadImportService",
  methods: {
    /**
     * @generated from rpc evs.v1.LeadImportService.ImportLeads
     */
    importLeads: {
      name: "ImportLeads",
      I: ImportLeadsRequest,
      O: ImportLeadsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.LeadImportService.GetImportJob
     */
    getImportJob: {
      name: "GetImportJob",
      I: GetImportJobRequest,
      O: GetImportJobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.LeadImportService.ListImportJobs
     */
    listImportJobs: {
      name: "ListImportJobs",
      I: ListImportJobsRequest,
      O: ListImportJobsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

