// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/llm_router.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/llm_router.proto.
 */
export const file_evs_v1_llm_router: GenFile = /*@__PURE__*/
  fileDesc("ChdldnMvdjEvbGxtX3JvdXRlci5wcm90bxIGZXZzLnYxIogBCg9Db21wbGV0ZVJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEhIKCm1vZGVsX2hpbnQYAiABKAkSJQoIbWVzc2FnZXMYAyADKAsyEy5ldnMudjEuQ2hhdE1lc3NhZ2USEwoLdGVtcGVyYXR1cmUYBCABKAESEgoKbWF4X3Rva2VucxgFIAEoBSJpChBDb21wbGV0ZVJlc3BvbnNlEg8KB2NvbnRlbnQYASABKAkSEgoKbW9kZWxfdXNlZBgCIAEoCRIVCg1wcm9tcHRfdG9rZW5zGAMgASgFEhkKEWNvbXBsZXRpb25fdG9rZW5zGAQgASgFIo4BChVTdHJlYW1Db21wbGV0ZVJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEhIKCm1vZGVsX2hpbnQYAiABKAkSJQoIbWVzc2FnZXMYAyADKAsyEy5ldnMudjEuQ2hhdE1lc3NhZ2USEwoLdGVtcGVyYXR1cmUYBCABKAESEgoKbWF4X3Rva2VucxgFIAEoBSI5ChZTdHJlYW1Db21wbGV0ZVJlc3BvbnNlEg0KBWRlbHRhGAEgASgJEhAKCGlzX2ZpbmFsGAIgASgIIiwKC0NoYXRNZXNzYWdlEgwKBHJvbGUYASABKAkSDwoHY29udGVudBgCIAEoCTKkAQoQTGxtUm91dGVyU2VydmljZRI9CghDb21wbGV0ZRIXLmV2cy52MS5Db21wbGV0ZVJlcXVlc3QaGC5ldnMudjEuQ29tcGxldGVSZXNwb25zZRJRCg5TdHJlYW1Db21wbGV0ZRIdLmV2cy52MS5TdHJlYW1Db21wbGV0ZVJlcXVlc3QaHi5ldnMudjEuU3RyZWFtQ29tcGxldGVSZXNwb25zZTABQn4KCmNvbS5ldnMudjFCDkxsbVJvdXRlclByb3RvUAFaJ2dpdGh1Yi5jb20vbGVhZC9saWJzL2dvL3BiL2V2cy92MTtldnN2MaICA0VYWKoCBkV2cy5WMcoCBkV2c1xWMeICEkV2c1xWMVxHUEJNZXRhZGF0YeoCB0V2czo6VjFiBnByb3RvMw");

/**
 * @generated from message evs.v1.CompleteRequest
 */
export type CompleteRequest = Message<"evs.v1.CompleteRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string model_hint = 2;
   */
  modelHint: string;

  /**
   * @generated from field: repeated evs.v1.ChatMessage messages = 3;
   */
  messages: ChatMessage[];

  /**
   * @generated from field: double temperature = 4;
   */
  temperature: number;

  /**
   * @generated from field: int32 max_tokens = 5;
   */
  maxTokens: number;
};

/**
 * Describes the message evs.v1.CompleteRequest.
 * Use `create(CompleteRequestSchema)` to create a new message.
 */
export const CompleteRequestSchema: GenMessage<CompleteRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_llm_router, 0);

/**
 * @generated from message evs.v1.CompleteResponse
 */
export type CompleteResponse = Message<"evs.v1.CompleteResponse"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * @generated from field: string model_used = 2;
   */
  modelUsed: string;

  /**
   * @generated from field: int32 prompt_tokens = 3;
   */
  promptTokens: number;

  /**
   * @generated from field: int32 completion_tokens = 4;
   */
  completionTokens: number;
};

/**
 * Describes the message evs.v1.CompleteResponse.
 * Use `create(CompleteResponseSchema)` to create a new message.
 */
export const CompleteResponseSchema: GenMessage<CompleteResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_llm_router, 1);

/**
 * @generated from message evs.v1.StreamCompleteRequest
 */
export type StreamCompleteRequest = Message<"evs.v1.StreamCompleteRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string model_hint = 2;
   */
  modelHint: string;

  /**
   * @generated from field: repeated evs.v1.ChatMessage messages = 3;
   */
  messages: ChatMessage[];

  /**
   * @generated from field: double temperature = 4;
   */
  temperature: number;

  /**
   * @generated from field: int32 max_tokens = 5;
   */
  maxTokens: number;
};

/**
 * Describes the message evs.v1.StreamCompleteRequest.
 * Use `create(StreamCompleteRequestSchema)` to create a new message.
 */
export const StreamCompleteRequestSchema: GenMessage<StreamCompleteRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_llm_router, 2);

/**
 * @generated from message evs.v1.StreamCompleteResponse
 */
export type StreamCompleteResponse = Message<"evs.v1.StreamCompleteResponse"> & {
  /**
   * @generated from field: string delta = 1;
   */
  delta: string;

  /**
   * @generated from field: bool is_final = 2;
   */
  isFinal: boolean;
};

/**
 * Describes the message evs.v1.StreamCompleteResponse.
 * Use `create(StreamCompleteResponseSchema)` to create a new message.
 */
export const StreamCompleteResponseSchema: GenMessage<StreamCompleteResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_llm_router, 3);

/**
 * @generated from message evs.v1.ChatMessage
 */
export type ChatMessage = Message<"evs.v1.ChatMessage"> & {
  /**
   * @generated from field: string role = 1;
   */
  role: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message evs.v1.ChatMessage.
 * Use `create(ChatMessageSchema)` to create a new message.
 */
export const ChatMessageSchema: GenMessage<ChatMessage> = /*@__PURE__*/
  messageDesc(file_evs_v1_llm_router, 4);

/**
 * @generated from service evs.v1.LlmRouterService
 */
export const LlmRouterService: GenService<{
  /**
   * @generated from rpc evs.v1.LlmRouterService.Complete
   */
  complete: {
    methodKind: "unary";
    input: typeof CompleteRequestSchema;
    output: typeof CompleteResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.LlmRouterService.StreamComplete
   */
  streamComplete: {
    methodKind: "server_streaming";
    input: typeof StreamCompleteRequestSchema;
    output: typeof StreamCompleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_llm_router, 0);

