// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/notification.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PageRequest, PageResponse } from "./common_pb";
import { file_evs_v1_common } from "./common_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/notification.proto.
 */
export const file_evs_v1_notification: GenFile = /*@__PURE__*/
  fileDesc("ChlldnMvdjEvbm90aWZpY2F0aW9uLnByb3RvEgZldnMudjEiwwEKC1NlbmRSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRISCgpjb250YWN0X2lkGAIgASgJEg8KB2NoYW5uZWwYAyABKAkSEwoLdGVtcGxhdGVfaWQYBCABKAkSNQoJdmFyaWFibGVzGAUgAygLMiIuZXZzLnYxLlNlbmRSZXF1ZXN0LlZhcmlhYmxlc0VudHJ5GjAKDlZhcmlhYmxlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiJwoMU2VuZFJlc3BvbnNlEhcKD25vdGlmaWNhdGlvbl9pZBgBIAEoCSI+ChBHZXRTdGF0dXNSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIXCg9ub3RpZmljYXRpb25faWQYAiABKAkiaQoRR2V0U3RhdHVzUmVzcG9uc2USFwoPbm90aWZpY2F0aW9uX2lkGAEgASgJEg4KBnN0YXR1cxgCIAEoCRIrCgdzZW50X2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJkChhMaXN0Tm90aWZpY2F0aW9uc1JlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEhIKCmNvbnRhY3RfaWQYAiABKAkSIQoEcGFnZRgDIAEoCzITLmV2cy52MS5QYWdlUmVxdWVzdCJsChlMaXN0Tm90aWZpY2F0aW9uc1Jlc3BvbnNlEisKDW5vdGlmaWNhdGlvbnMYASADKAsyFC5ldnMudjEuTm90aWZpY2F0aW9uEiIKBHBhZ2UYAiABKAsyFC5ldnMudjEuUGFnZVJlc3BvbnNlIqcBCgxOb3RpZmljYXRpb24SCgoCaWQYASABKAkSEQoJdGVuYW50X2lkGAIgASgJEhIKCmNvbnRhY3RfaWQYAyABKAkSDwoHY2hhbm5lbBgEIAEoCRITCgt0ZW1wbGF0ZV9pZBgFIAEoCRIOCgZzdGF0dXMYBiABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAy5AEKE05vdGlmaWNhdGlvblNlcnZpY2USMQoEU2VuZBITLmV2cy52MS5TZW5kUmVxdWVzdBoULmV2cy52MS5TZW5kUmVzcG9uc2USQAoJR2V0U3RhdHVzEhguZXZzLnYxLkdldFN0YXR1c1JlcXVlc3QaGS5ldnMudjEuR2V0U3RhdHVzUmVzcG9uc2USWAoRTGlzdE5vdGlmaWNhdGlvbnMSIC5ldnMudjEuTGlzdE5vdGlmaWNhdGlvbnNSZXF1ZXN0GiEuZXZzLnYxLkxpc3ROb3RpZmljYXRpb25zUmVzcG9uc2VCgQEKCmNvbS5ldnMudjFCEU5vdGlmaWNhdGlvblByb3RvUAFaJ2dpdGh1Yi5jb20vbGVhZC9saWJzL2dvL3BiL2V2cy92MTtldnN2MaICA0VYWKoCBkV2cy5WMcoCBkV2c1xWMeICEkV2c1xWMVxHUEJNZXRhZGF0YeoCB0V2czo6VjFiBnByb3RvMw", [file_evs_v1_common, file_google_protobuf_timestamp]);

/**
 * @generated from message evs.v1.SendRequest
 */
export type SendRequest = Message<"evs.v1.SendRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string channel = 3;
   */
  channel: string;

  /**
   * @generated from field: string template_id = 4;
   */
  templateId: string;

  /**
   * @generated from field: map<string, string> variables = 5;
   */
  variables: { [key: string]: string };
};

/**
 * Describes the message evs.v1.SendRequest.
 * Use `create(SendRequestSchema)` to create a new message.
 */
export const SendRequestSchema: GenMessage<SendRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 0);

/**
 * @generated from message evs.v1.SendResponse
 */
export type SendResponse = Message<"evs.v1.SendResponse"> & {
  /**
   * @generated from field: string notification_id = 1;
   */
  notificationId: string;
};

/**
 * Describes the message evs.v1.SendResponse.
 * Use `create(SendResponseSchema)` to create a new message.
 */
export const SendResponseSchema: GenMessage<SendResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 1);

/**
 * @generated from message evs.v1.GetStatusRequest
 */
export type GetStatusRequest = Message<"evs.v1.GetStatusRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string notification_id = 2;
   */
  notificationId: string;
};

/**
 * Describes the message evs.v1.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export const GetStatusRequestSchema: GenMessage<GetStatusRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 2);

/**
 * @generated from message evs.v1.GetStatusResponse
 */
export type GetStatusResponse = Message<"evs.v1.GetStatusResponse"> & {
  /**
   * @generated from field: string notification_id = 1;
   */
  notificationId: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: google.protobuf.Timestamp sent_at = 3;
   */
  sentAt?: Timestamp | undefined;
};

/**
 * Describes the message evs.v1.GetStatusResponse.
 * Use `create(GetStatusResponseSchema)` to create a new message.
 */
export const GetStatusResponseSchema: GenMessage<GetStatusResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 3);

/**
 * @generated from message evs.v1.ListNotificationsRequest
 */
export type ListNotificationsRequest = Message<"evs.v1.ListNotificationsRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: evs.v1.PageRequest page = 3;
   */
  page?: PageRequest | undefined;
};

/**
 * Describes the message evs.v1.ListNotificationsRequest.
 * Use `create(ListNotificationsRequestSchema)` to create a new message.
 */
export const ListNotificationsRequestSchema: GenMessage<ListNotificationsRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 4);

/**
 * @generated from message evs.v1.ListNotificationsResponse
 */
export type ListNotificationsResponse = Message<"evs.v1.ListNotificationsResponse"> & {
  /**
   * @generated from field: repeated evs.v1.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: evs.v1.PageResponse page = 2;
   */
  page?: PageResponse | undefined;
};

/**
 * Describes the message evs.v1.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 5);

/**
 * @generated from message evs.v1.Notification
 */
export type Notification = Message<"evs.v1.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 3;
   */
  contactId: string;

  /**
   * @generated from field: string channel = 4;
   */
  channel: string;

  /**
   * @generated from field: string template_id = 5;
   */
  templateId: string;

  /**
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message evs.v1.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification> = /*@__PURE__*/
  messageDesc(file_evs_v1_notification, 6);

/**
 * @generated from service evs.v1.NotificationService
 */
export const NotificationService: GenService<{
  /**
   * @generated from rpc evs.v1.NotificationService.Send
   */
  send: {
    methodKind: "unary";
    input: typeof SendRequestSchema;
    output: typeof SendResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.NotificationService.GetStatus
   */
  getStatus: {
    methodKind: "unary";
    input: typeof GetStatusRequestSchema;
    output: typeof GetStatusResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.NotificationService.ListNotifications
   */
  listNotifications: {
    methodKind: "unary";
    input: typeof ListNotificationsRequestSchema;
    output: typeof ListNotificationsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_notification, 0);

