// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/scheduler.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PageRequest, PageResponse } from "./common_pb";
import { file_evs_v1_common } from "./common_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/scheduler.proto.
 */
export const file_evs_v1_scheduler: GenFile = /*@__PURE__*/
  fileDesc("ChZldnMvdjEvc2NoZWR1bGVyLnByb3RvEgZldnMudjEijAEKDFNjaGVkdWxlZEpvYhIKCgJpZBgBIAEoCRIRCgl0ZW5hbnRfaWQYAiABKAkSEAoIam9iX3R5cGUYAyABKAkSKgoGcnVuX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZzdGF0dXMYBSABKAkSDwoHcGF5bG9hZBgGIAEoDCJKChJTY2hlZHVsZUpvYlJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEiEKA2pvYhgCIAEoCzIULmV2cy52MS5TY2hlZHVsZWRKb2IiOAoTU2NoZWR1bGVKb2JSZXNwb25zZRIhCgNqb2IYASABKAsyFC5ldnMudjEuU2NoZWR1bGVkSm9iIjUKEENhbmNlbEpvYlJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEg4KBmpvYl9pZBgCIAEoCSITChFDYW5jZWxKb2JSZXNwb25zZSJHCg9MaXN0Sm9ic1JlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEiEKBHBhZ2UYAiABKAsyEy5ldnMudjEuUGFnZVJlcXVlc3QiWgoQTGlzdEpvYnNSZXNwb25zZRIiCgRqb2JzGAEgAygLMhQuZXZzLnYxLlNjaGVkdWxlZEpvYhIiCgRwYWdlGAIgASgLMhQuZXZzLnYxLlBhZ2VSZXNwb25zZTLbAQoQU2NoZWR1bGVyU2VydmljZRJGCgtTY2hlZHVsZUpvYhIaLmV2cy52MS5TY2hlZHVsZUpvYlJlcXVlc3QaGy5ldnMudjEuU2NoZWR1bGVKb2JSZXNwb25zZRJACglDYW5jZWxKb2ISGC5ldnMudjEuQ2FuY2VsSm9iUmVxdWVzdBoZLmV2cy52MS5DYW5jZWxKb2JSZXNwb25zZRI9CghMaXN0Sm9icxIXLmV2cy52MS5MaXN0Sm9ic1JlcXVlc3QaGC5ldnMudjEuTGlzdEpvYnNSZXNwb25zZUJ+Cgpjb20uZXZzLnYxQg5TY2hlZHVsZXJQcm90b1ABWidnaXRodWIuY29tL2xlYWQvbGlicy9nby9wYi9ldnMvdjE7ZXZzdjGiAgNFWFiqAgZFdnMuVjHKAgZFdnNcVjHiAhJFdnNcVjFcR1BCTWV0YWRhdGHqAgdFdnM6OlYxYgZwcm90bzM", [file_evs_v1_common, file_google_protobuf_timestamp]);

/**
 * @generated from message evs.v1.ScheduledJob
 */
export type ScheduledJob = Message<"evs.v1.ScheduledJob"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string job_type = 3;
   */
  jobType: string;

  /**
   * @generated from field: google.protobuf.Timestamp run_at = 4;
   */
  runAt?: Timestamp | undefined;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: bytes payload = 6;
   */
  payload: Uint8Array;
};

/**
 * Describes the message evs.v1.ScheduledJob.
 * Use `create(ScheduledJobSchema)` to create a new message.
 */
export const ScheduledJobSchema: GenMessage<ScheduledJob> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 0);

/**
 * @generated from message evs.v1.ScheduleJobRequest
 */
export type ScheduleJobRequest = Message<"evs.v1.ScheduleJobRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: evs.v1.ScheduledJob job = 2;
   */
  job?: ScheduledJob | undefined;
};

/**
 * Describes the message evs.v1.ScheduleJobRequest.
 * Use `create(ScheduleJobRequestSchema)` to create a new message.
 */
export const ScheduleJobRequestSchema: GenMessage<ScheduleJobRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 1);

/**
 * @generated from message evs.v1.ScheduleJobResponse
 */
export type ScheduleJobResponse = Message<"evs.v1.ScheduleJobResponse"> & {
  /**
   * @generated from field: evs.v1.ScheduledJob job = 1;
   */
  job?: ScheduledJob | undefined;
};

/**
 * Describes the message evs.v1.ScheduleJobResponse.
 * Use `create(ScheduleJobResponseSchema)` to create a new message.
 */
export const ScheduleJobResponseSchema: GenMessage<ScheduleJobResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 2);

/**
 * @generated from message evs.v1.CancelJobRequest
 */
export type CancelJobRequest = Message<"evs.v1.CancelJobRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string job_id = 2;
   */
  jobId: string;
};

/**
 * Describes the message evs.v1.CancelJobRequest.
 * Use `create(CancelJobRequestSchema)` to create a new message.
 */
export const CancelJobRequestSchema: GenMessage<CancelJobRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 3);

/**
 * @generated from message evs.v1.CancelJobResponse
 */
export type CancelJobResponse = Message<"evs.v1.CancelJobResponse"> & {
};

/**
 * Describes the message evs.v1.CancelJobResponse.
 * Use `create(CancelJobResponseSchema)` to create a new message.
 */
export const CancelJobResponseSchema: GenMessage<CancelJobResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 4);

/**
 * @generated from message evs.v1.ListJobsRequest
 */
export type ListJobsRequest = Message<"evs.v1.ListJobsRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: evs.v1.PageRequest page = 2;
   */
  page?: PageRequest | undefined;
};

/**
 * Describes the message evs.v1.ListJobsRequest.
 * Use `create(ListJobsRequestSchema)` to create a new message.
 */
export const ListJobsRequestSchema: GenMessage<ListJobsRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 5);

/**
 * @generated from message evs.v1.ListJobsResponse
 */
export type ListJobsResponse = Message<"evs.v1.ListJobsResponse"> & {
  /**
   * @generated from field: repeated evs.v1.ScheduledJob jobs = 1;
   */
  jobs: ScheduledJob[];

  /**
   * @generated from field: evs.v1.PageResponse page = 2;
   */
  page?: PageResponse | undefined;
};

/**
 * Describes the message evs.v1.ListJobsResponse.
 * Use `create(ListJobsResponseSchema)` to create a new message.
 */
export const ListJobsResponseSchema: GenMessage<ListJobsResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scheduler, 6);

/**
 * @generated from service evs.v1.SchedulerService
 */
export const SchedulerService: GenService<{
  /**
   * @generated from rpc evs.v1.SchedulerService.ScheduleJob
   */
  scheduleJob: {
    methodKind: "unary";
    input: typeof ScheduleJobRequestSchema;
    output: typeof ScheduleJobResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.SchedulerService.CancelJob
   */
  cancelJob: {
    methodKind: "unary";
    input: typeof CancelJobRequestSchema;
    output: typeof CancelJobResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.SchedulerService.ListJobs
   */
  listJobs: {
    methodKind: "unary";
    input: typeof ListJobsRequestSchema;
    output: typeof ListJobsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_scheduler, 0);

