// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/scheduler.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelJobRequest, CancelJobResponse, ListJobsRequest, ListJobsResponse, ScheduleJobRequest, ScheduleJobResponse } from "./scheduler_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.SchedulerService
 */
export const SchedulerService = {
  typeName: "evs.v1.SchedulerService",
  methods: {
    /**
     * @generated from rpc evs.v1.SchedulerService.ScheduleJob
     */
    scheduleJob: {
      name: "ScheduleJob",
      I: ScheduleJobRequest,
      O: ScheduleJobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SchedulerService.CancelJob
     */
    cancelJob: {
      name: "CancelJob",
      I: CancelJobRequest,
      O: CancelJobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SchedulerService.ListJobs
     */
    listJobs: {
      name: "ListJobs",
      I: ListJobsRequest,
      O: ListJobsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

