// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/scoring.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/scoring.proto.
 */
export const file_evs_v1_scoring: GenFile = /*@__PURE__*/
  fileDesc("ChRldnMvdjEvc2NvcmluZy5wcm90bxIGZXZzLnYxIqEBChBTY29yZUxlYWRSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIPCgdsZWFkX2lkGAIgASgJEjgKCGZlYXR1cmVzGAMgAygLMiYuZXZzLnYxLlNjb3JlTGVhZFJlcXVlc3QuRmVhdHVyZXNFbnRyeRovCg1GZWF0dXJlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiNQoRU2NvcmVMZWFkUmVzcG9uc2USIAoFc2NvcmUYASABKAsyES5ldnMudjEuTGVhZFNjb3JlIjUKD0dldFNjb3JlUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSDwoHbGVhZF9pZBgCIAEoCSI0ChBHZXRTY29yZVJlc3BvbnNlEiAKBXNjb3JlGAEgASgLMhEuZXZzLnYxLkxlYWRTY29yZSI4ChFCYXRjaFNjb3JlUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSEAoIbGVhZF9pZHMYAiADKAkiNwoSQmF0Y2hTY29yZVJlc3BvbnNlEiEKBnNjb3JlcxgBIAMoCzIRLmV2cy52MS5MZWFkU2NvcmUi3wEKCUxlYWRTY29yZRIPCgdsZWFkX2lkGAEgASgJEg0KBXNjb3JlGAIgASgBEgwKBGJhbmQYAyABKAkSPgoPZmVhdHVyZV93ZWlnaHRzGAQgAygLMiUuZXZzLnYxLkxlYWRTY29yZS5GZWF0dXJlV2VpZ2h0c0VudHJ5Ei0KCXNjb3JlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaNQoTRmVhdHVyZVdlaWdodHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAE6AjgBMtYBCg5TY29yaW5nU2VydmljZRJACglTY29yZUxlYWQSGC5ldnMudjEuU2NvcmVMZWFkUmVxdWVzdBoZLmV2cy52MS5TY29yZUxlYWRSZXNwb25zZRI9CghHZXRTY29yZRIXLmV2cy52MS5HZXRTY29yZVJlcXVlc3QaGC5ldnMudjEuR2V0U2NvcmVSZXNwb25zZRJDCgpCYXRjaFNjb3JlEhkuZXZzLnYxLkJhdGNoU2NvcmVSZXF1ZXN0GhouZXZzLnYxLkJhdGNoU2NvcmVSZXNwb25zZUJ8Cgpjb20uZXZzLnYxQgxTY29yaW5nUHJvdG9QAVonZ2l0aHViLmNvbS9sZWFkL2xpYnMvZ28vcGIvZXZzL3YxO2V2c3YxogIDRVhYqgIGRXZzLlYxygIGRXZzXFYx4gISRXZzXFYxXEdQQk1ldGFkYXRh6gIHRXZzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message evs.v1.ScoreLeadRequest
 */
export type ScoreLeadRequest = Message<"evs.v1.ScoreLeadRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string lead_id = 2;
   */
  leadId: string;

  /**
   * @generated from field: map<string, string> features = 3;
   */
  features: { [key: string]: string };
};

/**
 * Describes the message evs.v1.ScoreLeadRequest.
 * Use `create(ScoreLeadRequestSchema)` to create a new message.
 */
export const ScoreLeadRequestSchema: GenMessage<ScoreLeadRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 0);

/**
 * @generated from message evs.v1.ScoreLeadResponse
 */
export type ScoreLeadResponse = Message<"evs.v1.ScoreLeadResponse"> & {
  /**
   * @generated from field: evs.v1.LeadScore score = 1;
   */
  score?: LeadScore | undefined;
};

/**
 * Describes the message evs.v1.ScoreLeadResponse.
 * Use `create(ScoreLeadResponseSchema)` to create a new message.
 */
export const ScoreLeadResponseSchema: GenMessage<ScoreLeadResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 1);

/**
 * @generated from message evs.v1.GetScoreRequest
 */
export type GetScoreRequest = Message<"evs.v1.GetScoreRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string lead_id = 2;
   */
  leadId: string;
};

/**
 * Describes the message evs.v1.GetScoreRequest.
 * Use `create(GetScoreRequestSchema)` to create a new message.
 */
export const GetScoreRequestSchema: GenMessage<GetScoreRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 2);

/**
 * @generated from message evs.v1.GetScoreResponse
 */
export type GetScoreResponse = Message<"evs.v1.GetScoreResponse"> & {
  /**
   * @generated from field: evs.v1.LeadScore score = 1;
   */
  score?: LeadScore | undefined;
};

/**
 * Describes the message evs.v1.GetScoreResponse.
 * Use `create(GetScoreResponseSchema)` to create a new message.
 */
export const GetScoreResponseSchema: GenMessage<GetScoreResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 3);

/**
 * @generated from message evs.v1.BatchScoreRequest
 */
export type BatchScoreRequest = Message<"evs.v1.BatchScoreRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: repeated string lead_ids = 2;
   */
  leadIds: string[];
};

/**
 * Describes the message evs.v1.BatchScoreRequest.
 * Use `create(BatchScoreRequestSchema)` to create a new message.
 */
export const BatchScoreRequestSchema: GenMessage<BatchScoreRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 4);

/**
 * @generated from message evs.v1.BatchScoreResponse
 */
export type BatchScoreResponse = Message<"evs.v1.BatchScoreResponse"> & {
  /**
   * @generated from field: repeated evs.v1.LeadScore scores = 1;
   */
  scores: LeadScore[];
};

/**
 * Describes the message evs.v1.BatchScoreResponse.
 * Use `create(BatchScoreResponseSchema)` to create a new message.
 */
export const BatchScoreResponseSchema: GenMessage<BatchScoreResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 5);

/**
 * @generated from message evs.v1.LeadScore
 */
export type LeadScore = Message<"evs.v1.LeadScore"> & {
  /**
   * @generated from field: string lead_id = 1;
   */
  leadId: string;

  /**
   * @generated from field: double score = 2;
   */
  score: number;

  /**
   * @generated from field: string band = 3;
   */
  band: string;

  /**
   * @generated from field: map<string, double> feature_weights = 4;
   */
  featureWeights: { [key: string]: number };

  /**
   * @generated from field: google.protobuf.Timestamp scored_at = 5;
   */
  scoredAt?: Timestamp | undefined;
};

/**
 * Describes the message evs.v1.LeadScore.
 * Use `create(LeadScoreSchema)` to create a new message.
 */
export const LeadScoreSchema: GenMessage<LeadScore> = /*@__PURE__*/
  messageDesc(file_evs_v1_scoring, 6);

/**
 * @generated from service evs.v1.ScoringService
 */
export const ScoringService: GenService<{
  /**
   * @generated from rpc evs.v1.ScoringService.ScoreLead
   */
  scoreLead: {
    methodKind: "unary";
    input: typeof ScoreLeadRequestSchema;
    output: typeof ScoreLeadResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.ScoringService.GetScore
   */
  getScore: {
    methodKind: "unary";
    input: typeof GetScoreRequestSchema;
    output: typeof GetScoreResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.ScoringService.BatchScore
   */
  batchScore: {
    methodKind: "unary";
    input: typeof BatchScoreRequestSchema;
    output: typeof BatchScoreResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_scoring, 0);

