// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/site_visit.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelVisitRequest, CancelVisitResponse, CompleteVisitRequest, CompleteVisitResponse, ListVisitsRequest, ListVisitsResponse, RescheduleVisitRequest, RescheduleVisitResponse, ScheduleVisitRequest, ScheduleVisitResponse } from "./site_visit_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.SiteVisitService
 */
export const SiteVisitService = {
  typeName: "evs.v1.SiteVisitService",
  methods: {
    /**
     * @generated from rpc evs.v1.SiteVisitService.ScheduleVisit
     */
    scheduleVisit: {
      name: "ScheduleVisit",
      I: ScheduleVisitRequest,
      O: ScheduleVisitResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SiteVisitService.RescheduleVisit
     */
    rescheduleVisit: {
      name: "RescheduleVisit",
      I: RescheduleVisitRequest,
      O: RescheduleVisitResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SiteVisitService.CancelVisit
     */
    cancelVisit: {
      name: "CancelVisit",
      I: CancelVisitRequest,
      O: CancelVisitResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SiteVisitService.CompleteVisit
     */
    completeVisit: {
      name: "CompleteVisit",
      I: CompleteVisitRequest,
      O: CompleteVisitResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.SiteVisitService.ListVisits
     */
    listVisits: {
      name: "ListVisits",
      I: ListVisitsRequest,
      O: ListVisitsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

