// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/telephony.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCallRequest, GetCallResponse, HandleProviderWebhookRequest, HandleProviderWebhookResponse, HangupCallRequest, HangupCallResponse, ListCallsRequest, ListCallsResponse, PlaceCallRequest, PlaceCallResponse } from "./telephony_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.TelephonyService
 */
export const TelephonyService = {
  typeName: "evs.v1.TelephonyService",
  methods: {
    /**
     * @generated from rpc evs.v1.TelephonyService.PlaceCall
     */
    placeCall: {
      name: "PlaceCall",
      I: PlaceCallRequest,
      O: PlaceCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TelephonyService.HangupCall
     */
    hangupCall: {
      name: "HangupCall",
      I: HangupCallRequest,
      O: HangupCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TelephonyService.GetCall
     */
    getCall: {
      name: "GetCall",
      I: GetCallRequest,
      O: GetCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TelephonyService.ListCalls
     */
    listCalls: {
      name: "ListCalls",
      I: ListCallsRequest,
      O: ListCallsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TelephonyService.HandleProviderWebhook
     */
    handleProviderWebhook: {
      name: "HandleProviderWebhook",
      I: HandleProviderWebhookRequest,
      O: HandleProviderWebhookResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

