// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/telephony.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { CallSession, PageRequest, PageResponse } from "./common_pb";
import { file_evs_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/telephony.proto.
 */
export const file_evs_v1_telephony: GenFile = /*@__PURE__*/
  fileDesc("ChZldnMvdjEvdGVsZXBob255LnByb3RvEgZldnMudjEicgoQUGxhY2VDYWxsUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSEgoKY29udGFjdF9pZBgCIAEoCRIRCglmcm9tX2UxNjQYAyABKAkSDwoHdG9fZTE2NBgEIAEoCRITCgtjYW1wYWlnbl9pZBgFIAEoCSI2ChFQbGFjZUNhbGxSZXNwb25zZRIhCgRjYWxsGAEgASgLMhMuZXZzLnYxLkNhbGxTZXNzaW9uIjcKEUhhbmd1cENhbGxSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIPCgdjYWxsX2lkGAIgASgJIhQKEkhhbmd1cENhbGxSZXNwb25zZSI0Cg5HZXRDYWxsUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSDwoHY2FsbF9pZBgCIAEoCSI0Cg9HZXRDYWxsUmVzcG9uc2USIQoEY2FsbBgBIAEoCzITLmV2cy52MS5DYWxsU2Vzc2lvbiJIChBMaXN0Q2FsbHNSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRIhCgRwYWdlGAIgASgLMhMuZXZzLnYxLlBhZ2VSZXF1ZXN0IlsKEUxpc3RDYWxsc1Jlc3BvbnNlEiIKBWNhbGxzGAEgAygLMhMuZXZzLnYxLkNhbGxTZXNzaW9uEiIKBHBhZ2UYAiABKAsyFC5ldnMudjEuUGFnZVJlc3BvbnNlIrIBChxIYW5kbGVQcm92aWRlcldlYmhvb2tSZXF1ZXN0EhAKCHByb3ZpZGVyGAEgASgJEgwKBGJvZHkYAiABKAwSQgoHaGVhZGVycxgDIAMoCzIxLmV2cy52MS5IYW5kbGVQcm92aWRlcldlYmhvb2tSZXF1ZXN0LkhlYWRlcnNFbnRyeRouCgxIZWFkZXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIfCh1IYW5kbGVQcm92aWRlcldlYmhvb2tSZXNwb25zZTL9AgoQVGVsZXBob255U2VydmljZRJACglQbGFjZUNhbGwSGC5ldnMudjEuUGxhY2VDYWxsUmVxdWVzdBoZLmV2cy52MS5QbGFjZUNhbGxSZXNwb25zZRJDCgpIYW5ndXBDYWxsEhkuZXZzLnYxLkhhbmd1cENhbGxSZXF1ZXN0GhouZXZzLnYxLkhhbmd1cENhbGxSZXNwb25zZRI6CgdHZXRDYWxsEhYuZXZzLnYxLkdldENhbGxSZXF1ZXN0GhcuZXZzLnYxLkdldENhbGxSZXNwb25zZRJACglMaXN0Q2FsbHMSGC5ldnMudjEuTGlzdENhbGxzUmVxdWVzdBoZLmV2cy52MS5MaXN0Q2FsbHNSZXNwb25zZRJkChVIYW5kbGVQcm92aWRlcldlYmhvb2sSJC5ldnMudjEuSGFuZGxlUHJvdmlkZXJXZWJob29rUmVxdWVzdBolLmV2cy52MS5IYW5kbGVQcm92aWRlcldlYmhvb2tSZXNwb25zZUJ+Cgpjb20uZXZzLnYxQg5UZWxlcGhvbnlQcm90b1ABWidnaXRodWIuY29tL2xlYWQvbGlicy9nby9wYi9ldnMvdjE7ZXZzdjGiAgNFWFiqAgZFdnMuVjHKAgZFdnNcVjHiAhJFdnNcVjFcR1BCTWV0YWRhdGHqAgdFdnM6OlYxYgZwcm90bzM", [file_evs_v1_common]);

/**
 * @generated from message evs.v1.PlaceCallRequest
 */
export type PlaceCallRequest = Message<"evs.v1.PlaceCallRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string from_e164 = 3;
   */
  fromE164: string;

  /**
   * @generated from field: string to_e164 = 4;
   */
  toE164: string;

  /**
   * @generated from field: string campaign_id = 5;
   */
  campaignId: string;
};

/**
 * Describes the message evs.v1.PlaceCallRequest.
 * Use `create(PlaceCallRequestSchema)` to create a new message.
 */
export const PlaceCallRequestSchema: GenMessage<PlaceCallRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 0);

/**
 * @generated from message evs.v1.PlaceCallResponse
 */
export type PlaceCallResponse = Message<"evs.v1.PlaceCallResponse"> & {
  /**
   * @generated from field: evs.v1.CallSession call = 1;
   */
  call?: CallSession | undefined;
};

/**
 * Describes the message evs.v1.PlaceCallResponse.
 * Use `create(PlaceCallResponseSchema)` to create a new message.
 */
export const PlaceCallResponseSchema: GenMessage<PlaceCallResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 1);

/**
 * @generated from message evs.v1.HangupCallRequest
 */
export type HangupCallRequest = Message<"evs.v1.HangupCallRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string call_id = 2;
   */
  callId: string;
};

/**
 * Describes the message evs.v1.HangupCallRequest.
 * Use `create(HangupCallRequestSchema)` to create a new message.
 */
export const HangupCallRequestSchema: GenMessage<HangupCallRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 2);

/**
 * @generated from message evs.v1.HangupCallResponse
 */
export type HangupCallResponse = Message<"evs.v1.HangupCallResponse"> & {
};

/**
 * Describes the message evs.v1.HangupCallResponse.
 * Use `create(HangupCallResponseSchema)` to create a new message.
 */
export const HangupCallResponseSchema: GenMessage<HangupCallResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 3);

/**
 * @generated from message evs.v1.GetCallRequest
 */
export type GetCallRequest = Message<"evs.v1.GetCallRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string call_id = 2;
   */
  callId: string;
};

/**
 * Describes the message evs.v1.GetCallRequest.
 * Use `create(GetCallRequestSchema)` to create a new message.
 */
export const GetCallRequestSchema: GenMessage<GetCallRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 4);

/**
 * @generated from message evs.v1.GetCallResponse
 */
export type GetCallResponse = Message<"evs.v1.GetCallResponse"> & {
  /**
   * @generated from field: evs.v1.CallSession call = 1;
   */
  call?: CallSession | undefined;
};

/**
 * Describes the message evs.v1.GetCallResponse.
 * Use `create(GetCallResponseSchema)` to create a new message.
 */
export const GetCallResponseSchema: GenMessage<GetCallResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 5);

/**
 * @generated from message evs.v1.ListCallsRequest
 */
export type ListCallsRequest = Message<"evs.v1.ListCallsRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: evs.v1.PageRequest page = 2;
   */
  page?: PageRequest | undefined;
};

/**
 * Describes the message evs.v1.ListCallsRequest.
 * Use `create(ListCallsRequestSchema)` to create a new message.
 */
export const ListCallsRequestSchema: GenMessage<ListCallsRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 6);

/**
 * @generated from message evs.v1.ListCallsResponse
 */
export type ListCallsResponse = Message<"evs.v1.ListCallsResponse"> & {
  /**
   * @generated from field: repeated evs.v1.CallSession calls = 1;
   */
  calls: CallSession[];

  /**
   * @generated from field: evs.v1.PageResponse page = 2;
   */
  page?: PageResponse | undefined;
};

/**
 * Describes the message evs.v1.ListCallsResponse.
 * Use `create(ListCallsResponseSchema)` to create a new message.
 */
export const ListCallsResponseSchema: GenMessage<ListCallsResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 7);

/**
 * @generated from message evs.v1.HandleProviderWebhookRequest
 */
export type HandleProviderWebhookRequest = Message<"evs.v1.HandleProviderWebhookRequest"> & {
  /**
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from field: bytes body = 2;
   */
  body: Uint8Array;

  /**
   * @generated from field: map<string, string> headers = 3;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message evs.v1.HandleProviderWebhookRequest.
 * Use `create(HandleProviderWebhookRequestSchema)` to create a new message.
 */
export const HandleProviderWebhookRequestSchema: GenMessage<HandleProviderWebhookRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 8);

/**
 * @generated from message evs.v1.HandleProviderWebhookResponse
 */
export type HandleProviderWebhookResponse = Message<"evs.v1.HandleProviderWebhookResponse"> & {
};

/**
 * Describes the message evs.v1.HandleProviderWebhookResponse.
 * Use `create(HandleProviderWebhookResponseSchema)` to create a new message.
 */
export const HandleProviderWebhookResponseSchema: GenMessage<HandleProviderWebhookResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_telephony, 9);

/**
 * @generated from service evs.v1.TelephonyService
 */
export const TelephonyService: GenService<{
  /**
   * @generated from rpc evs.v1.TelephonyService.PlaceCall
   */
  placeCall: {
    methodKind: "unary";
    input: typeof PlaceCallRequestSchema;
    output: typeof PlaceCallResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.TelephonyService.HangupCall
   */
  hangupCall: {
    methodKind: "unary";
    input: typeof HangupCallRequestSchema;
    output: typeof HangupCallResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.TelephonyService.GetCall
   */
  getCall: {
    methodKind: "unary";
    input: typeof GetCallRequestSchema;
    output: typeof GetCallResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.TelephonyService.ListCalls
   */
  listCalls: {
    methodKind: "unary";
    input: typeof ListCallsRequestSchema;
    output: typeof ListCallsResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.TelephonyService.HandleProviderWebhook
   */
  handleProviderWebhook: {
    methodKind: "unary";
    input: typeof HandleProviderWebhookRequestSchema;
    output: typeof HandleProviderWebhookResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_telephony, 0);

