// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/tenant_auth.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTenantRequest, CreateTenantResponse, CreateUserRequest, CreateUserResponse, GetTenantRequest, GetTenantResponse, IssueTokenRequest, IssueTokenResponse, VerifyTokenRequest, VerifyTokenResponse } from "./tenant_auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.TenantAuthService
 */
export const TenantAuthService = {
  typeName: "evs.v1.TenantAuthService",
  methods: {
    /**
     * @generated from rpc evs.v1.TenantAuthService.CreateTenant
     */
    createTenant: {
      name: "CreateTenant",
      I: CreateTenantRequest,
      O: CreateTenantResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TenantAuthService.GetTenant
     */
    getTenant: {
      name: "GetTenant",
      I: GetTenantRequest,
      O: GetTenantResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TenantAuthService.IssueToken
     */
    issueToken: {
      name: "IssueToken",
      I: IssueTokenRequest,
      O: IssueTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TenantAuthService.VerifyToken
     */
    verifyToken: {
      name: "VerifyToken",
      I: VerifyTokenRequest,
      O: VerifyTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TenantAuthService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

