// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/tts_router.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/tts_router.proto.
 */
export const file_evs_v1_tts_router: GenFile = /*@__PURE__*/
  fileDesc("ChdldnMvdjEvdHRzX3JvdXRlci5wcm90bxIGZXZzLnYxIooBChFTeW50aGVzaXplUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSDAoEdGV4dBgCIAEoCRIQCgh2b2ljZV9pZBgDIAEoCRIVCg1sYW5ndWFnZV9jb2RlGAQgASgJEhUKDXByb3ZpZGVyX2hpbnQYBSABKAkSFAoMYXVkaW9fZm9ybWF0GAYgASgJIlAKElN5bnRoZXNpemVSZXNwb25zZRINCgVhdWRpbxgBIAEoDBIVCg1wcm92aWRlcl91c2VkGAIgASgJEhQKDGF1ZGlvX2Zvcm1hdBgDIAEoCSJ6ChdTdHJlYW1TeW50aGVzaXplUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSDAoEdGV4dBgCIAEoCRIQCgh2b2ljZV9pZBgDIAEoCRIVCg1sYW5ndWFnZV9jb2RlGAQgASgJEhUKDXByb3ZpZGVyX2hpbnQYBSABKAkiQQoYU3RyZWFtU3ludGhlc2l6ZVJlc3BvbnNlEhMKC2F1ZGlvX2NodW5rGAEgASgMEhAKCGlzX2ZpbmFsGAIgASgIMrABChBUdHNSb3V0ZXJTZXJ2aWNlEkMKClN5bnRoZXNpemUSGS5ldnMudjEuU3ludGhlc2l6ZVJlcXVlc3QaGi5ldnMudjEuU3ludGhlc2l6ZVJlc3BvbnNlElcKEFN0cmVhbVN5bnRoZXNpemUSHy5ldnMudjEuU3RyZWFtU3ludGhlc2l6ZVJlcXVlc3QaIC5ldnMudjEuU3RyZWFtU3ludGhlc2l6ZVJlc3BvbnNlMAFCfgoKY29tLmV2cy52MUIOVHRzUm91dGVyUHJvdG9QAVonZ2l0aHViLmNvbS9sZWFkL2xpYnMvZ28vcGIvZXZzL3YxO2V2c3YxogIDRVhYqgIGRXZzLlYxygIGRXZzXFYx4gISRXZzXFYxXEdQQk1ldGFkYXRh6gIHRXZzOjpWMWIGcHJvdG8z");

/**
 * @generated from message evs.v1.SynthesizeRequest
 */
export type SynthesizeRequest = Message<"evs.v1.SynthesizeRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * @generated from field: string voice_id = 3;
   */
  voiceId: string;

  /**
   * @generated from field: string language_code = 4;
   */
  languageCode: string;

  /**
   * @generated from field: string provider_hint = 5;
   */
  providerHint: string;

  /**
   * @generated from field: string audio_format = 6;
   */
  audioFormat: string;
};

/**
 * Describes the message evs.v1.SynthesizeRequest.
 * Use `create(SynthesizeRequestSchema)` to create a new message.
 */
export const SynthesizeRequestSchema: GenMessage<SynthesizeRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_tts_router, 0);

/**
 * @generated from message evs.v1.SynthesizeResponse
 */
export type SynthesizeResponse = Message<"evs.v1.SynthesizeResponse"> & {
  /**
   * @generated from field: bytes audio = 1;
   */
  audio: Uint8Array;

  /**
   * @generated from field: string provider_used = 2;
   */
  providerUsed: string;

  /**
   * @generated from field: string audio_format = 3;
   */
  audioFormat: string;
};

/**
 * Describes the message evs.v1.SynthesizeResponse.
 * Use `create(SynthesizeResponseSchema)` to create a new message.
 */
export const SynthesizeResponseSchema: GenMessage<SynthesizeResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_tts_router, 1);

/**
 * @generated from message evs.v1.StreamSynthesizeRequest
 */
export type StreamSynthesizeRequest = Message<"evs.v1.StreamSynthesizeRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * @generated from field: string voice_id = 3;
   */
  voiceId: string;

  /**
   * @generated from field: string language_code = 4;
   */
  languageCode: string;

  /**
   * @generated from field: string provider_hint = 5;
   */
  providerHint: string;
};

/**
 * Describes the message evs.v1.StreamSynthesizeRequest.
 * Use `create(StreamSynthesizeRequestSchema)` to create a new message.
 */
export const StreamSynthesizeRequestSchema: GenMessage<StreamSynthesizeRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_tts_router, 2);

/**
 * @generated from message evs.v1.StreamSynthesizeResponse
 */
export type StreamSynthesizeResponse = Message<"evs.v1.StreamSynthesizeResponse"> & {
  /**
   * @generated from field: bytes audio_chunk = 1;
   */
  audioChunk: Uint8Array;

  /**
   * @generated from field: bool is_final = 2;
   */
  isFinal: boolean;
};

/**
 * Describes the message evs.v1.StreamSynthesizeResponse.
 * Use `create(StreamSynthesizeResponseSchema)` to create a new message.
 */
export const StreamSynthesizeResponseSchema: GenMessage<StreamSynthesizeResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_tts_router, 3);

/**
 * @generated from service evs.v1.TtsRouterService
 */
export const TtsRouterService: GenService<{
  /**
   * @generated from rpc evs.v1.TtsRouterService.Synthesize
   */
  synthesize: {
    methodKind: "unary";
    input: typeof SynthesizeRequestSchema;
    output: typeof SynthesizeResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.TtsRouterService.StreamSynthesize
   */
  streamSynthesize: {
    methodKind: "server_streaming";
    input: typeof StreamSynthesizeRequestSchema;
    output: typeof StreamSynthesizeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_tts_router, 0);

