// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/tts_router.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StreamSynthesizeRequest, StreamSynthesizeResponse, SynthesizeRequest, SynthesizeResponse } from "./tts_router_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.TtsRouterService
 */
export const TtsRouterService = {
  typeName: "evs.v1.TtsRouterService",
  methods: {
    /**
     * @generated from rpc evs.v1.TtsRouterService.Synthesize
     */
    synthesize: {
      name: "Synthesize",
      I: SynthesizeRequest,
      O: SynthesizeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.TtsRouterService.StreamSynthesize
     */
    streamSynthesize: {
      name: "StreamSynthesize",
      I: StreamSynthesizeRequest,
      O: StreamSynthesizeResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

