// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file evs/v1/whatsapp.proto (package evs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PageRequest, PageResponse, WhatsAppMessage } from "./common_pb";
import { file_evs_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file evs/v1/whatsapp.proto.
 */
export const file_evs_v1_whatsapp: GenFile = /*@__PURE__*/
  fileDesc("ChVldnMvdjEvd2hhdHNhcHAucHJvdG8SBmV2cy52MSJJChJTZW5kTWVzc2FnZVJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEhIKCmNvbnRhY3RfaWQYAiABKAkSDAoEdGV4dBgDIAEoCSI/ChNTZW5kTWVzc2FnZVJlc3BvbnNlEigKB21lc3NhZ2UYASABKAsyFy5ldnMudjEuV2hhdHNBcHBNZXNzYWdlIrsBChNTZW5kVGVtcGxhdGVSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCRISCgpjb250YWN0X2lkGAIgASgJEhUKDXRlbXBsYXRlX25hbWUYAyABKAkSNwoGcGFyYW1zGAQgAygLMicuZXZzLnYxLlNlbmRUZW1wbGF0ZVJlcXVlc3QuUGFyYW1zRW50cnkaLQoLUGFyYW1zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJAChRTZW5kVGVtcGxhdGVSZXNwb25zZRIoCgdtZXNzYWdlGAEgASgLMhcuZXZzLnYxLldoYXRzQXBwTWVzc2FnZSKQAQoUSGFuZGxlSW5ib3VuZFJlcXVlc3QSDAoEYm9keRgBIAEoDBI6CgdoZWFkZXJzGAIgAygLMikuZXZzLnYxLkhhbmRsZUluYm91bmRSZXF1ZXN0LkhlYWRlcnNFbnRyeRouCgxIZWFkZXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASIXChVIYW5kbGVJbmJvdW5kUmVzcG9uc2UiXwoTTGlzdE1lc3NhZ2VzUmVxdWVzdBIRCgl0ZW5hbnRfaWQYASABKAkSEgoKY29udGFjdF9pZBgCIAEoCRIhCgRwYWdlGAMgASgLMhMuZXZzLnYxLlBhZ2VSZXF1ZXN0ImUKFExpc3RNZXNzYWdlc1Jlc3BvbnNlEikKCG1lc3NhZ2VzGAEgAygLMhcuZXZzLnYxLldoYXRzQXBwTWVzc2FnZRIiCgRwYWdlGAIgASgLMhQuZXZzLnYxLlBhZ2VSZXNwb25zZTK9AgoPV2hhdHNBcHBTZXJ2aWNlEkYKC1NlbmRNZXNzYWdlEhouZXZzLnYxLlNlbmRNZXNzYWdlUmVxdWVzdBobLmV2cy52MS5TZW5kTWVzc2FnZVJlc3BvbnNlEkkKDFNlbmRUZW1wbGF0ZRIbLmV2cy52MS5TZW5kVGVtcGxhdGVSZXF1ZXN0GhwuZXZzLnYxLlNlbmRUZW1wbGF0ZVJlc3BvbnNlEkwKDUhhbmRsZUluYm91bmQSHC5ldnMudjEuSGFuZGxlSW5ib3VuZFJlcXVlc3QaHS5ldnMudjEuSGFuZGxlSW5ib3VuZFJlc3BvbnNlEkkKDExpc3RNZXNzYWdlcxIbLmV2cy52MS5MaXN0TWVzc2FnZXNSZXF1ZXN0GhwuZXZzLnYxLkxpc3RNZXNzYWdlc1Jlc3BvbnNlQn0KCmNvbS5ldnMudjFCDVdoYXRzYXBwUHJvdG9QAVonZ2l0aHViLmNvbS9sZWFkL2xpYnMvZ28vcGIvZXZzL3YxO2V2c3YxogIDRVhYqgIGRXZzLlYxygIGRXZzXFYx4gISRXZzXFYxXEdQQk1ldGFkYXRh6gIHRXZzOjpWMWIGcHJvdG8z", [file_evs_v1_common]);

/**
 * @generated from message evs.v1.SendMessageRequest
 */
export type SendMessageRequest = Message<"evs.v1.SendMessageRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string text = 3;
   */
  text: string;
};

/**
 * Describes the message evs.v1.SendMessageRequest.
 * Use `create(SendMessageRequestSchema)` to create a new message.
 */
export const SendMessageRequestSchema: GenMessage<SendMessageRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 0);

/**
 * @generated from message evs.v1.SendMessageResponse
 */
export type SendMessageResponse = Message<"evs.v1.SendMessageResponse"> & {
  /**
   * @generated from field: evs.v1.WhatsAppMessage message = 1;
   */
  message?: WhatsAppMessage | undefined;
};

/**
 * Describes the message evs.v1.SendMessageResponse.
 * Use `create(SendMessageResponseSchema)` to create a new message.
 */
export const SendMessageResponseSchema: GenMessage<SendMessageResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 1);

/**
 * @generated from message evs.v1.SendTemplateRequest
 */
export type SendTemplateRequest = Message<"evs.v1.SendTemplateRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: string template_name = 3;
   */
  templateName: string;

  /**
   * @generated from field: map<string, string> params = 4;
   */
  params: { [key: string]: string };
};

/**
 * Describes the message evs.v1.SendTemplateRequest.
 * Use `create(SendTemplateRequestSchema)` to create a new message.
 */
export const SendTemplateRequestSchema: GenMessage<SendTemplateRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 2);

/**
 * @generated from message evs.v1.SendTemplateResponse
 */
export type SendTemplateResponse = Message<"evs.v1.SendTemplateResponse"> & {
  /**
   * @generated from field: evs.v1.WhatsAppMessage message = 1;
   */
  message?: WhatsAppMessage | undefined;
};

/**
 * Describes the message evs.v1.SendTemplateResponse.
 * Use `create(SendTemplateResponseSchema)` to create a new message.
 */
export const SendTemplateResponseSchema: GenMessage<SendTemplateResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 3);

/**
 * @generated from message evs.v1.HandleInboundRequest
 */
export type HandleInboundRequest = Message<"evs.v1.HandleInboundRequest"> & {
  /**
   * @generated from field: bytes body = 1;
   */
  body: Uint8Array;

  /**
   * @generated from field: map<string, string> headers = 2;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message evs.v1.HandleInboundRequest.
 * Use `create(HandleInboundRequestSchema)` to create a new message.
 */
export const HandleInboundRequestSchema: GenMessage<HandleInboundRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 4);

/**
 * @generated from message evs.v1.HandleInboundResponse
 */
export type HandleInboundResponse = Message<"evs.v1.HandleInboundResponse"> & {
};

/**
 * Describes the message evs.v1.HandleInboundResponse.
 * Use `create(HandleInboundResponseSchema)` to create a new message.
 */
export const HandleInboundResponseSchema: GenMessage<HandleInboundResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 5);

/**
 * @generated from message evs.v1.ListMessagesRequest
 */
export type ListMessagesRequest = Message<"evs.v1.ListMessagesRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: string contact_id = 2;
   */
  contactId: string;

  /**
   * @generated from field: evs.v1.PageRequest page = 3;
   */
  page?: PageRequest | undefined;
};

/**
 * Describes the message evs.v1.ListMessagesRequest.
 * Use `create(ListMessagesRequestSchema)` to create a new message.
 */
export const ListMessagesRequestSchema: GenMessage<ListMessagesRequest> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 6);

/**
 * @generated from message evs.v1.ListMessagesResponse
 */
export type ListMessagesResponse = Message<"evs.v1.ListMessagesResponse"> & {
  /**
   * @generated from field: repeated evs.v1.WhatsAppMessage messages = 1;
   */
  messages: WhatsAppMessage[];

  /**
   * @generated from field: evs.v1.PageResponse page = 2;
   */
  page?: PageResponse | undefined;
};

/**
 * Describes the message evs.v1.ListMessagesResponse.
 * Use `create(ListMessagesResponseSchema)` to create a new message.
 */
export const ListMessagesResponseSchema: GenMessage<ListMessagesResponse> = /*@__PURE__*/
  messageDesc(file_evs_v1_whatsapp, 7);

/**
 * @generated from service evs.v1.WhatsAppService
 */
export const WhatsAppService: GenService<{
  /**
   * @generated from rpc evs.v1.WhatsAppService.SendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof SendMessageRequestSchema;
    output: typeof SendMessageResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.WhatsAppService.SendTemplate
   */
  sendTemplate: {
    methodKind: "unary";
    input: typeof SendTemplateRequestSchema;
    output: typeof SendTemplateResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.WhatsAppService.HandleInbound
   */
  handleInbound: {
    methodKind: "unary";
    input: typeof HandleInboundRequestSchema;
    output: typeof HandleInboundResponseSchema;
  },
  /**
   * @generated from rpc evs.v1.WhatsAppService.ListMessages
   */
  listMessages: {
    methodKind: "unary";
    input: typeof ListMessagesRequestSchema;
    output: typeof ListMessagesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_evs_v1_whatsapp, 0);

