// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evs/v1/whatsapp.proto (package evs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HandleInboundRequest, HandleInboundResponse, ListMessagesRequest, ListMessagesResponse, SendMessageRequest, SendMessageResponse, SendTemplateRequest, SendTemplateResponse } from "./whatsapp_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evs.v1.WhatsAppService
 */
export const WhatsAppService = {
  typeName: "evs.v1.WhatsAppService",
  methods: {
    /**
     * @generated from rpc evs.v1.WhatsAppService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: SendMessageRequest,
      O: SendMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.WhatsAppService.SendTemplate
     */
    sendTemplate: {
      name: "SendTemplate",
      I: SendTemplateRequest,
      O: SendTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.WhatsAppService.HandleInbound
     */
    handleInbound: {
      name: "HandleInbound",
      I: HandleInboundRequest,
      O: HandleInboundResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evs.v1.WhatsAppService.ListMessages
     */
    listMessages: {
      name: "ListMessages",
      I: ListMessagesRequest,
      O: ListMessagesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

