// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/billing.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_evs_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetUsageRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *GetUsageRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type GetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*UsageLine           `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Total         *Money                 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageResponse) Reset() {
	*x = GetUsageResponse{}
	mi := &file_evs_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageResponse) ProtoMessage() {}

func (x *GetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageResponse.ProtoReflect.Descriptor instead.
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsageResponse) GetLines() []*UsageLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *GetUsageResponse) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

type UsageLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Cost          *Money                 `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageLine) Reset() {
	*x = UsageLine{}
	mi := &file_evs_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageLine) ProtoMessage() {}

func (x *UsageLine) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageLine.ProtoReflect.Descriptor instead.
func (*UsageLine) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *UsageLine) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UsageLine) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UsageLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UsageLine) GetCost() *Money {
	if x != nil {
		return x.Cost
	}
	return nil
}

type ListInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_evs_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListInvoicesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListInvoicesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_evs_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *ListInvoicesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_evs_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Invoice) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Invoice) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type RecordUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUsageRequest) Reset() {
	*x = RecordUsageRequest{}
	mi := &file_evs_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageRequest) ProtoMessage() {}

func (x *RecordUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageRequest.ProtoReflect.Descriptor instead.
func (*RecordUsageRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *RecordUsageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordUsageRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RecordUsageRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecordUsageRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type RecordUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUsageResponse) Reset() {
	*x = RecordUsageResponse{}
	mi := &file_evs_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageResponse) ProtoMessage() {}

func (x *RecordUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageResponse.ProtoReflect.Descriptor instead.
func (*RecordUsageResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_billing_proto_rawDescGZIP(), []int{7}
}

var File_evs_v1_billing_proto protoreflect.FileDescriptor

const file_evs_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x14evs/v1/billing.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\x0fGetUsageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"`\n" +
	"\x10GetUsageResponse\x12'\n" +
	"\x05lines\x18\x01 \x03(\v2\x11.evs.v1.UsageLineR\x05lines\x12#\n" +
	"\x05total\x18\x02 \x01(\v2\r.evs.v1.MoneyR\x05total\"z\n" +
	"\tUsageLine\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12!\n" +
	"\x04cost\x18\x04 \x01(\v2\r.evs.v1.MoneyR\x04cost\"[\n" +
	"\x13ListInvoicesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"m\n" +
	"\x14ListInvoicesResponse\x12+\n" +
	"\binvoices\x18\x01 \x03(\v2\x0f.evs.v1.InvoiceR\binvoices\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page\"\xe1\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12%\n" +
	"\x06amount\x18\x03 \x01(\v2\r.evs.v1.MoneyR\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x121\n" +
	"\x06due_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\"}\n" +
	"\x12RecordUsageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"\x15\n" +
	"\x13RecordUsageResponse2\xe2\x01\n" +
	"\x0eBillingService\x12=\n" +
	"\bGetUsage\x12\x17.evs.v1.GetUsageRequest\x1a\x18.evs.v1.GetUsageResponse\x12I\n" +
	"\fListInvoices\x12\x1b.evs.v1.ListInvoicesRequest\x1a\x1c.evs.v1.ListInvoicesResponse\x12F\n" +
	"\vRecordUsage\x12\x1a.evs.v1.RecordUsageRequest\x1a\x1b.evs.v1.RecordUsageResponseB|\n" +
	"\n" +
	"com.evs.v1B\fBillingProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_billing_proto_rawDescOnce sync.Once
	file_evs_v1_billing_proto_rawDescData []byte
)

func file_evs_v1_billing_proto_rawDescGZIP() []byte {
	file_evs_v1_billing_proto_rawDescOnce.Do(func() {
		file_evs_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_billing_proto_rawDesc), len(file_evs_v1_billing_proto_rawDesc)))
	})
	return file_evs_v1_billing_proto_rawDescData
}

var file_evs_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_evs_v1_billing_proto_goTypes = []any{
	(*GetUsageRequest)(nil),       // 0: evs.v1.GetUsageRequest
	(*GetUsageResponse)(nil),      // 1: evs.v1.GetUsageResponse
	(*UsageLine)(nil),             // 2: evs.v1.UsageLine
	(*ListInvoicesRequest)(nil),   // 3: evs.v1.ListInvoicesRequest
	(*ListInvoicesResponse)(nil),  // 4: evs.v1.ListInvoicesResponse
	(*Invoice)(nil),               // 5: evs.v1.Invoice
	(*RecordUsageRequest)(nil),    // 6: evs.v1.RecordUsageRequest
	(*RecordUsageResponse)(nil),   // 7: evs.v1.RecordUsageResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Money)(nil),                 // 9: evs.v1.Money
	(*PageRequest)(nil),           // 10: evs.v1.PageRequest
	(*PageResponse)(nil),          // 11: evs.v1.PageResponse
}
var file_evs_v1_billing_proto_depIdxs = []int32{
	8,  // 0: evs.v1.GetUsageRequest.period_start:type_name -> google.protobuf.Timestamp
	8,  // 1: evs.v1.GetUsageRequest.period_end:type_name -> google.protobuf.Timestamp
	2,  // 2: evs.v1.GetUsageResponse.lines:type_name -> evs.v1.UsageLine
	9,  // 3: evs.v1.GetUsageResponse.total:type_name -> evs.v1.Money
	9,  // 4: evs.v1.UsageLine.cost:type_name -> evs.v1.Money
	10, // 5: evs.v1.ListInvoicesRequest.page:type_name -> evs.v1.PageRequest
	5,  // 6: evs.v1.ListInvoicesResponse.invoices:type_name -> evs.v1.Invoice
	11, // 7: evs.v1.ListInvoicesResponse.page:type_name -> evs.v1.PageResponse
	9,  // 8: evs.v1.Invoice.amount:type_name -> evs.v1.Money
	8,  // 9: evs.v1.Invoice.issued_at:type_name -> google.protobuf.Timestamp
	8,  // 10: evs.v1.Invoice.due_at:type_name -> google.protobuf.Timestamp
	0,  // 11: evs.v1.BillingService.GetUsage:input_type -> evs.v1.GetUsageRequest
	3,  // 12: evs.v1.BillingService.ListInvoices:input_type -> evs.v1.ListInvoicesRequest
	6,  // 13: evs.v1.BillingService.RecordUsage:input_type -> evs.v1.RecordUsageRequest
	1,  // 14: evs.v1.BillingService.GetUsage:output_type -> evs.v1.GetUsageResponse
	4,  // 15: evs.v1.BillingService.ListInvoices:output_type -> evs.v1.ListInvoicesResponse
	7,  // 16: evs.v1.BillingService.RecordUsage:output_type -> evs.v1.RecordUsageResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_evs_v1_billing_proto_init() }
func file_evs_v1_billing_proto_init() {
	if File_evs_v1_billing_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_billing_proto_rawDesc), len(file_evs_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_billing_proto_goTypes,
		DependencyIndexes: file_evs_v1_billing_proto_depIdxs,
		MessageInfos:      file_evs_v1_billing_proto_msgTypes,
	}.Build()
	File_evs_v1_billing_proto = out.File
	file_evs_v1_billing_proto_goTypes = nil
	file_evs_v1_billing_proto_depIdxs = nil
}
