// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/consent.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Record        *ConsentRecord         `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Actor         *AuditActor            `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordConsentRequest) Reset() {
	*x = RecordConsentRequest{}
	mi := &file_evs_v1_consent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordConsentRequest) ProtoMessage() {}

func (x *RecordConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordConsentRequest.ProtoReflect.Descriptor instead.
func (*RecordConsentRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{0}
}

func (x *RecordConsentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordConsentRequest) GetRecord() *ConsentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RecordConsentRequest) GetActor() *AuditActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type RecordConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ConsentRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordConsentResponse) Reset() {
	*x = RecordConsentResponse{}
	mi := &file_evs_v1_consent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordConsentResponse) ProtoMessage() {}

func (x *RecordConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordConsentResponse.ProtoReflect.Descriptor instead.
func (*RecordConsentResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{1}
}

func (x *RecordConsentResponse) GetRecord() *ConsentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type RevokeConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Actor         *AuditActor            `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentRequest) Reset() {
	*x = RevokeConsentRequest{}
	mi := &file_evs_v1_consent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentRequest) ProtoMessage() {}

func (x *RevokeConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentRequest.ProtoReflect.Descriptor instead.
func (*RevokeConsentRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeConsentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeConsentRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *RevokeConsentRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RevokeConsentRequest) GetActor() *AuditActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type RevokeConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ConsentRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentResponse) Reset() {
	*x = RevokeConsentResponse{}
	mi := &file_evs_v1_consent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentResponse) ProtoMessage() {}

func (x *RevokeConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentResponse.ProtoReflect.Descriptor instead.
func (*RevokeConsentResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeConsentResponse) GetRecord() *ConsentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CheckConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConsentRequest) Reset() {
	*x = CheckConsentRequest{}
	mi := &file_evs_v1_consent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentRequest) ProtoMessage() {}

func (x *CheckConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentRequest.ProtoReflect.Descriptor instead.
func (*CheckConsentRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{4}
}

func (x *CheckConsentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckConsentRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *CheckConsentRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type CheckConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Record        *ConsentRecord         `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConsentResponse) Reset() {
	*x = CheckConsentResponse{}
	mi := &file_evs_v1_consent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentResponse) ProtoMessage() {}

func (x *CheckConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentResponse.ProtoReflect.Descriptor instead.
func (*CheckConsentResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{5}
}

func (x *CheckConsentResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *CheckConsentResponse) GetRecord() *ConsentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsentRequest) Reset() {
	*x = ListConsentRequest{}
	mi := &file_evs_v1_consent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentRequest) ProtoMessage() {}

func (x *ListConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentRequest.ProtoReflect.Descriptor instead.
func (*ListConsentRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{6}
}

func (x *ListConsentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConsentRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *ListConsentRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ConsentRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsentResponse) Reset() {
	*x = ListConsentResponse{}
	mi := &file_evs_v1_consent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentResponse) ProtoMessage() {}

func (x *ListConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_consent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentResponse.ProtoReflect.Descriptor instead.
func (*ListConsentResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_consent_proto_rawDescGZIP(), []int{7}
}

func (x *ListConsentResponse) GetRecords() []*ConsentRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListConsentResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_evs_v1_consent_proto protoreflect.FileDescriptor

const file_evs_v1_consent_proto_rawDesc = "" +
	"\n" +
	"\x14evs/v1/consent.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\"\x8c\x01\n" +
	"\x14RecordConsentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.evs.v1.ConsentRecordR\x06record\x12(\n" +
	"\x05actor\x18\x03 \x01(\v2\x12.evs.v1.AuditActorR\x05actor\"F\n" +
	"\x15RecordConsentResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.evs.v1.ConsentRecordR\x06record\"\x96\x01\n" +
	"\x14RevokeConsentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12(\n" +
	"\x05actor\x18\x04 \x01(\v2\x12.evs.v1.AuditActorR\x05actor\"F\n" +
	"\x15RevokeConsentResponse\x12-\n" +
	"\x06record\x18\x01 \x01(\v2\x15.evs.v1.ConsentRecordR\x06record\"k\n" +
	"\x13CheckConsentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"_\n" +
	"\x14CheckConsentResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.evs.v1.ConsentRecordR\x06record\"y\n" +
	"\x12ListConsentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"p\n" +
	"\x13ListConsentResponse\x12/\n" +
	"\arecords\x18\x01 \x03(\v2\x15.evs.v1.ConsentRecordR\arecords\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page2\xbf\x02\n" +
	"\x0eConsentService\x12L\n" +
	"\rRecordConsent\x12\x1c.evs.v1.RecordConsentRequest\x1a\x1d.evs.v1.RecordConsentResponse\x12L\n" +
	"\rRevokeConsent\x12\x1c.evs.v1.RevokeConsentRequest\x1a\x1d.evs.v1.RevokeConsentResponse\x12I\n" +
	"\fCheckConsent\x12\x1b.evs.v1.CheckConsentRequest\x1a\x1c.evs.v1.CheckConsentResponse\x12F\n" +
	"\vListConsent\x12\x1a.evs.v1.ListConsentRequest\x1a\x1b.evs.v1.ListConsentResponseB|\n" +
	"\n" +
	"com.evs.v1B\fConsentProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_consent_proto_rawDescOnce sync.Once
	file_evs_v1_consent_proto_rawDescData []byte
)

func file_evs_v1_consent_proto_rawDescGZIP() []byte {
	file_evs_v1_consent_proto_rawDescOnce.Do(func() {
		file_evs_v1_consent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_consent_proto_rawDesc), len(file_evs_v1_consent_proto_rawDesc)))
	})
	return file_evs_v1_consent_proto_rawDescData
}

var file_evs_v1_consent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_evs_v1_consent_proto_goTypes = []any{
	(*RecordConsentRequest)(nil),  // 0: evs.v1.RecordConsentRequest
	(*RecordConsentResponse)(nil), // 1: evs.v1.RecordConsentResponse
	(*RevokeConsentRequest)(nil),  // 2: evs.v1.RevokeConsentRequest
	(*RevokeConsentResponse)(nil), // 3: evs.v1.RevokeConsentResponse
	(*CheckConsentRequest)(nil),   // 4: evs.v1.CheckConsentRequest
	(*CheckConsentResponse)(nil),  // 5: evs.v1.CheckConsentResponse
	(*ListConsentRequest)(nil),    // 6: evs.v1.ListConsentRequest
	(*ListConsentResponse)(nil),   // 7: evs.v1.ListConsentResponse
	(*ConsentRecord)(nil),         // 8: evs.v1.ConsentRecord
	(*AuditActor)(nil),            // 9: evs.v1.AuditActor
	(*PageRequest)(nil),           // 10: evs.v1.PageRequest
	(*PageResponse)(nil),          // 11: evs.v1.PageResponse
}
var file_evs_v1_consent_proto_depIdxs = []int32{
	8,  // 0: evs.v1.RecordConsentRequest.record:type_name -> evs.v1.ConsentRecord
	9,  // 1: evs.v1.RecordConsentRequest.actor:type_name -> evs.v1.AuditActor
	8,  // 2: evs.v1.RecordConsentResponse.record:type_name -> evs.v1.ConsentRecord
	9,  // 3: evs.v1.RevokeConsentRequest.actor:type_name -> evs.v1.AuditActor
	8,  // 4: evs.v1.RevokeConsentResponse.record:type_name -> evs.v1.ConsentRecord
	8,  // 5: evs.v1.CheckConsentResponse.record:type_name -> evs.v1.ConsentRecord
	10, // 6: evs.v1.ListConsentRequest.page:type_name -> evs.v1.PageRequest
	8,  // 7: evs.v1.ListConsentResponse.records:type_name -> evs.v1.ConsentRecord
	11, // 8: evs.v1.ListConsentResponse.page:type_name -> evs.v1.PageResponse
	0,  // 9: evs.v1.ConsentService.RecordConsent:input_type -> evs.v1.RecordConsentRequest
	2,  // 10: evs.v1.ConsentService.RevokeConsent:input_type -> evs.v1.RevokeConsentRequest
	4,  // 11: evs.v1.ConsentService.CheckConsent:input_type -> evs.v1.CheckConsentRequest
	6,  // 12: evs.v1.ConsentService.ListConsent:input_type -> evs.v1.ListConsentRequest
	1,  // 13: evs.v1.ConsentService.RecordConsent:output_type -> evs.v1.RecordConsentResponse
	3,  // 14: evs.v1.ConsentService.RevokeConsent:output_type -> evs.v1.RevokeConsentResponse
	5,  // 15: evs.v1.ConsentService.CheckConsent:output_type -> evs.v1.CheckConsentResponse
	7,  // 16: evs.v1.ConsentService.ListConsent:output_type -> evs.v1.ListConsentResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_evs_v1_consent_proto_init() }
func file_evs_v1_consent_proto_init() {
	if File_evs_v1_consent_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_consent_proto_rawDesc), len(file_evs_v1_consent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_consent_proto_goTypes,
		DependencyIndexes: file_evs_v1_consent_proto_depIdxs,
		MessageInfos:      file_evs_v1_consent_proto_msgTypes,
	}.Build()
	File_evs_v1_consent_proto = out.File
	file_evs_v1_consent_proto_goTypes = nil
	file_evs_v1_consent_proto_depIdxs = nil
}
