// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/handoff.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Handoff struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadId         string                 `protobuf:"bytes,3,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Channel        string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	AssignedUserId string                 `protobuf:"bytes,6,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Handoff) Reset() {
	*x = Handoff{}
	mi := &file_evs_v1_handoff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handoff) ProtoMessage() {}

func (x *Handoff) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handoff.ProtoReflect.Descriptor instead.
func (*Handoff) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{0}
}

func (x *Handoff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Handoff) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Handoff) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *Handoff) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Handoff) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Handoff) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *Handoff) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RequestHandoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Handoff       *Handoff               `protobuf:"bytes,2,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHandoffRequest) Reset() {
	*x = RequestHandoffRequest{}
	mi := &file_evs_v1_handoff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHandoffRequest) ProtoMessage() {}

func (x *RequestHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHandoffRequest.ProtoReflect.Descriptor instead.
func (*RequestHandoffRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{1}
}

func (x *RequestHandoffRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestHandoffRequest) GetHandoff() *Handoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

type RequestHandoffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handoff       *Handoff               `protobuf:"bytes,1,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHandoffResponse) Reset() {
	*x = RequestHandoffResponse{}
	mi := &file_evs_v1_handoff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHandoffResponse) ProtoMessage() {}

func (x *RequestHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHandoffResponse.ProtoReflect.Descriptor instead.
func (*RequestHandoffResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{2}
}

func (x *RequestHandoffResponse) GetHandoff() *Handoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

type AssignAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HandoffId     string                 `protobuf:"bytes,2,opt,name=handoff_id,json=handoffId,proto3" json:"handoff_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentRequest) Reset() {
	*x = AssignAgentRequest{}
	mi := &file_evs_v1_handoff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentRequest) ProtoMessage() {}

func (x *AssignAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentRequest.ProtoReflect.Descriptor instead.
func (*AssignAgentRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{3}
}

func (x *AssignAgentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AssignAgentRequest) GetHandoffId() string {
	if x != nil {
		return x.HandoffId
	}
	return ""
}

func (x *AssignAgentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssignAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handoff       *Handoff               `protobuf:"bytes,1,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentResponse) Reset() {
	*x = AssignAgentResponse{}
	mi := &file_evs_v1_handoff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentResponse) ProtoMessage() {}

func (x *AssignAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentResponse.ProtoReflect.Descriptor instead.
func (*AssignAgentResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{4}
}

func (x *AssignAgentResponse) GetHandoff() *Handoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

type CompleteHandoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HandoffId     string                 `protobuf:"bytes,2,opt,name=handoff_id,json=handoffId,proto3" json:"handoff_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandoffRequest) Reset() {
	*x = CompleteHandoffRequest{}
	mi := &file_evs_v1_handoff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandoffRequest) ProtoMessage() {}

func (x *CompleteHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandoffRequest.ProtoReflect.Descriptor instead.
func (*CompleteHandoffRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteHandoffRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompleteHandoffRequest) GetHandoffId() string {
	if x != nil {
		return x.HandoffId
	}
	return ""
}

func (x *CompleteHandoffRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type CompleteHandoffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handoff       *Handoff               `protobuf:"bytes,1,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandoffResponse) Reset() {
	*x = CompleteHandoffResponse{}
	mi := &file_evs_v1_handoff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandoffResponse) ProtoMessage() {}

func (x *CompleteHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandoffResponse.ProtoReflect.Descriptor instead.
func (*CompleteHandoffResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteHandoffResponse) GetHandoff() *Handoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

type GetHandoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HandoffId     string                 `protobuf:"bytes,2,opt,name=handoff_id,json=handoffId,proto3" json:"handoff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandoffRequest) Reset() {
	*x = GetHandoffRequest{}
	mi := &file_evs_v1_handoff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandoffRequest) ProtoMessage() {}

func (x *GetHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandoffRequest.ProtoReflect.Descriptor instead.
func (*GetHandoffRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{7}
}

func (x *GetHandoffRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetHandoffRequest) GetHandoffId() string {
	if x != nil {
		return x.HandoffId
	}
	return ""
}

type GetHandoffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handoff       *Handoff               `protobuf:"bytes,1,opt,name=handoff,proto3" json:"handoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandoffResponse) Reset() {
	*x = GetHandoffResponse{}
	mi := &file_evs_v1_handoff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandoffResponse) ProtoMessage() {}

func (x *GetHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_handoff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandoffResponse.ProtoReflect.Descriptor instead.
func (*GetHandoffResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_handoff_proto_rawDescGZIP(), []int{8}
}

func (x *GetHandoffResponse) GetHandoff() *Handoff {
	if x != nil {
		return x.Handoff
	}
	return nil
}

var File_evs_v1_handoff_proto protoreflect.FileDescriptor

const file_evs_v1_handoff_proto_rawDesc = "" +
	"\n" +
	"\x14evs/v1/handoff.proto\x12\x06evs.v1\"\xc3\x01\n" +
	"\aHandoff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\alead_id\x18\x03 \x01(\tR\x06leadId\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12(\n" +
	"\x10assigned_user_id\x18\x06 \x01(\tR\x0eassignedUserId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"_\n" +
	"\x15RequestHandoffRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12)\n" +
	"\ahandoff\x18\x02 \x01(\v2\x0f.evs.v1.HandoffR\ahandoff\"C\n" +
	"\x16RequestHandoffResponse\x12)\n" +
	"\ahandoff\x18\x01 \x01(\v2\x0f.evs.v1.HandoffR\ahandoff\"i\n" +
	"\x12AssignAgentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"handoff_id\x18\x02 \x01(\tR\thandoffId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"@\n" +
	"\x13AssignAgentResponse\x12)\n" +
	"\ahandoff\x18\x01 \x01(\v2\x0f.evs.v1.HandoffR\ahandoff\"t\n" +
	"\x16CompleteHandoffRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"handoff_id\x18\x02 \x01(\tR\thandoffId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\"D\n" +
	"\x17CompleteHandoffResponse\x12)\n" +
	"\ahandoff\x18\x01 \x01(\v2\x0f.evs.v1.HandoffR\ahandoff\"O\n" +
	"\x11GetHandoffRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"handoff_id\x18\x02 \x01(\tR\thandoffId\"?\n" +
	"\x12GetHandoffResponse\x12)\n" +
	"\ahandoff\x18\x01 \x01(\v2\x0f.evs.v1.HandoffR\ahandoff2\xc2\x02\n" +
	"\x0eHandoffService\x12O\n" +
	"\x0eRequestHandoff\x12\x1d.evs.v1.RequestHandoffRequest\x1a\x1e.evs.v1.RequestHandoffResponse\x12F\n" +
	"\vAssignAgent\x12\x1a.evs.v1.AssignAgentRequest\x1a\x1b.evs.v1.AssignAgentResponse\x12R\n" +
	"\x0fCompleteHandoff\x12\x1e.evs.v1.CompleteHandoffRequest\x1a\x1f.evs.v1.CompleteHandoffResponse\x12C\n" +
	"\n" +
	"GetHandoff\x12\x19.evs.v1.GetHandoffRequest\x1a\x1a.evs.v1.GetHandoffResponseB|\n" +
	"\n" +
	"com.evs.v1B\fHandoffProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_handoff_proto_rawDescOnce sync.Once
	file_evs_v1_handoff_proto_rawDescData []byte
)

func file_evs_v1_handoff_proto_rawDescGZIP() []byte {
	file_evs_v1_handoff_proto_rawDescOnce.Do(func() {
		file_evs_v1_handoff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_handoff_proto_rawDesc), len(file_evs_v1_handoff_proto_rawDesc)))
	})
	return file_evs_v1_handoff_proto_rawDescData
}

var file_evs_v1_handoff_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_evs_v1_handoff_proto_goTypes = []any{
	(*Handoff)(nil),                 // 0: evs.v1.Handoff
	(*RequestHandoffRequest)(nil),   // 1: evs.v1.RequestHandoffRequest
	(*RequestHandoffResponse)(nil),  // 2: evs.v1.RequestHandoffResponse
	(*AssignAgentRequest)(nil),      // 3: evs.v1.AssignAgentRequest
	(*AssignAgentResponse)(nil),     // 4: evs.v1.AssignAgentResponse
	(*CompleteHandoffRequest)(nil),  // 5: evs.v1.CompleteHandoffRequest
	(*CompleteHandoffResponse)(nil), // 6: evs.v1.CompleteHandoffResponse
	(*GetHandoffRequest)(nil),       // 7: evs.v1.GetHandoffRequest
	(*GetHandoffResponse)(nil),      // 8: evs.v1.GetHandoffResponse
}
var file_evs_v1_handoff_proto_depIdxs = []int32{
	0, // 0: evs.v1.RequestHandoffRequest.handoff:type_name -> evs.v1.Handoff
	0, // 1: evs.v1.RequestHandoffResponse.handoff:type_name -> evs.v1.Handoff
	0, // 2: evs.v1.AssignAgentResponse.handoff:type_name -> evs.v1.Handoff
	0, // 3: evs.v1.CompleteHandoffResponse.handoff:type_name -> evs.v1.Handoff
	0, // 4: evs.v1.GetHandoffResponse.handoff:type_name -> evs.v1.Handoff
	1, // 5: evs.v1.HandoffService.RequestHandoff:input_type -> evs.v1.RequestHandoffRequest
	3, // 6: evs.v1.HandoffService.AssignAgent:input_type -> evs.v1.AssignAgentRequest
	5, // 7: evs.v1.HandoffService.CompleteHandoff:input_type -> evs.v1.CompleteHandoffRequest
	7, // 8: evs.v1.HandoffService.GetHandoff:input_type -> evs.v1.GetHandoffRequest
	2, // 9: evs.v1.HandoffService.RequestHandoff:output_type -> evs.v1.RequestHandoffResponse
	4, // 10: evs.v1.HandoffService.AssignAgent:output_type -> evs.v1.AssignAgentResponse
	6, // 11: evs.v1.HandoffService.CompleteHandoff:output_type -> evs.v1.CompleteHandoffResponse
	8, // 12: evs.v1.HandoffService.GetHandoff:output_type -> evs.v1.GetHandoffResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_evs_v1_handoff_proto_init() }
func file_evs_v1_handoff_proto_init() {
	if File_evs_v1_handoff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_handoff_proto_rawDesc), len(file_evs_v1_handoff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_handoff_proto_goTypes,
		DependencyIndexes: file_evs_v1_handoff_proto_depIdxs,
		MessageInfos:      file_evs_v1_handoff_proto_msgTypes,
	}.Build()
	File_evs_v1_handoff_proto = out.File
	file_evs_v1_handoff_proto_goTypes = nil
	file_evs_v1_handoff_proto_depIdxs = nil
}
