// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/lead_import.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportLeadsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Format          string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "csv" | "json"
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	SpacesObjectKey string                 `protobuf:"bytes,5,opt,name=spaces_object_key,json=spacesObjectKey,proto3" json:"spaces_object_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImportLeadsRequest) Reset() {
	*x = ImportLeadsRequest{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLeadsRequest) ProtoMessage() {}

func (x *ImportLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLeadsRequest.ProtoReflect.Descriptor instead.
func (*ImportLeadsRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{0}
}

func (x *ImportLeadsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImportLeadsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ImportLeadsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImportLeadsRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImportLeadsRequest) GetSpacesObjectKey() string {
	if x != nil {
		return x.SpacesObjectKey
	}
	return ""
}

type ImportLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportLeadsResponse) Reset() {
	*x = ImportLeadsResponse{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLeadsResponse) ProtoMessage() {}

func (x *ImportLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLeadsResponse.ProtoReflect.Descriptor instead.
func (*ImportLeadsResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{1}
}

func (x *ImportLeadsResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetImportJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportJobRequest) Reset() {
	*x = GetImportJobRequest{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportJobRequest) ProtoMessage() {}

func (x *GetImportJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportJobRequest.ProtoReflect.Descriptor instead.
func (*GetImportJobRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{2}
}

func (x *GetImportJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetImportJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetImportJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ImportJob             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportJobResponse) Reset() {
	*x = GetImportJobResponse{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportJobResponse) ProtoMessage() {}

func (x *GetImportJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportJobResponse.ProtoReflect.Descriptor instead.
func (*GetImportJobResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{3}
}

func (x *GetImportJobResponse) GetJob() *ImportJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListImportJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportJobsRequest) Reset() {
	*x = ListImportJobsRequest{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportJobsRequest) ProtoMessage() {}

func (x *ListImportJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportJobsRequest.ProtoReflect.Descriptor instead.
func (*ListImportJobsRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{4}
}

func (x *ListImportJobsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListImportJobsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListImportJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ImportJob           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportJobsResponse) Reset() {
	*x = ListImportJobsResponse{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportJobsResponse) ProtoMessage() {}

func (x *ListImportJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportJobsResponse.ProtoReflect.Descriptor instead.
func (*ListImportJobsResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{5}
}

func (x *ListImportJobsResponse) GetJobs() []*ImportJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListImportJobsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ImportJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalRows     int32                  `protobuf:"varint,4,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	Succeeded     int32                  `protobuf:"varint,5,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int32                  `protobuf:"varint,6,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportJob) Reset() {
	*x = ImportJob{}
	mi := &file_evs_v1_lead_import_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportJob) ProtoMessage() {}

func (x *ImportJob) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_import_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportJob.ProtoReflect.Descriptor instead.
func (*ImportJob) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_import_proto_rawDescGZIP(), []int{6}
}

func (x *ImportJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImportJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImportJob) GetTotalRows() int32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ImportJob) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *ImportJob) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ImportJob) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_evs_v1_lead_import_proto protoreflect.FileDescriptor

const file_evs_v1_lead_import_proto_rawDesc = "" +
	"\n" +
	"\x18evs/v1/lead_import.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\"\xa7\x01\n" +
	"\x12ImportLeadsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12*\n" +
	"\x11spaces_object_key\x18\x05 \x01(\tR\x0fspacesObjectKey\",\n" +
	"\x13ImportLeadsResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"I\n" +
	"\x13GetImportJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\";\n" +
	"\x14GetImportJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.evs.v1.ImportJobR\x03job\"]\n" +
	"\x15ListImportJobsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"i\n" +
	"\x16ListImportJobsResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.evs.v1.ImportJobR\x04jobs\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page\"\xbd\x01\n" +
	"\tImportJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x04 \x01(\x05R\ttotalRows\x12\x1c\n" +
	"\tsucceeded\x18\x05 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x06 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\a \x03(\tR\x06errors2\xf7\x01\n" +
	"\x11LeadImportService\x12F\n" +
	"\vImportLeads\x12\x1a.evs.v1.ImportLeadsRequest\x1a\x1b.evs.v1.ImportLeadsResponse\x12I\n" +
	"\fGetImportJob\x12\x1b.evs.v1.GetImportJobRequest\x1a\x1c.evs.v1.GetImportJobResponse\x12O\n" +
	"\x0eListImportJobs\x12\x1d.evs.v1.ListImportJobsRequest\x1a\x1e.evs.v1.ListImportJobsResponseB\x7f\n" +
	"\n" +
	"com.evs.v1B\x0fLeadImportProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_lead_import_proto_rawDescOnce sync.Once
	file_evs_v1_lead_import_proto_rawDescData []byte
)

func file_evs_v1_lead_import_proto_rawDescGZIP() []byte {
	file_evs_v1_lead_import_proto_rawDescOnce.Do(func() {
		file_evs_v1_lead_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_lead_import_proto_rawDesc), len(file_evs_v1_lead_import_proto_rawDesc)))
	})
	return file_evs_v1_lead_import_proto_rawDescData
}

var file_evs_v1_lead_import_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_evs_v1_lead_import_proto_goTypes = []any{
	(*ImportLeadsRequest)(nil),     // 0: evs.v1.ImportLeadsRequest
	(*ImportLeadsResponse)(nil),    // 1: evs.v1.ImportLeadsResponse
	(*GetImportJobRequest)(nil),    // 2: evs.v1.GetImportJobRequest
	(*GetImportJobResponse)(nil),   // 3: evs.v1.GetImportJobResponse
	(*ListImportJobsRequest)(nil),  // 4: evs.v1.ListImportJobsRequest
	(*ListImportJobsResponse)(nil), // 5: evs.v1.ListImportJobsResponse
	(*ImportJob)(nil),              // 6: evs.v1.ImportJob
	(*PageRequest)(nil),            // 7: evs.v1.PageRequest
	(*PageResponse)(nil),           // 8: evs.v1.PageResponse
}
var file_evs_v1_lead_import_proto_depIdxs = []int32{
	6, // 0: evs.v1.GetImportJobResponse.job:type_name -> evs.v1.ImportJob
	7, // 1: evs.v1.ListImportJobsRequest.page:type_name -> evs.v1.PageRequest
	6, // 2: evs.v1.ListImportJobsResponse.jobs:type_name -> evs.v1.ImportJob
	8, // 3: evs.v1.ListImportJobsResponse.page:type_name -> evs.v1.PageResponse
	0, // 4: evs.v1.LeadImportService.ImportLeads:input_type -> evs.v1.ImportLeadsRequest
	2, // 5: evs.v1.LeadImportService.GetImportJob:input_type -> evs.v1.GetImportJobRequest
	4, // 6: evs.v1.LeadImportService.ListImportJobs:input_type -> evs.v1.ListImportJobsRequest
	1, // 7: evs.v1.LeadImportService.ImportLeads:output_type -> evs.v1.ImportLeadsResponse
	3, // 8: evs.v1.LeadImportService.GetImportJob:output_type -> evs.v1.GetImportJobResponse
	5, // 9: evs.v1.LeadImportService.ListImportJobs:output_type -> evs.v1.ListImportJobsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_evs_v1_lead_import_proto_init() }
func file_evs_v1_lead_import_proto_init() {
	if File_evs_v1_lead_import_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_lead_import_proto_rawDesc), len(file_evs_v1_lead_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_lead_import_proto_goTypes,
		DependencyIndexes: file_evs_v1_lead_import_proto_depIdxs,
		MessageInfos:      file_evs_v1_lead_import_proto_msgTypes,
	}.Build()
	File_evs_v1_lead_import_proto = out.File
	file_evs_v1_lead_import_proto_goTypes = nil
	file_evs_v1_lead_import_proto_depIdxs = nil
}
