// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/lead_identity.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Contact       *Contact               `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertContactRequest) Reset() {
	*x = UpsertContactRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertContactRequest) ProtoMessage() {}

func (x *UpsertContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertContactRequest.ProtoReflect.Descriptor instead.
func (*UpsertContactRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertContactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpsertContactRequest) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type UpsertContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertContactResponse) Reset() {
	*x = UpsertContactResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertContactResponse) ProtoMessage() {}

func (x *UpsertContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertContactResponse.ProtoReflect.Descriptor instead.
func (*UpsertContactResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *UpsertContactResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetContactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetContactRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type GetContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactResponse) Reset() {
	*x = GetContactResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactResponse) ProtoMessage() {}

func (x *GetContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactResponse.ProtoReflect.Descriptor instead.
func (*GetContactResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type UpsertLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Lead          *Lead                  `protobuf:"bytes,2,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLeadRequest) Reset() {
	*x = UpsertLeadRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLeadRequest) ProtoMessage() {}

func (x *UpsertLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLeadRequest.ProtoReflect.Descriptor instead.
func (*UpsertLeadRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertLeadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpsertLeadRequest) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type UpsertLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLeadResponse) Reset() {
	*x = UpsertLeadResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLeadResponse) ProtoMessage() {}

func (x *UpsertLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLeadResponse.ProtoReflect.Descriptor instead.
func (*UpsertLeadResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertLeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

func (x *UpsertLeadResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadId        string                 `protobuf:"bytes,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadRequest) Reset() {
	*x = GetLeadRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadRequest) ProtoMessage() {}

func (x *GetLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadRequest.ProtoReflect.Descriptor instead.
func (*GetLeadRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type GetLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadResponse) Reset() {
	*x = GetLeadResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadResponse) ProtoMessage() {}

func (x *GetLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadResponse.ProtoReflect.Descriptor instead.
func (*GetLeadResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type ListLeadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest) Reset() {
	*x = ListLeadsRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest) ProtoMessage() {}

func (x *ListLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeadsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListLeadsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListLeadsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Lead                `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsResponse) Reset() {
	*x = ListLeadsResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsResponse) ProtoMessage() {}

func (x *ListLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{9}
}

func (x *ListLeadsResponse) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

func (x *ListLeadsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type DedupeContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PhoneE164     string                 `protobuf:"bytes,2,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DedupeContactRequest) Reset() {
	*x = DedupeContactRequest{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DedupeContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DedupeContactRequest) ProtoMessage() {}

func (x *DedupeContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DedupeContactRequest.ProtoReflect.Descriptor instead.
func (*DedupeContactRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{10}
}

func (x *DedupeContactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DedupeContactRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *DedupeContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DedupeContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Contact             `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DedupeContactResponse) Reset() {
	*x = DedupeContactResponse{}
	mi := &file_evs_v1_lead_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DedupeContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DedupeContactResponse) ProtoMessage() {}

func (x *DedupeContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_lead_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DedupeContactResponse.ProtoReflect.Descriptor instead.
func (*DedupeContactResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_lead_identity_proto_rawDescGZIP(), []int{11}
}

func (x *DedupeContactResponse) GetMatches() []*Contact {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_evs_v1_lead_identity_proto protoreflect.FileDescriptor

const file_evs_v1_lead_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aevs/v1/lead_identity.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\"^\n" +
	"\x14UpsertContactRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12)\n" +
	"\acontact\x18\x02 \x01(\v2\x0f.evs.v1.ContactR\acontact\"\\\n" +
	"\x15UpsertContactResponse\x12)\n" +
	"\acontact\x18\x01 \x01(\v2\x0f.evs.v1.ContactR\acontact\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"O\n" +
	"\x11GetContactRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\"?\n" +
	"\x12GetContactResponse\x12)\n" +
	"\acontact\x18\x01 \x01(\v2\x0f.evs.v1.ContactR\acontact\"R\n" +
	"\x11UpsertLeadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12 \n" +
	"\x04lead\x18\x02 \x01(\v2\f.evs.v1.LeadR\x04lead\"P\n" +
	"\x12UpsertLeadResponse\x12 \n" +
	"\x04lead\x18\x01 \x01(\v2\f.evs.v1.LeadR\x04lead\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"F\n" +
	"\x0eGetLeadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\alead_id\x18\x02 \x01(\tR\x06leadId\"3\n" +
	"\x0fGetLeadResponse\x12 \n" +
	"\x04lead\x18\x01 \x01(\v2\f.evs.v1.LeadR\x04lead\"p\n" +
	"\x10ListLeadsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x04page\x18\x03 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"a\n" +
	"\x11ListLeadsResponse\x12\"\n" +
	"\x05leads\x18\x01 \x03(\v2\f.evs.v1.LeadR\x05leads\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page\"h\n" +
	"\x14DedupeContactRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x02 \x01(\tR\tphoneE164\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"B\n" +
	"\x15DedupeContactResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.evs.v1.ContactR\amatches2\xb9\x03\n" +
	"\x13LeadIdentityService\x12L\n" +
	"\rUpsertContact\x12\x1c.evs.v1.UpsertContactRequest\x1a\x1d.evs.v1.UpsertContactResponse\x12C\n" +
	"\n" +
	"GetContact\x12\x19.evs.v1.GetContactRequest\x1a\x1a.evs.v1.GetContactResponse\x12C\n" +
	"\n" +
	"UpsertLead\x12\x19.evs.v1.UpsertLeadRequest\x1a\x1a.evs.v1.UpsertLeadResponse\x12:\n" +
	"\aGetLead\x12\x16.evs.v1.GetLeadRequest\x1a\x17.evs.v1.GetLeadResponse\x12@\n" +
	"\tListLeads\x12\x18.evs.v1.ListLeadsRequest\x1a\x19.evs.v1.ListLeadsResponse\x12L\n" +
	"\rDedupeContact\x12\x1c.evs.v1.DedupeContactRequest\x1a\x1d.evs.v1.DedupeContactResponseB\x81\x01\n" +
	"\n" +
	"com.evs.v1B\x11LeadIdentityProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_lead_identity_proto_rawDescOnce sync.Once
	file_evs_v1_lead_identity_proto_rawDescData []byte
)

func file_evs_v1_lead_identity_proto_rawDescGZIP() []byte {
	file_evs_v1_lead_identity_proto_rawDescOnce.Do(func() {
		file_evs_v1_lead_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_lead_identity_proto_rawDesc), len(file_evs_v1_lead_identity_proto_rawDesc)))
	})
	return file_evs_v1_lead_identity_proto_rawDescData
}

var file_evs_v1_lead_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_evs_v1_lead_identity_proto_goTypes = []any{
	(*UpsertContactRequest)(nil),  // 0: evs.v1.UpsertContactRequest
	(*UpsertContactResponse)(nil), // 1: evs.v1.UpsertContactResponse
	(*GetContactRequest)(nil),     // 2: evs.v1.GetContactRequest
	(*GetContactResponse)(nil),    // 3: evs.v1.GetContactResponse
	(*UpsertLeadRequest)(nil),     // 4: evs.v1.UpsertLeadRequest
	(*UpsertLeadResponse)(nil),    // 5: evs.v1.UpsertLeadResponse
	(*GetLeadRequest)(nil),        // 6: evs.v1.GetLeadRequest
	(*GetLeadResponse)(nil),       // 7: evs.v1.GetLeadResponse
	(*ListLeadsRequest)(nil),      // 8: evs.v1.ListLeadsRequest
	(*ListLeadsResponse)(nil),     // 9: evs.v1.ListLeadsResponse
	(*DedupeContactRequest)(nil),  // 10: evs.v1.DedupeContactRequest
	(*DedupeContactResponse)(nil), // 11: evs.v1.DedupeContactResponse
	(*Contact)(nil),               // 12: evs.v1.Contact
	(*Lead)(nil),                  // 13: evs.v1.Lead
	(*PageRequest)(nil),           // 14: evs.v1.PageRequest
	(*PageResponse)(nil),          // 15: evs.v1.PageResponse
}
var file_evs_v1_lead_identity_proto_depIdxs = []int32{
	12, // 0: evs.v1.UpsertContactRequest.contact:type_name -> evs.v1.Contact
	12, // 1: evs.v1.UpsertContactResponse.contact:type_name -> evs.v1.Contact
	12, // 2: evs.v1.GetContactResponse.contact:type_name -> evs.v1.Contact
	13, // 3: evs.v1.UpsertLeadRequest.lead:type_name -> evs.v1.Lead
	13, // 4: evs.v1.UpsertLeadResponse.lead:type_name -> evs.v1.Lead
	13, // 5: evs.v1.GetLeadResponse.lead:type_name -> evs.v1.Lead
	14, // 6: evs.v1.ListLeadsRequest.page:type_name -> evs.v1.PageRequest
	13, // 7: evs.v1.ListLeadsResponse.leads:type_name -> evs.v1.Lead
	15, // 8: evs.v1.ListLeadsResponse.page:type_name -> evs.v1.PageResponse
	12, // 9: evs.v1.DedupeContactResponse.matches:type_name -> evs.v1.Contact
	0,  // 10: evs.v1.LeadIdentityService.UpsertContact:input_type -> evs.v1.UpsertContactRequest
	2,  // 11: evs.v1.LeadIdentityService.GetContact:input_type -> evs.v1.GetContactRequest
	4,  // 12: evs.v1.LeadIdentityService.UpsertLead:input_type -> evs.v1.UpsertLeadRequest
	6,  // 13: evs.v1.LeadIdentityService.GetLead:input_type -> evs.v1.GetLeadRequest
	8,  // 14: evs.v1.LeadIdentityService.ListLeads:input_type -> evs.v1.ListLeadsRequest
	10, // 15: evs.v1.LeadIdentityService.DedupeContact:input_type -> evs.v1.DedupeContactRequest
	1,  // 16: evs.v1.LeadIdentityService.UpsertContact:output_type -> evs.v1.UpsertContactResponse
	3,  // 17: evs.v1.LeadIdentityService.GetContact:output_type -> evs.v1.GetContactResponse
	5,  // 18: evs.v1.LeadIdentityService.UpsertLead:output_type -> evs.v1.UpsertLeadResponse
	7,  // 19: evs.v1.LeadIdentityService.GetLead:output_type -> evs.v1.GetLeadResponse
	9,  // 20: evs.v1.LeadIdentityService.ListLeads:output_type -> evs.v1.ListLeadsResponse
	11, // 21: evs.v1.LeadIdentityService.DedupeContact:output_type -> evs.v1.DedupeContactResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_evs_v1_lead_identity_proto_init() }
func file_evs_v1_lead_identity_proto_init() {
	if File_evs_v1_lead_identity_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_lead_identity_proto_rawDesc), len(file_evs_v1_lead_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_lead_identity_proto_goTypes,
		DependencyIndexes: file_evs_v1_lead_identity_proto_depIdxs,
		MessageInfos:      file_evs_v1_lead_identity_proto_msgTypes,
	}.Build()
	File_evs_v1_lead_identity_proto = out.File
	file_evs_v1_lead_identity_proto_goTypes = nil
	file_evs_v1_lead_identity_proto_depIdxs = nil
}
