// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/llm_router.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelHint     string                 `protobuf:"bytes,2,opt,name=model_hint,json=modelHint,proto3" json:"model_hint,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_evs_v1_llm_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_llm_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_llm_router_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompleteRequest) GetModelHint() string {
	if x != nil {
		return x.ModelHint
	}
	return ""
}

func (x *CompleteRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type CompleteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ModelUsed        string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,4,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_evs_v1_llm_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_llm_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_llm_router_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompleteResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *CompleteResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *CompleteResponse) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type StreamCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelHint     string                 `protobuf:"bytes,2,opt,name=model_hint,json=modelHint,proto3" json:"model_hint,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCompleteRequest) Reset() {
	*x = StreamCompleteRequest{}
	mi := &file_evs_v1_llm_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCompleteRequest) ProtoMessage() {}

func (x *StreamCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_llm_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCompleteRequest.ProtoReflect.Descriptor instead.
func (*StreamCompleteRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_llm_router_proto_rawDescGZIP(), []int{2}
}

func (x *StreamCompleteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StreamCompleteRequest) GetModelHint() string {
	if x != nil {
		return x.ModelHint
	}
	return ""
}

func (x *StreamCompleteRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *StreamCompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *StreamCompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type StreamCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCompleteResponse) Reset() {
	*x = StreamCompleteResponse{}
	mi := &file_evs_v1_llm_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCompleteResponse) ProtoMessage() {}

func (x *StreamCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_llm_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCompleteResponse.ProtoReflect.Descriptor instead.
func (*StreamCompleteResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_llm_router_proto_rawDescGZIP(), []int{3}
}

func (x *StreamCompleteResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *StreamCompleteResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_evs_v1_llm_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_llm_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_evs_v1_llm_router_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_evs_v1_llm_router_proto protoreflect.FileDescriptor

const file_evs_v1_llm_router_proto_rawDesc = "" +
	"\n" +
	"\x17evs/v1/llm_router.proto\x12\x06evs.v1\"\xbf\x01\n" +
	"\x0fCompleteRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"model_hint\x18\x02 \x01(\tR\tmodelHint\x12/\n" +
	"\bmessages\x18\x03 \x03(\v2\x13.evs.v1.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\"\x9d\x01\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x04 \x01(\x05R\x10completionTokens\"\xc5\x01\n" +
	"\x15StreamCompleteRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"model_hint\x18\x02 \x01(\tR\tmodelHint\x12/\n" +
	"\bmessages\x18\x03 \x03(\v2\x13.evs.v1.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\"I\n" +
	"\x16StreamCompleteResponse\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\xa4\x01\n" +
	"\x10LlmRouterService\x12=\n" +
	"\bComplete\x12\x17.evs.v1.CompleteRequest\x1a\x18.evs.v1.CompleteResponse\x12Q\n" +
	"\x0eStreamComplete\x12\x1d.evs.v1.StreamCompleteRequest\x1a\x1e.evs.v1.StreamCompleteResponse0\x01B~\n" +
	"\n" +
	"com.evs.v1B\x0eLlmRouterProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_llm_router_proto_rawDescOnce sync.Once
	file_evs_v1_llm_router_proto_rawDescData []byte
)

func file_evs_v1_llm_router_proto_rawDescGZIP() []byte {
	file_evs_v1_llm_router_proto_rawDescOnce.Do(func() {
		file_evs_v1_llm_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_llm_router_proto_rawDesc), len(file_evs_v1_llm_router_proto_rawDesc)))
	})
	return file_evs_v1_llm_router_proto_rawDescData
}

var file_evs_v1_llm_router_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_evs_v1_llm_router_proto_goTypes = []any{
	(*CompleteRequest)(nil),        // 0: evs.v1.CompleteRequest
	(*CompleteResponse)(nil),       // 1: evs.v1.CompleteResponse
	(*StreamCompleteRequest)(nil),  // 2: evs.v1.StreamCompleteRequest
	(*StreamCompleteResponse)(nil), // 3: evs.v1.StreamCompleteResponse
	(*ChatMessage)(nil),            // 4: evs.v1.ChatMessage
}
var file_evs_v1_llm_router_proto_depIdxs = []int32{
	4, // 0: evs.v1.CompleteRequest.messages:type_name -> evs.v1.ChatMessage
	4, // 1: evs.v1.StreamCompleteRequest.messages:type_name -> evs.v1.ChatMessage
	0, // 2: evs.v1.LlmRouterService.Complete:input_type -> evs.v1.CompleteRequest
	2, // 3: evs.v1.LlmRouterService.StreamComplete:input_type -> evs.v1.StreamCompleteRequest
	1, // 4: evs.v1.LlmRouterService.Complete:output_type -> evs.v1.CompleteResponse
	3, // 5: evs.v1.LlmRouterService.StreamComplete:output_type -> evs.v1.StreamCompleteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_evs_v1_llm_router_proto_init() }
func file_evs_v1_llm_router_proto_init() {
	if File_evs_v1_llm_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_llm_router_proto_rawDesc), len(file_evs_v1_llm_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_llm_router_proto_goTypes,
		DependencyIndexes: file_evs_v1_llm_router_proto_depIdxs,
		MessageInfos:      file_evs_v1_llm_router_proto_msgTypes,
	}.Build()
	File_evs_v1_llm_router_proto = out.File
	file_evs_v1_llm_router_proto_goTypes = nil
	file_evs_v1_llm_router_proto_depIdxs = nil
}
