// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/scoring.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadId        string                 `protobuf:"bytes,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Features      map[string]string      `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreLeadRequest) Reset() {
	*x = ScoreLeadRequest{}
	mi := &file_evs_v1_scoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreLeadRequest) ProtoMessage() {}

func (x *ScoreLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreLeadRequest.ProtoReflect.Descriptor instead.
func (*ScoreLeadRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreLeadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScoreLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *ScoreLeadRequest) GetFeatures() map[string]string {
	if x != nil {
		return x.Features
	}
	return nil
}

type ScoreLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *LeadScore             `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreLeadResponse) Reset() {
	*x = ScoreLeadResponse{}
	mi := &file_evs_v1_scoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreLeadResponse) ProtoMessage() {}

func (x *ScoreLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreLeadResponse.ProtoReflect.Descriptor instead.
func (*ScoreLeadResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreLeadResponse) GetScore() *LeadScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type GetScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadId        string                 `protobuf:"bytes,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreRequest) Reset() {
	*x = GetScoreRequest{}
	mi := &file_evs_v1_scoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreRequest) ProtoMessage() {}

func (x *GetScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreRequest.ProtoReflect.Descriptor instead.
func (*GetScoreRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoreRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetScoreRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type GetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *LeadScore             `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreResponse) Reset() {
	*x = GetScoreResponse{}
	mi := &file_evs_v1_scoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreResponse) ProtoMessage() {}

func (x *GetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreResponse.ProtoReflect.Descriptor instead.
func (*GetScoreResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoreResponse) GetScore() *LeadScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type BatchScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadIds       []string               `protobuf:"bytes,2,rep,name=lead_ids,json=leadIds,proto3" json:"lead_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScoreRequest) Reset() {
	*x = BatchScoreRequest{}
	mi := &file_evs_v1_scoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScoreRequest) ProtoMessage() {}

func (x *BatchScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScoreRequest.ProtoReflect.Descriptor instead.
func (*BatchScoreRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{4}
}

func (x *BatchScoreRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchScoreRequest) GetLeadIds() []string {
	if x != nil {
		return x.LeadIds
	}
	return nil
}

type BatchScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*LeadScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScoreResponse) Reset() {
	*x = BatchScoreResponse{}
	mi := &file_evs_v1_scoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScoreResponse) ProtoMessage() {}

func (x *BatchScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScoreResponse.ProtoReflect.Descriptor instead.
func (*BatchScoreResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{5}
}

func (x *BatchScoreResponse) GetScores() []*LeadScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type LeadScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LeadId         string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Score          float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Band           string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"`
	FeatureWeights map[string]float64     `protobuf:"bytes,4,rep,name=feature_weights,json=featureWeights,proto3" json:"feature_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ScoredAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scored_at,json=scoredAt,proto3" json:"scored_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeadScore) Reset() {
	*x = LeadScore{}
	mi := &file_evs_v1_scoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadScore) ProtoMessage() {}

func (x *LeadScore) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_scoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadScore.ProtoReflect.Descriptor instead.
func (*LeadScore) Descriptor() ([]byte, []int) {
	return file_evs_v1_scoring_proto_rawDescGZIP(), []int{6}
}

func (x *LeadScore) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *LeadScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeadScore) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

func (x *LeadScore) GetFeatureWeights() map[string]float64 {
	if x != nil {
		return x.FeatureWeights
	}
	return nil
}

func (x *LeadScore) GetScoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScoredAt
	}
	return nil
}

var File_evs_v1_scoring_proto protoreflect.FileDescriptor

const file_evs_v1_scoring_proto_rawDesc = "" +
	"\n" +
	"\x14evs/v1/scoring.proto\x12\x06evs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\x10ScoreLeadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\alead_id\x18\x02 \x01(\tR\x06leadId\x12B\n" +
	"\bfeatures\x18\x03 \x03(\v2&.evs.v1.ScoreLeadRequest.FeaturesEntryR\bfeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x11ScoreLeadResponse\x12'\n" +
	"\x05score\x18\x01 \x01(\v2\x11.evs.v1.LeadScoreR\x05score\"G\n" +
	"\x0fGetScoreRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\alead_id\x18\x02 \x01(\tR\x06leadId\";\n" +
	"\x10GetScoreResponse\x12'\n" +
	"\x05score\x18\x01 \x01(\v2\x11.evs.v1.LeadScoreR\x05score\"K\n" +
	"\x11BatchScoreRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\blead_ids\x18\x02 \x03(\tR\aleadIds\"?\n" +
	"\x12BatchScoreResponse\x12)\n" +
	"\x06scores\x18\x01 \x03(\v2\x11.evs.v1.LeadScoreR\x06scores\"\x9a\x02\n" +
	"\tLeadScore\x12\x17\n" +
	"\alead_id\x18\x01 \x01(\tR\x06leadId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\x12N\n" +
	"\x0ffeature_weights\x18\x04 \x03(\v2%.evs.v1.LeadScore.FeatureWeightsEntryR\x0efeatureWeights\x127\n" +
	"\tscored_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bscoredAt\x1aA\n" +
	"\x13FeatureWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xd6\x01\n" +
	"\x0eScoringService\x12@\n" +
	"\tScoreLead\x12\x18.evs.v1.ScoreLeadRequest\x1a\x19.evs.v1.ScoreLeadResponse\x12=\n" +
	"\bGetScore\x12\x17.evs.v1.GetScoreRequest\x1a\x18.evs.v1.GetScoreResponse\x12C\n" +
	"\n" +
	"BatchScore\x12\x19.evs.v1.BatchScoreRequest\x1a\x1a.evs.v1.BatchScoreResponseB|\n" +
	"\n" +
	"com.evs.v1B\fScoringProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_scoring_proto_rawDescOnce sync.Once
	file_evs_v1_scoring_proto_rawDescData []byte
)

func file_evs_v1_scoring_proto_rawDescGZIP() []byte {
	file_evs_v1_scoring_proto_rawDescOnce.Do(func() {
		file_evs_v1_scoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_scoring_proto_rawDesc), len(file_evs_v1_scoring_proto_rawDesc)))
	})
	return file_evs_v1_scoring_proto_rawDescData
}

var file_evs_v1_scoring_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_evs_v1_scoring_proto_goTypes = []any{
	(*ScoreLeadRequest)(nil),      // 0: evs.v1.ScoreLeadRequest
	(*ScoreLeadResponse)(nil),     // 1: evs.v1.ScoreLeadResponse
	(*GetScoreRequest)(nil),       // 2: evs.v1.GetScoreRequest
	(*GetScoreResponse)(nil),      // 3: evs.v1.GetScoreResponse
	(*BatchScoreRequest)(nil),     // 4: evs.v1.BatchScoreRequest
	(*BatchScoreResponse)(nil),    // 5: evs.v1.BatchScoreResponse
	(*LeadScore)(nil),             // 6: evs.v1.LeadScore
	nil,                           // 7: evs.v1.ScoreLeadRequest.FeaturesEntry
	nil,                           // 8: evs.v1.LeadScore.FeatureWeightsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_evs_v1_scoring_proto_depIdxs = []int32{
	7, // 0: evs.v1.ScoreLeadRequest.features:type_name -> evs.v1.ScoreLeadRequest.FeaturesEntry
	6, // 1: evs.v1.ScoreLeadResponse.score:type_name -> evs.v1.LeadScore
	6, // 2: evs.v1.GetScoreResponse.score:type_name -> evs.v1.LeadScore
	6, // 3: evs.v1.BatchScoreResponse.scores:type_name -> evs.v1.LeadScore
	8, // 4: evs.v1.LeadScore.feature_weights:type_name -> evs.v1.LeadScore.FeatureWeightsEntry
	9, // 5: evs.v1.LeadScore.scored_at:type_name -> google.protobuf.Timestamp
	0, // 6: evs.v1.ScoringService.ScoreLead:input_type -> evs.v1.ScoreLeadRequest
	2, // 7: evs.v1.ScoringService.GetScore:input_type -> evs.v1.GetScoreRequest
	4, // 8: evs.v1.ScoringService.BatchScore:input_type -> evs.v1.BatchScoreRequest
	1, // 9: evs.v1.ScoringService.ScoreLead:output_type -> evs.v1.ScoreLeadResponse
	3, // 10: evs.v1.ScoringService.GetScore:output_type -> evs.v1.GetScoreResponse
	5, // 11: evs.v1.ScoringService.BatchScore:output_type -> evs.v1.BatchScoreResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_evs_v1_scoring_proto_init() }
func file_evs_v1_scoring_proto_init() {
	if File_evs_v1_scoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_scoring_proto_rawDesc), len(file_evs_v1_scoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_scoring_proto_goTypes,
		DependencyIndexes: file_evs_v1_scoring_proto_depIdxs,
		MessageInfos:      file_evs_v1_scoring_proto_msgTypes,
	}.Build()
	File_evs_v1_scoring_proto = out.File
	file_evs_v1_scoring_proto_goTypes = nil
	file_evs_v1_scoring_proto_depIdxs = nil
}
