// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/site_visit.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteVisit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LeadId         string                 `protobuf:"bytes,3,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	PropertyId     string                 `protobuf:"bytes,4,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	ScheduledAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AssignedUserId string                 `protobuf:"bytes,7,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	Notes          string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SiteVisit) Reset() {
	*x = SiteVisit{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteVisit) ProtoMessage() {}

func (x *SiteVisit) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteVisit.ProtoReflect.Descriptor instead.
func (*SiteVisit) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{0}
}

func (x *SiteVisit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SiteVisit) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SiteVisit) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *SiteVisit) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *SiteVisit) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *SiteVisit) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SiteVisit) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *SiteVisit) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ScheduleVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Visit         *SiteVisit             `protobuf:"bytes,2,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleVisitRequest) Reset() {
	*x = ScheduleVisitRequest{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleVisitRequest) ProtoMessage() {}

func (x *ScheduleVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleVisitRequest.ProtoReflect.Descriptor instead.
func (*ScheduleVisitRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleVisitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScheduleVisitRequest) GetVisit() *SiteVisit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type ScheduleVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *SiteVisit             `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleVisitResponse) Reset() {
	*x = ScheduleVisitResponse{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleVisitResponse) ProtoMessage() {}

func (x *ScheduleVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleVisitResponse.ProtoReflect.Descriptor instead.
func (*ScheduleVisitResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleVisitResponse) GetVisit() *SiteVisit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type RescheduleVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VisitId       string                 `protobuf:"bytes,2,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	NewTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=new_time,json=newTime,proto3" json:"new_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescheduleVisitRequest) Reset() {
	*x = RescheduleVisitRequest{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleVisitRequest) ProtoMessage() {}

func (x *RescheduleVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleVisitRequest.ProtoReflect.Descriptor instead.
func (*RescheduleVisitRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{3}
}

func (x *RescheduleVisitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RescheduleVisitRequest) GetVisitId() string {
	if x != nil {
		return x.VisitId
	}
	return ""
}

func (x *RescheduleVisitRequest) GetNewTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NewTime
	}
	return nil
}

type RescheduleVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *SiteVisit             `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescheduleVisitResponse) Reset() {
	*x = RescheduleVisitResponse{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleVisitResponse) ProtoMessage() {}

func (x *RescheduleVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleVisitResponse.ProtoReflect.Descriptor instead.
func (*RescheduleVisitResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{4}
}

func (x *RescheduleVisitResponse) GetVisit() *SiteVisit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type CancelVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VisitId       string                 `protobuf:"bytes,2,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelVisitRequest) Reset() {
	*x = CancelVisitRequest{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelVisitRequest) ProtoMessage() {}

func (x *CancelVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelVisitRequest.ProtoReflect.Descriptor instead.
func (*CancelVisitRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{5}
}

func (x *CancelVisitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CancelVisitRequest) GetVisitId() string {
	if x != nil {
		return x.VisitId
	}
	return ""
}

func (x *CancelVisitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *SiteVisit             `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelVisitResponse) Reset() {
	*x = CancelVisitResponse{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelVisitResponse) ProtoMessage() {}

func (x *CancelVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelVisitResponse.ProtoReflect.Descriptor instead.
func (*CancelVisitResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{6}
}

func (x *CancelVisitResponse) GetVisit() *SiteVisit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type CompleteVisitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VisitId       string                 `protobuf:"bytes,2,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteVisitRequest) Reset() {
	*x = CompleteVisitRequest{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteVisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteVisitRequest) ProtoMessage() {}

func (x *CompleteVisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteVisitRequest.ProtoReflect.Descriptor instead.
func (*CompleteVisitRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteVisitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompleteVisitRequest) GetVisitId() string {
	if x != nil {
		return x.VisitId
	}
	return ""
}

func (x *CompleteVisitRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type CompleteVisitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *SiteVisit             `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteVisitResponse) Reset() {
	*x = CompleteVisitResponse{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteVisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteVisitResponse) ProtoMessage() {}

func (x *CompleteVisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteVisitResponse.ProtoReflect.Descriptor instead.
func (*CompleteVisitResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteVisitResponse) GetVisit() *SiteVisit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type ListVisitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisitsRequest) Reset() {
	*x = ListVisitsRequest{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisitsRequest) ProtoMessage() {}

func (x *ListVisitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisitsRequest.ProtoReflect.Descriptor instead.
func (*ListVisitsRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{9}
}

func (x *ListVisitsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListVisitsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListVisitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visits        []*SiteVisit           `protobuf:"bytes,1,rep,name=visits,proto3" json:"visits,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisitsResponse) Reset() {
	*x = ListVisitsResponse{}
	mi := &file_evs_v1_site_visit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisitsResponse) ProtoMessage() {}

func (x *ListVisitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_site_visit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisitsResponse.ProtoReflect.Descriptor instead.
func (*ListVisitsResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_site_visit_proto_rawDescGZIP(), []int{10}
}

func (x *ListVisitsResponse) GetVisits() []*SiteVisit {
	if x != nil {
		return x.Visits
	}
	return nil
}

func (x *ListVisitsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_evs_v1_site_visit_proto protoreflect.FileDescriptor

const file_evs_v1_site_visit_proto_rawDesc = "" +
	"\n" +
	"\x17evs/v1/site_visit.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n" +
	"\tSiteVisit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\alead_id\x18\x03 \x01(\tR\x06leadId\x12\x1f\n" +
	"\vproperty_id\x18\x04 \x01(\tR\n" +
	"propertyId\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\x10assigned_user_id\x18\a \x01(\tR\x0eassignedUserId\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\"\\\n" +
	"\x14ScheduleVisitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x05visit\x18\x02 \x01(\v2\x11.evs.v1.SiteVisitR\x05visit\"@\n" +
	"\x15ScheduleVisitResponse\x12'\n" +
	"\x05visit\x18\x01 \x01(\v2\x11.evs.v1.SiteVisitR\x05visit\"\x87\x01\n" +
	"\x16RescheduleVisitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bvisit_id\x18\x02 \x01(\tR\avisitId\x125\n" +
	"\bnew_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\anewTime\"B\n" +
	"\x17RescheduleVisitResponse\x12'\n" +
	"\x05visit\x18\x01 \x01(\v2\x11.evs.v1.SiteVisitR\x05visit\"d\n" +
	"\x12CancelVisitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bvisit_id\x18\x02 \x01(\tR\avisitId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\">\n" +
	"\x13CancelVisitResponse\x12'\n" +
	"\x05visit\x18\x01 \x01(\v2\x11.evs.v1.SiteVisitR\x05visit\"h\n" +
	"\x14CompleteVisitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bvisit_id\x18\x02 \x01(\tR\avisitId\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\"@\n" +
	"\x15CompleteVisitResponse\x12'\n" +
	"\x05visit\x18\x01 \x01(\v2\x11.evs.v1.SiteVisitR\x05visit\"Y\n" +
	"\x11ListVisitsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"i\n" +
	"\x12ListVisitsResponse\x12)\n" +
	"\x06visits\x18\x01 \x03(\v2\x11.evs.v1.SiteVisitR\x06visits\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page2\x8f\x03\n" +
	"\x10SiteVisitService\x12L\n" +
	"\rScheduleVisit\x12\x1c.evs.v1.ScheduleVisitRequest\x1a\x1d.evs.v1.ScheduleVisitResponse\x12R\n" +
	"\x0fRescheduleVisit\x12\x1e.evs.v1.RescheduleVisitRequest\x1a\x1f.evs.v1.RescheduleVisitResponse\x12F\n" +
	"\vCancelVisit\x12\x1a.evs.v1.CancelVisitRequest\x1a\x1b.evs.v1.CancelVisitResponse\x12L\n" +
	"\rCompleteVisit\x12\x1c.evs.v1.CompleteVisitRequest\x1a\x1d.evs.v1.CompleteVisitResponse\x12C\n" +
	"\n" +
	"ListVisits\x12\x19.evs.v1.ListVisitsRequest\x1a\x1a.evs.v1.ListVisitsResponseB~\n" +
	"\n" +
	"com.evs.v1B\x0eSiteVisitProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_site_visit_proto_rawDescOnce sync.Once
	file_evs_v1_site_visit_proto_rawDescData []byte
)

func file_evs_v1_site_visit_proto_rawDescGZIP() []byte {
	file_evs_v1_site_visit_proto_rawDescOnce.Do(func() {
		file_evs_v1_site_visit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_site_visit_proto_rawDesc), len(file_evs_v1_site_visit_proto_rawDesc)))
	})
	return file_evs_v1_site_visit_proto_rawDescData
}

var file_evs_v1_site_visit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_evs_v1_site_visit_proto_goTypes = []any{
	(*SiteVisit)(nil),               // 0: evs.v1.SiteVisit
	(*ScheduleVisitRequest)(nil),    // 1: evs.v1.ScheduleVisitRequest
	(*ScheduleVisitResponse)(nil),   // 2: evs.v1.ScheduleVisitResponse
	(*RescheduleVisitRequest)(nil),  // 3: evs.v1.RescheduleVisitRequest
	(*RescheduleVisitResponse)(nil), // 4: evs.v1.RescheduleVisitResponse
	(*CancelVisitRequest)(nil),      // 5: evs.v1.CancelVisitRequest
	(*CancelVisitResponse)(nil),     // 6: evs.v1.CancelVisitResponse
	(*CompleteVisitRequest)(nil),    // 7: evs.v1.CompleteVisitRequest
	(*CompleteVisitResponse)(nil),   // 8: evs.v1.CompleteVisitResponse
	(*ListVisitsRequest)(nil),       // 9: evs.v1.ListVisitsRequest
	(*ListVisitsResponse)(nil),      // 10: evs.v1.ListVisitsResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*PageRequest)(nil),             // 12: evs.v1.PageRequest
	(*PageResponse)(nil),            // 13: evs.v1.PageResponse
}
var file_evs_v1_site_visit_proto_depIdxs = []int32{
	11, // 0: evs.v1.SiteVisit.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 1: evs.v1.ScheduleVisitRequest.visit:type_name -> evs.v1.SiteVisit
	0,  // 2: evs.v1.ScheduleVisitResponse.visit:type_name -> evs.v1.SiteVisit
	11, // 3: evs.v1.RescheduleVisitRequest.new_time:type_name -> google.protobuf.Timestamp
	0,  // 4: evs.v1.RescheduleVisitResponse.visit:type_name -> evs.v1.SiteVisit
	0,  // 5: evs.v1.CancelVisitResponse.visit:type_name -> evs.v1.SiteVisit
	0,  // 6: evs.v1.CompleteVisitResponse.visit:type_name -> evs.v1.SiteVisit
	12, // 7: evs.v1.ListVisitsRequest.page:type_name -> evs.v1.PageRequest
	0,  // 8: evs.v1.ListVisitsResponse.visits:type_name -> evs.v1.SiteVisit
	13, // 9: evs.v1.ListVisitsResponse.page:type_name -> evs.v1.PageResponse
	1,  // 10: evs.v1.SiteVisitService.ScheduleVisit:input_type -> evs.v1.ScheduleVisitRequest
	3,  // 11: evs.v1.SiteVisitService.RescheduleVisit:input_type -> evs.v1.RescheduleVisitRequest
	5,  // 12: evs.v1.SiteVisitService.CancelVisit:input_type -> evs.v1.CancelVisitRequest
	7,  // 13: evs.v1.SiteVisitService.CompleteVisit:input_type -> evs.v1.CompleteVisitRequest
	9,  // 14: evs.v1.SiteVisitService.ListVisits:input_type -> evs.v1.ListVisitsRequest
	2,  // 15: evs.v1.SiteVisitService.ScheduleVisit:output_type -> evs.v1.ScheduleVisitResponse
	4,  // 16: evs.v1.SiteVisitService.RescheduleVisit:output_type -> evs.v1.RescheduleVisitResponse
	6,  // 17: evs.v1.SiteVisitService.CancelVisit:output_type -> evs.v1.CancelVisitResponse
	8,  // 18: evs.v1.SiteVisitService.CompleteVisit:output_type -> evs.v1.CompleteVisitResponse
	10, // 19: evs.v1.SiteVisitService.ListVisits:output_type -> evs.v1.ListVisitsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_evs_v1_site_visit_proto_init() }
func file_evs_v1_site_visit_proto_init() {
	if File_evs_v1_site_visit_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_site_visit_proto_rawDesc), len(file_evs_v1_site_visit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_site_visit_proto_goTypes,
		DependencyIndexes: file_evs_v1_site_visit_proto_depIdxs,
		MessageInfos:      file_evs_v1_site_visit_proto_msgTypes,
	}.Build()
	File_evs_v1_site_visit_proto = out.File
	file_evs_v1_site_visit_proto_goTypes = nil
	file_evs_v1_site_visit_proto_depIdxs = nil
}
