// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evs/v1/telephony.proto

package evsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	FromE164      string                 `protobuf:"bytes,3,opt,name=from_e164,json=fromE164,proto3" json:"from_e164,omitempty"`
	ToE164        string                 `protobuf:"bytes,4,opt,name=to_e164,json=toE164,proto3" json:"to_e164,omitempty"`
	CampaignId    string                 `protobuf:"bytes,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceCallRequest) Reset() {
	*x = PlaceCallRequest{}
	mi := &file_evs_v1_telephony_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceCallRequest) ProtoMessage() {}

func (x *PlaceCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceCallRequest.ProtoReflect.Descriptor instead.
func (*PlaceCallRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceCallRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlaceCallRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *PlaceCallRequest) GetFromE164() string {
	if x != nil {
		return x.FromE164
	}
	return ""
}

func (x *PlaceCallRequest) GetToE164() string {
	if x != nil {
		return x.ToE164
	}
	return ""
}

func (x *PlaceCallRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type PlaceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallSession           `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceCallResponse) Reset() {
	*x = PlaceCallResponse{}
	mi := &file_evs_v1_telephony_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceCallResponse) ProtoMessage() {}

func (x *PlaceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceCallResponse.ProtoReflect.Descriptor instead.
func (*PlaceCallResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceCallResponse) GetCall() *CallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

type HangupCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallRequest) Reset() {
	*x = HangupCallRequest{}
	mi := &file_evs_v1_telephony_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallRequest) ProtoMessage() {}

func (x *HangupCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallRequest.ProtoReflect.Descriptor instead.
func (*HangupCallRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{2}
}

func (x *HangupCallRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HangupCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type HangupCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallResponse) Reset() {
	*x = HangupCallResponse{}
	mi := &file_evs_v1_telephony_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallResponse) ProtoMessage() {}

func (x *HangupCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallResponse.ProtoReflect.Descriptor instead.
func (*HangupCallResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{3}
}

type GetCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRequest) Reset() {
	*x = GetCallRequest{}
	mi := &file_evs_v1_telephony_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRequest) ProtoMessage() {}

func (x *GetCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRequest.ProtoReflect.Descriptor instead.
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{4}
}

func (x *GetCallRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *CallSession           `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResponse) Reset() {
	*x = GetCallResponse{}
	mi := &file_evs_v1_telephony_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResponse) ProtoMessage() {}

func (x *GetCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResponse.ProtoReflect.Descriptor instead.
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{5}
}

func (x *GetCallResponse) GetCall() *CallSession {
	if x != nil {
		return x.Call
	}
	return nil
}

type ListCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallsRequest) Reset() {
	*x = ListCallsRequest{}
	mi := &file_evs_v1_telephony_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallsRequest) ProtoMessage() {}

func (x *ListCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallsRequest.ProtoReflect.Descriptor instead.
func (*ListCallsRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{6}
}

func (x *ListCallsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCallsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListCallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*CallSession         `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallsResponse) Reset() {
	*x = ListCallsResponse{}
	mi := &file_evs_v1_telephony_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallsResponse) ProtoMessage() {}

func (x *ListCallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallsResponse.ProtoReflect.Descriptor instead.
func (*ListCallsResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{7}
}

func (x *ListCallsResponse) GetCalls() []*CallSession {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *ListCallsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type HandleProviderWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleProviderWebhookRequest) Reset() {
	*x = HandleProviderWebhookRequest{}
	mi := &file_evs_v1_telephony_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleProviderWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProviderWebhookRequest) ProtoMessage() {}

func (x *HandleProviderWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProviderWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleProviderWebhookRequest) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{8}
}

func (x *HandleProviderWebhookRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HandleProviderWebhookRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleProviderWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HandleProviderWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleProviderWebhookResponse) Reset() {
	*x = HandleProviderWebhookResponse{}
	mi := &file_evs_v1_telephony_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleProviderWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProviderWebhookResponse) ProtoMessage() {}

func (x *HandleProviderWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evs_v1_telephony_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProviderWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleProviderWebhookResponse) Descriptor() ([]byte, []int) {
	return file_evs_v1_telephony_proto_rawDescGZIP(), []int{9}
}

var File_evs_v1_telephony_proto protoreflect.FileDescriptor

const file_evs_v1_telephony_proto_rawDesc = "" +
	"\n" +
	"\x16evs/v1/telephony.proto\x12\x06evs.v1\x1a\x13evs/v1/common.proto\"\xa5\x01\n" +
	"\x10PlaceCallRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x1b\n" +
	"\tfrom_e164\x18\x03 \x01(\tR\bfromE164\x12\x17\n" +
	"\ato_e164\x18\x04 \x01(\tR\x06toE164\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\tR\n" +
	"campaignId\"<\n" +
	"\x11PlaceCallResponse\x12'\n" +
	"\x04call\x18\x01 \x01(\v2\x13.evs.v1.CallSessionR\x04call\"I\n" +
	"\x11HangupCallRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"\x14\n" +
	"\x12HangupCallResponse\"F\n" +
	"\x0eGetCallRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\":\n" +
	"\x0fGetCallResponse\x12'\n" +
	"\x04call\x18\x01 \x01(\v2\x13.evs.v1.CallSessionR\x04call\"X\n" +
	"\x10ListCallsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.evs.v1.PageRequestR\x04page\"h\n" +
	"\x11ListCallsResponse\x12)\n" +
	"\x05calls\x18\x01 \x03(\v2\x13.evs.v1.CallSessionR\x05calls\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.evs.v1.PageResponseR\x04page\"\xd7\x01\n" +
	"\x1cHandleProviderWebhookRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12K\n" +
	"\aheaders\x18\x03 \x03(\v21.evs.v1.HandleProviderWebhookRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\x1dHandleProviderWebhookResponse2\xfd\x02\n" +
	"\x10TelephonyService\x12@\n" +
	"\tPlaceCall\x12\x18.evs.v1.PlaceCallRequest\x1a\x19.evs.v1.PlaceCallResponse\x12C\n" +
	"\n" +
	"HangupCall\x12\x19.evs.v1.HangupCallRequest\x1a\x1a.evs.v1.HangupCallResponse\x12:\n" +
	"\aGetCall\x12\x16.evs.v1.GetCallRequest\x1a\x17.evs.v1.GetCallResponse\x12@\n" +
	"\tListCalls\x12\x18.evs.v1.ListCallsRequest\x1a\x19.evs.v1.ListCallsResponse\x12d\n" +
	"\x15HandleProviderWebhook\x12$.evs.v1.HandleProviderWebhookRequest\x1a%.evs.v1.HandleProviderWebhookResponseB~\n" +
	"\n" +
	"com.evs.v1B\x0eTelephonyProtoP\x01Z'github.com/lead/libs/go/pb/evs/v1;evsv1\xa2\x02\x03EXX\xaa\x02\x06Evs.V1\xca\x02\x06Evs\\V1\xe2\x02\x12Evs\\V1\\GPBMetadata\xea\x02\aEvs::V1b\x06proto3"

var (
	file_evs_v1_telephony_proto_rawDescOnce sync.Once
	file_evs_v1_telephony_proto_rawDescData []byte
)

func file_evs_v1_telephony_proto_rawDescGZIP() []byte {
	file_evs_v1_telephony_proto_rawDescOnce.Do(func() {
		file_evs_v1_telephony_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evs_v1_telephony_proto_rawDesc), len(file_evs_v1_telephony_proto_rawDesc)))
	})
	return file_evs_v1_telephony_proto_rawDescData
}

var file_evs_v1_telephony_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_evs_v1_telephony_proto_goTypes = []any{
	(*PlaceCallRequest)(nil),              // 0: evs.v1.PlaceCallRequest
	(*PlaceCallResponse)(nil),             // 1: evs.v1.PlaceCallResponse
	(*HangupCallRequest)(nil),             // 2: evs.v1.HangupCallRequest
	(*HangupCallResponse)(nil),            // 3: evs.v1.HangupCallResponse
	(*GetCallRequest)(nil),                // 4: evs.v1.GetCallRequest
	(*GetCallResponse)(nil),               // 5: evs.v1.GetCallResponse
	(*ListCallsRequest)(nil),              // 6: evs.v1.ListCallsRequest
	(*ListCallsResponse)(nil),             // 7: evs.v1.ListCallsResponse
	(*HandleProviderWebhookRequest)(nil),  // 8: evs.v1.HandleProviderWebhookRequest
	(*HandleProviderWebhookResponse)(nil), // 9: evs.v1.HandleProviderWebhookResponse
	nil,                                   // 10: evs.v1.HandleProviderWebhookRequest.HeadersEntry
	(*CallSession)(nil),                   // 11: evs.v1.CallSession
	(*PageRequest)(nil),                   // 12: evs.v1.PageRequest
	(*PageResponse)(nil),                  // 13: evs.v1.PageResponse
}
var file_evs_v1_telephony_proto_depIdxs = []int32{
	11, // 0: evs.v1.PlaceCallResponse.call:type_name -> evs.v1.CallSession
	11, // 1: evs.v1.GetCallResponse.call:type_name -> evs.v1.CallSession
	12, // 2: evs.v1.ListCallsRequest.page:type_name -> evs.v1.PageRequest
	11, // 3: evs.v1.ListCallsResponse.calls:type_name -> evs.v1.CallSession
	13, // 4: evs.v1.ListCallsResponse.page:type_name -> evs.v1.PageResponse
	10, // 5: evs.v1.HandleProviderWebhookRequest.headers:type_name -> evs.v1.HandleProviderWebhookRequest.HeadersEntry
	0,  // 6: evs.v1.TelephonyService.PlaceCall:input_type -> evs.v1.PlaceCallRequest
	2,  // 7: evs.v1.TelephonyService.HangupCall:input_type -> evs.v1.HangupCallRequest
	4,  // 8: evs.v1.TelephonyService.GetCall:input_type -> evs.v1.GetCallRequest
	6,  // 9: evs.v1.TelephonyService.ListCalls:input_type -> evs.v1.ListCallsRequest
	8,  // 10: evs.v1.TelephonyService.HandleProviderWebhook:input_type -> evs.v1.HandleProviderWebhookRequest
	1,  // 11: evs.v1.TelephonyService.PlaceCall:output_type -> evs.v1.PlaceCallResponse
	3,  // 12: evs.v1.TelephonyService.HangupCall:output_type -> evs.v1.HangupCallResponse
	5,  // 13: evs.v1.TelephonyService.GetCall:output_type -> evs.v1.GetCallResponse
	7,  // 14: evs.v1.TelephonyService.ListCalls:output_type -> evs.v1.ListCallsResponse
	9,  // 15: evs.v1.TelephonyService.HandleProviderWebhook:output_type -> evs.v1.HandleProviderWebhookResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_evs_v1_telephony_proto_init() }
func file_evs_v1_telephony_proto_init() {
	if File_evs_v1_telephony_proto != nil {
		return
	}
	file_evs_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evs_v1_telephony_proto_rawDesc), len(file_evs_v1_telephony_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evs_v1_telephony_proto_goTypes,
		DependencyIndexes: file_evs_v1_telephony_proto_depIdxs,
		MessageInfos:      file_evs_v1_telephony_proto_msgTypes,
	}.Build()
	File_evs_v1_telephony_proto = out.File
	file_evs_v1_telephony_proto_goTypes = nil
	file_evs_v1_telephony_proto_depIdxs = nil
}
