export const currentAdminRole = 'super_admin';
export const canSeeModelSwitcher = currentAdminRole === 'super_admin';

export const modelOptions = {
  llm: [
    {
      id: 'groq_llama',
      name: 'Groq Llama 3.x',
      type: 'api',
      cost: 'INR 0.11',
      latency: '90 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'qwen3_32b',
      name: 'Qwen3 32B vLLM',
      type: 'self hosted',
      cost: 'INR 0.04',
      latency: 'offline',
      requiresGpu: true,
      healthy: false,
    },
    {
      id: 'llama3_70b',
      name: 'Llama 3.3 70B Q4',
      type: 'self hosted',
      cost: 'INR 0.08',
      latency: 'offline',
      requiresGpu: true,
      healthy: false,
    },
    {
      id: 'mistral_7b',
      name: 'Mistral 7B',
      type: 'self hosted',
      cost: 'INR 0.02',
      latency: '180 ms',
      requiresGpu: true,
      healthy: true,
    },
    {
      id: 'sarvam_105b',
      name: 'Sarvam 105B',
      type: 'api',
      cost: 'INR 0.16',
      latency: '160 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'openai_gpt4o',
      name: 'OpenAI GPT-4o',
      type: 'api',
      cost: 'INR 0.42',
      latency: '220 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'anthropic_claude',
      name: 'Anthropic Claude Sonnet',
      type: 'api',
      cost: 'INR 0.48',
      latency: '240 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'google_gemini',
      name: 'Google Gemini Flash',
      type: 'api',
      cost: 'INR 0.19',
      latency: '190 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'openrouter',
      name: 'OpenRouter',
      type: 'api',
      cost: 'INR 0.22',
      latency: '260 ms',
      requiresGpu: false,
      healthy: true,
    },
  ],
  stt: [
    {
      id: 'sarvam',
      name: 'Sarvam Saarika',
      type: 'api',
      cost: 'INR 0.05',
      latency: '150 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'indicconformer',
      name: 'IndicConformer',
      type: 'self hosted',
      cost: 'INR 0.01',
      latency: '140 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'faster_whisper',
      name: 'faster-whisper',
      type: 'self hosted',
      cost: 'INR 0.02',
      latency: 'offline',
      requiresGpu: true,
      healthy: false,
    },
    {
      id: 'groq_whisper',
      name: 'Groq Whisper',
      type: 'api',
      cost: 'INR 0.07',
      latency: '120 ms',
      requiresGpu: false,
      healthy: true,
    },
  ],
  tts: [
    {
      id: 'sarvam_bulbul',
      name: 'Sarvam Bulbul',
      type: 'api',
      cost: 'INR 0.05',
      latency: '130 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'indic_parler',
      name: 'Indic Parler-TTS',
      type: 'self hosted',
      cost: 'INR 0.02',
      latency: 'offline',
      requiresGpu: true,
      healthy: false,
    },
    {
      id: 'indicf5',
      name: 'IndicF5',
      type: 'self hosted',
      cost: 'INR 0.03',
      latency: 'offline',
      requiresGpu: true,
      healthy: false,
    },
    {
      id: 'kokoro',
      name: 'Kokoro TTS',
      type: 'self hosted',
      cost: 'INR 0.01',
      latency: '85 ms',
      requiresGpu: false,
      healthy: true,
    },
    {
      id: 'elevenlabs',
      name: 'ElevenLabs',
      type: 'api',
      cost: 'INR 0.28',
      latency: '260 ms',
      requiresGpu: false,
      healthy: true,
    },
  ],
};

export const globalModelSelection = {
  llm: 'groq_llama',
  stt: 'sarvam',
  tts: 'sarvam_bulbul',
};

export const tenantModelOverrides = [
  {
    tenant: 'tenant-north',
    name: 'North Star Realty',
    llm: 'openrouter',
    stt: 'sarvam',
    tts: 'sarvam_bulbul',
    updated: '10:42',
  },
  {
    tenant: 'tenant-west',
    name: 'Westline Estates',
    llm: 'mistral_7b',
    stt: 'groq_whisper',
    tts: 'kokoro',
    updated: '09:18',
  },
];

export const tenants = [
  {
    id: 'tenant-north',
    name: 'North Star Realty',
    status: 'active',
    plan: 'Growth',
    usage: '84%',
    owner: 'Riya Sharma',
  },
  {
    id: 'tenant-west',
    name: 'Westline Estates',
    status: 'active',
    plan: 'Scale',
    usage: '57%',
    owner: 'Kabir Mehta',
  },
  {
    id: 'tenant-south',
    name: 'Southgate Homes',
    status: 'suspended',
    plan: 'Launch',
    usage: '100%',
    owner: 'Anika Rao',
  },
];

export const providers = [
  {
    name: 'Plivo',
    key: 'plivo',
    online: true,
    failure: '1.2%',
    latency: '120 ms',
    circuit: 'closed',
    inFlight: 42,
  },
  {
    name: 'Meta WA',
    key: 'meta_wa',
    online: true,
    failure: '3.1%',
    latency: '180 ms',
    circuit: 'closed',
    inFlight: 9,
  },
  {
    name: 'Groq',
    key: 'groq',
    online: true,
    failure: '2.0%',
    latency: '90 ms',
    circuit: 'closed',
    inFlight: 18,
  },
  {
    name: 'OpenRouter',
    key: 'openrouter',
    online: true,
    failure: '4.2%',
    latency: '240 ms',
    circuit: 'closed',
    inFlight: 6,
  },
  {
    name: 'Sarvam',
    key: 'sarvam',
    online: true,
    failure: '2.4%',
    latency: '160 ms',
    circuit: 'closed',
    inFlight: 14,
  },
  {
    name: 'ElevenLabs',
    key: 'elevenlabs',
    online: true,
    failure: '5.1%',
    latency: '260 ms',
    circuit: 'closed',
    inFlight: 2,
  },
  {
    name: 'vLLM',
    key: 'vllm',
    online: false,
    failure: '100%',
    latency: 'offline',
    circuit: 'open',
    inFlight: 0,
  },
  {
    name: 'IndicConformer',
    key: 'indicconformer',
    online: true,
    failure: '0.8%',
    latency: '140 ms',
    circuit: 'closed',
    inFlight: 5,
  },
];

export const failedJobs = [
  {
    id: 'dlq-001',
    queue: 'NATS DLQ',
    subject: 'call.completed',
    tenant: 'tenant-north',
    workflow: 'wf-991',
    attempts: 3,
    error: 'billing cap exceeded',
  },
  {
    id: 'tmp-884',
    queue: 'Temporal failed',
    subject: 'campaign-run',
    tenant: 'tenant-west',
    workflow: 'campaign-77',
    attempts: 2,
    error: 'provider circuit open',
  },
  {
    id: 'dlq-019',
    queue: 'NATS DLQ',
    subject: 'wa.template.send',
    tenant: 'tenant-south',
    workflow: 'wf-104',
    attempts: 5,
    error: 'template missing language',
  },
];

export const supportLead = {
  phone: '+919876543210',
  name: 'Amit Verma',
  tenant: 'tenant-north',
  status: 'hot',
  timeline: [
    { at: '08:42', type: 'call.started', detail: 'AI qualified 2BHK budget around 85 lakh' },
    { at: '09:04', type: 'whatsapp.sent', detail: 'Sent brochure and site visit options' },
    { at: '09:12', type: 'site_visit.booked', detail: 'Booked Saturday 11:00' },
  ],
};

export const auditRows = [
  {
    actor: 'admin-7',
    role: 'super_admin',
    action: 'tenant.impersonate',
    target: 'tenant-north',
    ticket: 'SUP-123',
    reason: 'support escalation',
    at: '10:34',
  },
  {
    actor: 'ops-2',
    role: 'ops_admin',
    action: 'feature_flag.update',
    target: 'premium_tts',
    ticket: 'OPS-88',
    reason: 'controlled rollout',
    at: '10:11',
  },
  {
    actor: 'admin-1',
    role: 'super_admin',
    action: 'provider.kill_switch.pause',
    target: 'vllm',
    ticket: 'INC-77',
    reason: 'elevated 5xx',
    at: '09:51',
  },
];

export const featureFlags = [
  {
    key: 'ai_quality_review',
    tenant: 'tenant-north',
    enabled: true,
    description: 'Route low-confidence AI sessions to review',
  },
  {
    key: 'premium_tts',
    tenant: 'tenant-west',
    enabled: false,
    description: 'Allow ElevenLabs fallback',
  },
  {
    key: 'site_visit_auto_confirm',
    tenant: 'tenant-north',
    enabled: true,
    description: 'Auto-confirm visits after WhatsApp acknowledgement',
  },
];

export const qualityItems = [
  {
    id: 'qa-101',
    tenant: 'tenant-north',
    session: 'sess-551',
    status: 'queued',
    reason: 'low confidence handoff',
  },
  {
    id: 'qa-102',
    tenant: 'tenant-west',
    session: 'sess-552',
    status: 'queued',
    reason: 'claim rewritten by guardrail',
  },
];
