# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evs/events/v1/envelope.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'evs/events/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65vs/events/v1/envelope.proto\x12\revs.events.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n\x08\x45nvelope\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x1b\n\ttenant_id\x18\x02 \x01(\tR\x08tenantId\x12\x1d\n\nevent_type\x18\x03 \x01(\tR\teventType\x12;\n\x0boccurred_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\noccurredAt\x12\x18\n\x07version\x18\x05 \x01(\tR\x07version\x12.\n\x07payload\x18\x06 \x01(\x0b\x32\x14.google.protobuf.AnyR\x07payload\x12@\n\rtrace_context\x18\x07 \x01(\x0b\x32\x1b.evs.events.v1.TraceContextR\x0ctraceContext\x12\x1a\n\x08producer\x18\x08 \x01(\tR\x08producer\x12%\n\x0e\x63orrelation_id\x18\t \x01(\tR\rcorrelationId\"j\n\x0cTraceContext\x12 \n\x0btraceparent\x18\x01 \x01(\tR\x0btraceparent\x12\x1e\n\ntracestate\x18\x02 \x01(\tR\ntracestate\x12\x18\n\x07\x62\x61ggage\x18\x03 \x01(\tR\x07\x62\x61ggageB\xab\x01\n\x11\x63om.evs.events.v1B\rEnvelopeProtoP\x01Z1github.com/lead/libs/go/pb/evs/events/v1;eventsv1\xa2\x02\x03\x45\x45X\xaa\x02\rEvs.Events.V1\xca\x02\rEvs\\Events\\V1\xe2\x02\x19\x45vs\\Events\\V1\\GPBMetadata\xea\x02\x0f\x45vs::Events::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evs.events.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.evs.events.v1B\rEnvelopeProtoP\001Z1github.com/lead/libs/go/pb/evs/events/v1;eventsv1\242\002\003EEX\252\002\rEvs.Events.V1\312\002\rEvs\\Events\\V1\342\002\031Evs\\Events\\V1\\GPBMetadata\352\002\017Evs::Events::V1'
  _globals['_ENVELOPE']._serialized_start=108
  _globals['_ENVELOPE']._serialized_end=473
  _globals['_TRACECONTEXT']._serialized_start=475
  _globals['_TRACECONTEXT']._serialized_end=581
# @@protoc_insertion_point(module_scope)
